import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { assessChangeReadiness, renderCompactHandoff } from '../scripts/dev/change-readiness.mjs';

const hash=value=>createHash('sha256').update(value).digest('hex');
async function fixture(){
  const root=await mkdtemp(path.join(os.tmpdir(),'af-ready-'));await mkdir(path.join(root,'.runtime/contracts'),{recursive:true});await writeFile(path.join(root,'source.txt'),'source');await writeFile(path.join(root,'evidence'),'passed');await writeFile(path.join(root,'tasks.md'),'- [x] 1.1 Complete behavior\n- [x] 2.1 Verify behavior\n');await writeFile(path.join(root,'handoff.md'),'change-x\nreviewed-clean\nverify-1\nreview-1\n');const source={revision:'worktree',files:[{path:'source.txt',sha256:hash('source')}]},base={version:1,objective:'Check change',criteria:[{id:'C1',description:'Behavior works'}],source,scope:[{path:'source.txt',boundary:'whole file'}],allowedActions:['Run check'],resources:[],evidenceDirectory:'.runtime/contracts/evidence',budget:{timeSeconds:60,providerCalls:0},stopConditions:['Stop on source change'],returnConditions:['Return result']};
  const verification={...base,assignmentId:'verify-1',role:'verification',checks:[{id:'T1',command:'node check.mjs',expected:'exit 0'}],additionalChecks:'within-scope'},verificationResult={version:1,assignmentId:'verify-1',role:'verification',summary:'passed',disposition:'returned',source:{...source,stable:true},limits:[],model:{requested:'gpt-5.6-luna / medium',observed:null,usage:null},cleanup:[],criteria:[{id:'C1',status:'pass',observation:'passed',evidence:['evidence'],checks:['T1']}],checks:[{id:'T1',command:'node check.mjs',authorization:null,status:'executed',exit:0,outcome:'pass',observation:'passed',evidence:['evidence']}]},review={...base,assignmentId:'review-1',role:'review',checks:[],additionalChecks:'forbidden'},reviewResult={version:1,assignmentId:'review-1',role:'review',summary:'clean',disposition:'returned',source:{...source,stable:true},limits:[],model:{requested:'inherit',observed:null,usage:null},cleanup:[],scope:[{path:'source.txt',status:'reviewed',observation:'clean'}],findings:[]};
  for(const [name,value] of Object.entries({verification,verificationResult,review,reviewResult}))await writeFile(path.join(root,`.runtime/contracts/${name}.json`),JSON.stringify(value));
  const input={version:1,change:'change-x',lifecycle:'reviewed-clean',capabilities:['runtime'],integrationBoundaries:['entrypoint','effect'],slices:[{id:'vertical',capabilities:['runtime'],integrationBoundaries:['entrypoint','effect'],scenarios:['S1']}],scenarios:[{id:'S1',requirement:'Production flow',entrypoint:{kind:'production',path:'source.txt'},effectful:true,negativeCases:['lost receipt'],recovery:true,checks:[{command:'node check.mjs',evidence:['evidence']}]}],contracts:{verification:{assignment:'.runtime/contracts/verification.json',result:'.runtime/contracts/verificationResult.json'},review:{assignment:'.runtime/contracts/review.json',result:'.runtime/contracts/reviewResult.json'}},closeout:{taskFile:'tasks.md',handoffFile:'handoff.md',requiredHandoffMarkers:['change-x','reviewed-clean','verify-1','review-1']}};return{root,input};
}

describe('change readiness gate',()=>{
  it('accepts only production-mapped, source-matched, reviewed-clean work',async()=>{const {root,input}=await fixture(),report=await assessChangeReadiness(input,{root});expect(report).toMatchObject({ready:true,coverage:{scenarios:1,effectful:1},contracts:{verification:{ready:true,sourceMatches:true},review:{ready:true,sourceMatches:true}}});expect(renderCompactHandoff(input,report)).toContain('reviewed-clean');});
  it('rejects fixture-only coverage, incomplete recovery, stale status and unsliced large changes',async()=>{const {root,input}=await fixture();input.lifecycle='verified';input.capabilities=['a','b','c'];input.slices=[{id:'only',capabilities:['a','b','c'],integrationBoundaries:['entrypoint','effect'],scenarios:['S1']}];input.scenarios[0].entrypoint.kind='fixture';input.scenarios[0].negativeCases=[];input.scenarios[0].recovery=false;const report=await assessChangeReadiness(input,{root});expect(report.ready).toBe(false);expect(report.errors.join('\n')).toMatch(/not closable|production entrypoint|negative cases|at least two/);});
  it('rejects missing or unverified scenario evidence',async()=>{const {root,input}=await fixture();input.scenarios[0].checks[0].evidence=['missing-evidence'];let report=await assessChangeReadiness(input,{root});expect(report.errors.join('\n')).toMatch(/missing-evidence|not bound to passing verification evidence/);input.scenarios[0].checks[0]={command:'node different.mjs',evidence:['evidence']};report=await assessChangeReadiness(input,{root});expect(report.errors.join('\n')).toContain('not bound to passing verification evidence');});
  it('rejects duplicate slices even when their count satisfies the large-change gate',async()=>{const {root,input}=await fixture();input.capabilities=['a','b','c'];input.slices=[input.slices[0],{...structuredClone(input.slices[0]),id:'duplicate'}];const report=await assessChangeReadiness(input,{root});expect(report.errors.join('\n')).toMatch(/duplicates another slice|assigned to more than one slice/);});
});
