import { describe, it, expect } from 'vitest';
import { mkdtemp, writeFile, readFile, mkdir } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { GameClient } from '../packages/factorio/src/client.js';
import { Lifecycle, barrier, completeZip, reconciliation, sha256, validateCheckpoint, prepareManagedLoad, verifyLoaded, captureCheckpoint, state } from '../packages/factorio/src/lifecycle.js';
import type { ControlState, Checkpoint } from '../packages/factorio/src/lifecycle.js';
import { validateRequest } from '@autofactorio/contracts';
const saved:ControlState={ok:true,epoch:'e1',session:'s1',revision:2,generation:1,armed:false,ready:false,paused:true,neutral:true,ticksToRun:0,tick:100,ticksPlayed:200,experimentTick:100,scenarioElapsed:100,injections:1,checkpoint:'save',ledger:{pending:{commandId:'pending',status:'suspended',acceptedTick:10,endedTick:100,completed:0,unexecuted:1,steps:[]}},intents:{pending:[{kind:'walk',position:{x:2,y:0}}]},production:{},mods:{autofactorio:'0.1.0'}};
const world={tick:100,entities:[],actors:{}};
function zip(){const bytes=Buffer.alloc(68);bytes.writeUInt32LE(0x02014b50);bytes.writeUInt32LE(0x06054b50,46);bytes.writeUInt16LE(1,54);bytes.writeUInt16LE(1,56);bytes.writeUInt32LE(46,58);return bytes;}
async function fixture(){const dir=await mkdtemp(path.join(os.tmpdir(),'af-checkpoint-'));const bytes=zip();const m:Checkpoint={schema:1,source:'managed-disarmed',name:'save',save:'save.zip',sha256:sha256(bytes),size:bytes.length,eventCursor:5,captured:structuredClone(saved),world,modHash:'mod'};await writeFile(path.join(dir,'save.zip'),bytes);const file=path.join(dir,'save.json');await writeFile(file,JSON.stringify(m));return {dir,file,m};}
describe('phase 04 controlled recovery',()=>{
 it.each(['armed','paused','neutral','ticksToRun'] as const)('rejects unsafe barrier %s',key=>{const s={...saved,[key]:key==='ticksToRun'?1:!saved[key]};expect(()=>barrier(s)).toThrow();});
 it('rejects live saved orders',()=>{expect(()=>barrier({...saved,ledger:{pending:{...saved.ledger.pending!,status:'running'}}})).toThrow('Live order');});
 it('does not restore post-checkpoint claims as world effects',()=>{const latest={pending:{...saved.ledger.pending!,status:'cancelled' as const},new:{...saved.ledger.pending!,commandId:'new',status:'completed' as const}};const plan=reconciliation(saved,latest);expect(plan.cancelledAfterCheckpoint).toEqual(['pending']);expect(plan.absentAfterRollback).toEqual(['new']);expect(plan.worldLedger).toEqual(saved.ledger);expect(plan.requiresFreshAuthorization).toEqual(['pending']);});
 it('rejects truncated ZIP and accepts a final central directory',()=>{expect(completeZip(zip())).toBe(true);expect(completeZip(zip().subarray(0,-1))).toBe(false);expect(completeZip(Buffer.from('PK'))).toBe(false);});
 it('validates and copies a completed managed checkpoint',async()=>{const {dir,file}=await fixture();expect((await validateCheckpoint(file,'mod')).eventCursor).toBe(5);await prepareManagedLoad(file,'mod',path.join(dir,'load'));expect(await readFile(path.join(dir,'load/save.zip'))).toEqual(zip());});
 it.each(['checksum','mod','armed','path','cursor','checkpoint'])('rejects manifest mismatch %s',async kind=>{const {file,m}=await fixture();if(kind==='checksum')m.sha256='bad';if(kind==='mod')m.modHash='old';if(kind==='armed')m.captured.armed=true;if(kind==='path')m.save='../save.zip';if(kind==='cursor')m.eventCursor=-1;if(kind==='checkpoint')m.captured.checkpoint='other';await writeFile(file,JSON.stringify(m));await expect(validateCheckpoint(file,'mod')).rejects.toThrow();});
 it('refuses native autosaves without a managed manifest',async()=>{const {dir}=await fixture();await expect(prepareManagedLoad(path.join(dir,'_autosave1.json'),'mod',path.join(dir,'load'))).rejects.toThrow('Uncontrolled');});
 it('checks loaded receipts, tick and effects before reconciliation',async()=>{const {m}=await fixture();expect(()=>verifyLoaded(m,{...saved,ticksPlayed:999},world)).not.toThrow();expect(()=>verifyLoaded(m,{...saved,tick:101},world)).toThrow();expect(()=>verifyLoaded(m,saved,{...world,entities:[{}]})).toThrow();});
 it('closes admission before an unconfirmed pause and forbids automatic arm on heartbeat',async()=>{let reject=false;const calls:string[]=[];const port={command:async (r:string)=>{calls.push(r);if(reject)throw new Error('disconnected');return JSON.stringify(saved);},close:()=>{}};const game=new GameClient(port,()=>{});const life=new Lifecycle(port,game,()=>{});game.admission=false;await life.heartbeat(saved);expect(game.admission).toBe(false);game.admission=true;reject=true;await expect(life.pause(saved)).rejects.toThrow('disconnected');expect(game.admission).toBe(false);expect(calls).toHaveLength(2);});
 it('does not open admission for unknown work or rejected arm',async()=>{const port={command:async()=>JSON.stringify({ok:false,error:'stale_control_revision'}),close:()=>{}};const game=new GameClient(port,()=>{});const life=new Lifecycle(port,game,()=>{});game.admission=false;game.unresolved.add('pending');await expect(life.arm(saved)).rejects.toThrow('Unknown');game.unresolved.clear();await expect(life.arm(saved)).rejects.toThrow('stale');expect(game.admission).toBe(false);});
 it('acknowledges pause only after neutral controls and frozen simulation are observed',async()=>{
  const queue=[{...saved,paused:false,neutral:false},{...saved,paused:false,neutral:true},saved];let calls=0;
  const port={command:async()=>JSON.stringify(queue[calls++]),close:()=>{}};const game=new GameClient(port,()=>{});const life=new Lifecycle(port,game,()=>{});
  expect(await life.pause(saved)).toEqual(saved);expect(calls).toBe(3);expect(game.admission).toBe(false);
 });
 it('requires epoch/session for gameplay cancellation and rejects control operations',()=>{expect(()=>validateRequest({op:'cancel',commandId:'pending'})).toThrow();expect(()=>validateRequest({op:'arm',epoch:'e1',session:'s1',revision:2})).toThrow();expect(validateRequest({op:'cancel',commandId:'pending',epoch:'e1',session:'s1'}).op).toBe('cancel');});
 it('does not publish interrupted captures',async()=>{const {dir}=await fixture();const log=path.join(dir,'process.log');await writeFile(log,'');const output=path.join(dir,'out');await mkdir(output);const port={command:async()=>JSON.stringify(saved),close:()=>{}};const life=new Lifecycle(port,new GameClient(port,()=>{}),()=>{});await expect(captureCheckpoint({lifecycle:life,paused:saved,saveDirectory:dir,outputDirectory:output,logFile:log,eventCursor:()=>1,world:async()=>world,modHash:'mod',timeoutMs:1})).rejects.toThrow('not published');const {readdir}=await import('node:fs/promises');expect(await readdir(output)).toEqual([]);});
 it('rejects malformed control telemetry',()=>{expect(()=>state({...saved,neutral:undefined})).toThrow();expect(()=>state({...saved,ledger:{bad:saved.ledger.pending}})).toThrow();});
});
