import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync, symlinkSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { validateWorkshopAssignment } from '@autofactorio/contracts';
import type { WorkshopScore } from '@autofactorio/contracts';
import { SqliteJournal } from '../packages/storage/src/journal.js';
import type { EventContext } from '../packages/core/execution/durable.js';
import { WorkshopOrchestrator } from '../packages/core/workshop/orchestrator.js';
import { WorkshopUsageLedger } from '../packages/core/workshop/usage.js';
import { LearningService } from '../packages/core/workshop/learning.js';
import { HelperQuota, authorizeHelperPlan, invokeConfinedHelper } from '../packages/core/workshop/helper-worker.js';
import { admissibleFeedback, redactBlindCandidate, validateInvocationProvenance } from '../packages/core/workshop/provenance.js';

const rate=(numerator:string,denominator='1')=>({numerator,denominator});
const manifest=(overrides:Record<string,unknown>={})=>validateWorkshopAssignment({schema:1,id:'workshop',revision:1,comparisonSeries:'series',objective:'Build circuits',source:{kind:'brief',id:null,numericTargetText:'60 per minute'},ports:[{id:'input',direction:'input',product:{kind:'item',name:'iron-plate',quality:'normal',surface:'nauvis'},position:{x:0,y:0},facing:0,transport:'belt',rate:rate('1'),unit:'units-per-game-second',required:true},{id:'output',direction:'output',product:{kind:'item',name:'electronic-circuit',quality:'normal',surface:'nauvis'},position:{x:10,y:0},facing:8,transport:'belt',rate:rate('1'),unit:'units-per-game-second',required:true}],profileId:'starter-assembly',profileRevision:1,gameFingerprint:'a'.repeat(64),footprint:{width:32,height:16,clearance:2,maxTiles:512},construction:'direct',libraryAccess:true,improveRevision:null,requestedSpeed:rate('10'),settlingTicks:600,throughput:[{portId:'output',windowTicks:3600,windows:5,quantum:rate('1'),productionError:rate('0'),deliveryError:rate('0'),maxStockDrawdown:rate('2'),maxResidual:rate('1'),interval:'(startTick,endTick]'}],rubric:{version:'r1',weights:{throughput:rate('1')},materiality:{throughput:rate('1','100')}},iterations:{attempts:5,mode:'exact',earlyStop:false,plateauRounds:2},checkpoints:{brief:false,afterScore:false,libraryAdmission:false,learningActivation:false,timeoutMs:1000,timeoutAction:'finish'},budgets:{wallMs:100000,gameTicks:200000,turns:30,toolCalls:100,reportedTokens:null,learningReservedTurns:3,learningReservedTools:10},models:{sessionDefault:{provider:'openai',modelId:'gpt-6-astra',reasoningEffort:'low'},overrides:{scorer:{provider:'openai',modelId:'gpt-5.6-sol',reasoningEffort:'medium'}}},...overrides});
function fixture(){const root=mkdtempSync(path.join(os.tmpdir(),'af-workshop-orchestration-'));const journal=new SqliteJournal(path.join(root,'run.sqlite'));let n=0;const context=():EventContext=>({run:'run',epoch:'epoch',wallTime:new Date(1_800_000_000_000+n++).toISOString(),gameTick:null,actor:'operator',task:null,causation:null,correlation:null,visibility:{kind:'operator'}});return{root,journal,context,close(){journal.close();rmSync(root,{recursive:true,force:true});}};}
const selection=[{provider:'openai',modelId:'gpt-6-astra',reasoningEffort:'low'},{provider:'openai',modelId:'gpt-5.6-sol',reasoningEffort:'medium'}];

describe('durable workshop orchestration and accounting',()=>{
  it('keeps blind critique and private comparison provenance separate even after paraphrase attempts',()=>{const scorer={role:'scorer' as const,session:'score-session',selection:{provider:'openai',modelId:'gpt-5.6-sol',reasoningEffort:'medium'},reportedModel:null,reportedEffort:null,contextLineage:['assignment','candidate','measurement'],libraryBlind:true,iteration:1,contextScope:'library-blind-score' as const,modelConcreteId:'gpt-5.6-sol'};expect(()=>validateInvocationProvenance(scorer,'scorer','score-session',1)).not.toThrow();expect(redactBlindCandidate({family:'hidden',libraryHistory:['layout'],suggestion:'Place four assemblers',artifactHash:'a'})).toEqual({suggestion:'Place four assemblers',artifactHash:'a'});expect(admissibleFeedback({...scorer,role:'private-comparison',session:'private',contextScope:'private-comparison',libraryBlind:false},'designer')).toBe(false);expect(admissibleFeedback(scorer,'designer')).toBe(true);expect(()=>validateInvocationProvenance({...scorer,role:'designer'},'scorer','score-session',1)).toThrow('provenance');});
  it('runs exactly five unattended attempts, preserves the best valid revision, and resumes effects without duplication',async()=>{const f=fixture();try{let effects=0;let service=new WorkshopOrchestrator(f.journal,f.context);service.configure('workshop',manifest(),'baseline');service.preflight('workshop',selection);
    for(let number=1;number<=5;number++){service.beginIteration('workshop');service.advance('workshop','building');const candidate={sessionId:'workshop',iteration:number,artifactHash:`artifact-${number}`,assignmentRevision:1,bundleHash:'baseline',evidence:[`design-${number}`]};service.artifact('workshop',candidate);service.advance('workshop','frozen');service.advance('workshop','measuring');service.evaluation('workshop',{schema:1,attemptId:`workshop:${number}`,valid:number!==4,passed:number!==4,reasons:number===4?['control_invalid']:[],ports:[],evidence:[`measure-${number}`]});service.advance('workshop','scoring');const score:WorkshopScore={schema:1,candidate,rubricVersion:'r1',eligible:number!==4,dimensions:{throughput:{value:number===3?10:number,unit:'score',evidence:[],judgment:'measured'}},feedback:'feedback',interactionFeedback:'interaction',invalidReasons:number===4?['control_invalid']:[]};service.score('workshop',score,`round ${number}`);if(number<5)expect(service.next('workshop')).toBe('iterate');}
    expect(service.next('workshop')).toBe('finalize');expect(service.get('workshop')).toMatchObject({bestIteration:3,validIterations:[1,2,3,5]});const first=await service.effect('workshop','admit',async()=>({count:++effects}));service=new WorkshopOrchestrator(f.journal,f.context);const repeated=await service.effect('workshop','admit',async()=>({count:++effects}));expect(first).toEqual(repeated);expect(effects).toBe(1);
  }finally{f.close();}});
  it('holds an unacknowledged external effect across controller replacement instead of replaying it',async()=>{const f=fixture();try{let service=new WorkshopOrchestrator(f.journal,f.context);service.configure('unknown',manifest({id:'unknown'}),'baseline');service.preflight('unknown',selection);service.beginIteration('unknown');await expect(service.effect('unknown','unknown:1:design',async()=>{throw new Error('controller lost after dispatch');})).rejects.toThrow('controller lost');service=new WorkshopOrchestrator(f.journal,f.context);let replayed=false;await expect(service.effect('unknown','unknown:1:design',async()=>{replayed=true;return{artifact:'wrong'};},async()=>({resolved:false}))).rejects.toThrow('outcome unknown');expect(replayed).toBe(false);expect(service.get('unknown').operationIntents['unknown:1:design']).toMatchObject({status:'unknown',stage:'designing'});expect(service.hold('unknown','unresolved design effect')).toMatchObject({stage:'held',stopReason:'unresolved design effect'});}finally{f.close();}});
  it('rejects unavailable pinned selections, stale steering, and attributes cumulative or unknown usage once',()=>{const f=fixture();try{const service=new WorkshopOrchestrator(f.journal,f.context);service.configure('workshop',manifest({iterations:{attempts:2,mode:'maximum',earlyStop:true,plateauRounds:1},checkpoints:{brief:false,afterScore:true,libraryAdmission:false,learningActivation:false,timeoutMs:1000,timeoutAction:'continue'}}),'baseline');expect(()=>service.preflight('workshop',selection.slice(0,1))).toThrow('scorer');
    const usage=new WorkshopUsageLedger(f.journal,f.context);const base={sessionId:'workshop',role:'designer',iteration:1,batchId:null,monetaryAmount:null,allowanceRemaining:null,owner:'workshop' as const,at:'2026-01-01T00:00:00Z'};usage.record({...base,id:'u1',invocationId:'invoke-1',cumulativeTokens:100});usage.record({...base,id:'u2',invocationId:'invoke-1',cumulativeTokens:100});usage.record({...base,id:'u3',invocationId:'invoke-1',cumulativeTokens:130});usage.record({...base,id:'u4',invocationId:'invoke-2',cumulativeTokens:null});usage.record({...base,id:'u5',invocationId:'review-1',role:'learning-review',iteration:null,batchId:'batch-1',owner:'learning',cumulativeTokens:20});expect(usage.state('workshop')).toMatchObject({totalTokens:150,byRole:{designer:130,'learning-review':20},byBatch:{'batch-1':20},byOwner:{workshop:130,learning:20},unknownTokenInvocations:['invoke-2'],monetaryAmount:null});expect(()=>usage.record({...base,id:'collision',invocationId:'review-1',owner:'workshop',cumulativeTokens:25})).toThrow('ownership collision');expect(()=>usage.admit('workshop',27,0,{turns:30,tools:100,learningReservedTurns:3,learningReservedTools:10})).toThrow('exhausted');
  }finally{f.close();}});
  it('records assisted steering, restores every durable stage, and finalizes an explicit no-valid result',()=>{const f=fixture();try{let service=new WorkshopOrchestrator(f.journal,f.context);service.configure('empty',manifest({id:'empty',iterations:{attempts:1,mode:'exact',earlyStop:false,plateauRounds:1},checkpoints:{brief:false,afterScore:true,libraryAdmission:false,learningActivation:false,timeoutMs:1000,timeoutAction:'continue'}}),'baseline');service.preflight('empty',selection);service.beginIteration('empty');service.advance('empty','building');service=new WorkshopOrchestrator(f.journal,f.context);expect(service.get('empty').stage).toBe('building');const candidate={sessionId:'empty',iteration:1,artifactHash:'bad',assignmentRevision:1,bundleHash:'baseline',evidence:['design']};service.artifact('empty',candidate);for(const stage of ['frozen','measuring'] as const){service.advance('empty',stage);service=new WorkshopOrchestrator(f.journal,f.context);expect(service.get('empty').stage).toBe(stage);}service.evaluation('empty',{schema:1,attemptId:'empty:1',valid:false,passed:false,reasons:['invalid'],ports:[],evidence:['measure']});service.advance('empty','scoring');service.score('empty',{schema:1,candidate,rubricVersion:'r1',eligible:false,dimensions:{throughput:{value:null,unit:'score',evidence:[],judgment:'unknown'}},feedback:'invalid',interactionFeedback:'',invalidReasons:['invalid']},'invalid');expect(service.next('empty')).toBe('checkpoint');service.resolveCheckpoint('empty',1,'continue');expect(service.next('empty')).toBe('finalize');expect(service.finalize('empty')).toMatchObject({stage:'finalizing',bestIteration:null,finalOutcome:'no-valid-result'});
    service.configure('assist',manifest({id:'assist',iterations:{attempts:2,mode:'maximum',earlyStop:false,plateauRounds:1},checkpoints:{brief:false,afterScore:true,libraryAdmission:false,learningActivation:false,timeoutMs:1000,timeoutAction:'continue'}}),'baseline');service.preflight('assist',selection);service.beginIteration('assist');service.advance('assist','building');const assisted={...candidate,sessionId:'assist',artifactHash:'ok'};service.artifact('assist',assisted);service.advance('assist','frozen');service.advance('assist','measuring');service.evaluation('assist',{schema:1,attemptId:'assist:1',valid:true,passed:true,reasons:[],ports:[],evidence:[]});service.advance('assist','scoring');service.score('assist',{schema:1,candidate:assisted,rubricVersion:'r1',eligible:true,dimensions:{throughput:{value:1,unit:'score',evidence:[],judgment:'measured'}},feedback:'',interactionFeedback:'',invalidReasons:[]},'ok');expect(service.next('assist')).toBe('checkpoint');expect(()=>service.steer('assist',2,'stale')).toThrow('Stale');expect(service.steer('assist',1,'Move output east')).toMatchObject({assistance:[{revision:1,text:'Move output east'}]});service.recheckAvailability('assist',selection);expect(()=>service.recheckAvailability('assist',selection.slice(0,1))).toThrow('scorer');
  }finally{f.close();}});
  it('persists brief, after-score, library and learning checkpoints with continue, finish and timeout decisions',()=>{const f=fixture();try{let service=new WorkshopOrchestrator(f.journal,f.context);const checkpoints={brief:true,afterScore:true,libraryAdmission:true,learningActivation:true,timeoutMs:1000,timeoutAction:'continue' as const};service.configure('gates',manifest({id:'gates',iterations:{attempts:1,mode:'exact',earlyStop:false,plateauRounds:1},checkpoints}),'baseline');service.preflight('gates',selection);expect(service.requestCheckpoint('gates','brief','preflight')).toBe(true);service=new WorkshopOrchestrator(f.journal,f.context);expect(service.get('gates')).toMatchObject({stage:'checkpoint',checkpoint:{kind:'brief',resumeStage:'preflight'}});expect(service.resolveCheckpoint('gates',1,'continue','Approved brief')).toMatchObject({stage:'preflight',checkpoint:null,checkpointDecisions:{brief:'continue'}});service.beginIteration('gates');service.advance('gates','building');const candidate={sessionId:'gates',iteration:1,artifactHash:'gated',assignmentRevision:1,bundleHash:'baseline',evidence:[]};service.artifact('gates',candidate);service.advance('gates','frozen');service.advance('gates','measuring');service.evaluation('gates',{schema:1,attemptId:'gates:1',valid:true,passed:true,reasons:[],ports:[],evidence:[]});service.advance('gates','scoring');service.score('gates',{schema:1,candidate,rubricVersion:'r1',eligible:true,dimensions:{throughput:{value:1,unit:'score',evidence:[],judgment:'measured'}},feedback:'',interactionFeedback:'',invalidReasons:[]},'');expect(service.next('gates')).toBe('checkpoint');service=new WorkshopOrchestrator(f.journal,f.context);expect(service.resolveCheckpoint('gates',2,'continue')).toMatchObject({stage:'scoring',checkpointDecisions:{'afterScore:1':'continue'}});expect(service.next('gates')).toBe('finalize');service.finalize('gates');expect(service.requestCheckpoint('gates','libraryAdmission','finalizing')).toBe(true);expect(service.resolveCheckpoint('gates',3,'continue')).toMatchObject({stage:'finalizing'});service.advance('gates','library');service.advance('gates','learning');expect(service.requestCheckpoint('gates','learningActivation','learning')).toBe(true);service=new WorkshopOrchestrator(f.journal,f.context);expect(service.resolveCheckpoint('gates',4,'finish','Operator ended after review')).toMatchObject({stage:'reported',stopReason:'checkpoint_finish:learningActivation',finalOutcome:'best-valid'});
    service.configure('timeout',manifest({id:'timeout',checkpoints:{...checkpoints,afterScore:false,libraryAdmission:false,learningActivation:false}}),'baseline');service.preflight('timeout',selection);service.requestCheckpoint('timeout','brief','preflight');service=new WorkshopOrchestrator(f.journal,f.context);expect(service.timeout('timeout','2027-02-01T00:00:00.000Z')).toBe('continue');expect(service.get('timeout')).toMatchObject({stage:'preflight',checkpointDecisions:{brief:'continue'},assistance:[{text:'review-timeout'}]});
  }finally{f.close();}});
  it('does not promote a structurally valid target miss and uses rubric direction for best selection',()=>{const f=fixture();try{const run=(service:WorkshopOrchestrator,id:string,number:number,passed:boolean,throughput:number,space:number)=>{service.beginIteration(id);service.advance(id,'building');const candidate={sessionId:id,iteration:number,artifactHash:`${id}-${number}`,assignmentRevision:1,bundleHash:'baseline',evidence:[]};service.artifact(id,candidate);service.advance(id,'frozen');service.advance(id,'measuring');service.evaluation(id,{schema:1,attemptId:`${id}:${number}`,valid:true,passed,reasons:passed?[]:['sustained_target_failed'],ports:[],evidence:[]});service.advance(id,'scoring');service.score(id,{schema:1,candidate,rubricVersion:'r1',eligible:passed,dimensions:{throughput:{value:throughput,unit:'items',evidence:[],judgment:'measured'},space:{value:space,unit:'tiles',evidence:[],judgment:'derived'}},feedback:'',interactionFeedback:'',invalidReasons:passed?[]:['sustained_target_failed']},'');};const miss=new WorkshopOrchestrator(f.journal,f.context);miss.configure('miss',manifest({id:'miss',iterations:{attempts:1,mode:'exact',earlyStop:false,plateauRounds:1}}),'baseline');miss.preflight('miss',selection);run(miss,'miss',1,false,100,1);expect(miss.finalize('miss')).toMatchObject({bestIteration:null,validIterations:[],finalOutcome:'no-valid-result'});const weighted=new WorkshopOrchestrator(f.journal,f.context);weighted.configure('weighted',manifest({id:'weighted',rubric:{version:'r1',weights:{throughput:rate('1'),space:rate('10')},materiality:{throughput:rate('0'),space:rate('0')},directions:{throughput:'maximize',space:'minimize'}},iterations:{attempts:2,mode:'exact',earlyStop:false,plateauRounds:1}}),'baseline');weighted.preflight('weighted',selection);run(weighted,'weighted',1,true,10,100);expect(weighted.next('weighted')).toBe('iterate');run(weighted,'weighted',2,true,9,50);expect(weighted.get('weighted').bestIteration).toBe(2);}finally{f.close();}});
});

describe('bounded learning and activated helper confinement',()=>{
  it('binds gates to the final combined bundle and atomically rejects a stale competing activation',()=>{const f=fixture();try{const learning=new LearningService(f.journal,f.context,{maxCandidates:3,maxAttempts:2,maxLessonsPerRole:10,maxBriefingBytes:16384,maxBundles:2});const candidate=learning.candidate({id:'c1',batchId:'batch',scope:'designer-instructions',content:'Check port identity before routing.',evidence:['failure-1'],contextLineage:['public-session'],libraryIndependent:true});learning.attempt(candidate.id);learning.decide(candidate.id,'accept','Improves deterministic routing',null);const controls=['baseline','regression'];const a=learning.assemble({incumbentHash:'baseline',expectedGeneration:0,files:{'designer.instructions':'check ports'},requiredControls:controls,policyHash:'policy',retrievalHash:'retrieval',catalogHash:'catalog',candidates:['c1']});const b=learning.assemble({incumbentHash:'baseline',expectedGeneration:0,files:{'designer.instructions':'check ports twice'},requiredControls:controls,policyHash:'policy',retrievalHash:'retrieval',catalogHash:'catalog',candidates:['c1']});
    const attest=(hash:string,kind:'deterministic'|'interaction'|'behavior'|'review',passed=true)=>learning.attest(hash,{kind,bundleHash:hash,incumbentHash:'baseline',generation:0,controlSuite:'controls-v1',controls,environment:'node24-factorio2.0.77',passed,conclusive:true,evidence:[kind]});for(const kind of ['deterministic','interaction','behavior','review'] as const)attest(a.hash,kind);attest(b.hash,'deterministic');attest(b.hash,'interaction',false);attest(b.hash,'interaction');attest(b.hash,'behavior');attest(b.hash,'review');expect(()=>learning.activate(b.hash,'activate-b')).toThrow('interaction');expect(learning.activate(a.hash,'activate-a')).toMatchObject({generation:1,activeHash:a.hash});expect(learning.activate(a.hash,'activate-a')).toMatchObject({generation:1});expect(()=>learning.activate(b.hash,'activate-b2')).toThrow('Stale');const pinned=learning.pin('existing-session');learning.rollback('baseline','rollback');expect(learning.pin('existing-session')).toEqual(pinned);expect(learning.pin('future-session')).toMatchObject({generation:2,hash:'baseline'});
    expect(()=>learning.candidate({id:'private',batchId:'batch-2',scope:'lesson',content:'copy hidden layout',evidence:['private'],contextLineage:['private-comparison'],libraryIndependent:false})).toThrow('Private library');
    expect(()=>learning.assemble({incumbentHash:'baseline',expectedGeneration:2,files:{'renamed-helper.mjs':'x'} as never,requiredControls:['baseline'],policyHash:'p',retrievalHash:'r',catalogHash:'c',candidates:[]})).toThrow('unregistered');expect(()=>learning.attest(a.hash,{kind:'review',bundleHash:a.hash,incumbentHash:'baseline',generation:0,controlSuite:'controls-v1',controls:['baseline'],environment:'node24-factorio2.0.77',passed:true,conclusive:true,evidence:['incomplete']})).toThrow('complete controls');
  }finally{f.close();}});
  it('attests and pins each follow-on activation as one complete effective bundle',()=>{const f=fixture();try{
    const learning=new LearningService(f.journal,f.context,{maxCandidates:3,maxAttempts:2,maxLessonsPerRole:10,maxBriefingBytes:16384,maxBundles:1}),firstControls=['incumbent-control'];
    const first=learning.assemble({incumbentHash:'baseline',expectedGeneration:0,files:{'designer.instructions':'keep ports clear','lessons.json':'[{"lesson":"use exact rates"}]'},requiredControls:firstControls,policyHash:'policy-1',retrievalHash:'retrieval-1',catalogHash:'catalog-1',candidates:[]});
    for(const kind of ['deterministic','interaction','behavior','review'] as const)learning.attest(first.hash,{kind,bundleHash:first.hash,incumbentHash:'baseline',generation:0,controlSuite:'controls-0',controls:firstControls,environment:'test',passed:true,conclusive:true,evidence:[kind]});
    learning.activate(first.hash,'activate-first');
    const second=learning.assemble({incumbentHash:first.hash,expectedGeneration:1,files:{'scorer.instructions':'cite measured evidence'},requiredControls:['new-control'],policyHash:'policy-2',retrievalHash:'retrieval-2',catalogHash:'catalog-2',candidates:[]}),combinedControls=['incumbent-control','new-control'];
    expect(second.files).toEqual({'designer.instructions':'keep ports clear','lessons.json':'[{"lesson":"use exact rates"}]','scorer.instructions':'cite measured evidence'});expect(second.requiredControls).toEqual(combinedControls);
    expect(()=>learning.attest(second.hash,{kind:'deterministic',bundleHash:second.hash,incumbentHash:first.hash,generation:1,controlSuite:'controls-1',controls:['new-control'],environment:'test',passed:true,conclusive:true,evidence:['deterministic']})).toThrow('complete controls');
    for(const kind of ['deterministic','interaction','behavior','review'] as const)learning.attest(second.hash,{kind,bundleHash:second.hash,incumbentHash:first.hash,generation:1,controlSuite:'controls-1',controls:combinedControls,environment:'test',passed:true,conclusive:true,evidence:[kind]});
    learning.activate(second.hash,'activate-second');expect(learning.pinnedBundle('future')).toMatchObject({generation:2,hash:second.hash,files:second.files,policyHash:'policy-2'});
  }finally{f.close();}});
  it('requires behavioral evidence before activating a lesson-only bundle',()=>{const f=fixture();try{
    const learning=new LearningService(f.journal,f.context,{maxCandidates:3,maxAttempts:2,maxLessonsPerRole:10,maxBriefingBytes:16384,maxBundles:1}),controls=['lesson-control'],bundle=learning.assemble({incumbentHash:'baseline',expectedGeneration:0,files:{'lessons.json':'[{"lesson":"keep output lanes clear"}]'},requiredControls:controls,policyHash:'policy',retrievalHash:'retrieval',catalogHash:'catalog',candidates:[]});
    expect(bundle.behaviorChanging).toBe(true);for(const kind of ['deterministic','interaction','review'] as const)learning.attest(bundle.hash,{kind,bundleHash:bundle.hash,incumbentHash:'baseline',generation:0,controlSuite:'lesson-suite',controls,environment:'test',passed:true,conclusive:true,evidence:[kind]});expect(()=>learning.activate(bundle.hash,'activate-lesson')).toThrow('behavior');learning.attest(bundle.hash,{kind:'behavior',bundleHash:bundle.hash,incumbentHash:'baseline',generation:0,controlSuite:'lesson-suite',controls,environment:'test',passed:true,conclusive:true,evidence:['behavior']});expect(learning.activate(bundle.hash,'activate-lesson')).toMatchObject({activeHash:bundle.hash,generation:1});
  }finally{f.close();}});
  it('enforces lesson count and briefing caps while retaining relocation and retirement reasons',()=>{const f=fixture();try{const learning=new LearningService(f.journal,f.context,{maxCandidates:3,maxAttempts:1,maxLessonsPerRole:1,maxBriefingBytes:16,maxBundles:1});const first=learning.candidate({id:'one',batchId:'a',scope:'lesson',content:'short',evidence:['e1'],contextLineage:['public'],libraryIndependent:true});learning.decide(first.id,'accept','supported',null);const second=learning.candidate({id:'two',batchId:'b',scope:'lesson',content:'other',evidence:['e2'],contextLineage:['public'],libraryIndependent:true});expect(()=>learning.decide(second.id,'accept','overflow',null)).toThrow('count cap');expect(learning.relocate(second.id,'scorer-instructions','narrower retrieval scope')).toMatchObject({state:'relocated',reason:'narrower retrieval scope'});expect(learning.retire(first.id,'superseded by deterministic guard')).toMatchObject({state:'retired'});expect(learning.retrieve('lesson')).toEqual({values:[],omitted:[]});expect(()=>learning.assemble({incumbentHash:'baseline',expectedGeneration:0,files:{'designer.instructions':'x'.repeat(17)},requiredControls:['baseline'],policyHash:'p',retrievalHash:'r',catalogHash:'c',candidates:[]})).toThrow('instruction budget');
  }finally{f.close();}});
  it('runs helpers out of process with bounded I/O and denies host files, network, child processes and path escapes',async()=>{const root=mkdtempSync(path.join(os.tmpdir(),'af-helper-'));const bundle=path.join(root,'bundle'),scratch=path.join(root,'scratch'),outside=path.join(root,'outside');mkdirSync(bundle);mkdirSync(scratch);mkdirSync(outside);const helper=path.join(bundle,'helper.mjs');const secret=path.join(outside,'secret.txt');writeFileSync(secret,'secret');writeFileSync(helper,`input=>({revision:input.revision,actions:[],fs:typeof require==='undefined'?'denied':'allowed',net:typeof fetch==='undefined'?'denied':'allowed',child:typeof process==='undefined'?'denied':'allowed',env:typeof process==='undefined'?'denied':'allowed'})`);const hash=createHash('sha256').update(readFileSync(helper)).digest('hex');const policy={wallMs:5000,inputBytes:2048,outputBytes:4096,scratchBytes:4096,invocations:1,policyHash:'policy'};try{const output=await invokeConfinedHelper({worker:path.resolve('scripts/workshop-helper-worker.mjs'),bundleRoot:bundle,helper,expectedHash:hash,scratch,value:{revision:7},policy,quota:new HelperQuota(policy)}) as Record<string,unknown>;expect(output).toMatchObject({fs:'denied',net:'denied',child:'denied',env:'denied'});expect(authorizeHelperPlan({revision:7,actions:[]},7,['place'],1)).toMatchObject({revision:7,actions:[]});await expect(invokeConfinedHelper({worker:path.resolve('scripts/workshop-helper-worker.mjs'),bundleRoot:bundle,helper:secret,expectedHash:'x',scratch,value:{},policy,quota:new HelperQuota(policy)})).rejects.toThrow('escape');const junction=path.join(scratch,'escape');symlinkSync(outside,junction,'junction');await expect(invokeConfinedHelper({worker:path.resolve('scripts/workshop-helper-worker.mjs'),bundleRoot:bundle,helper,expectedHash:hash,scratch,value:{revision:7},policy,quota:new HelperQuota(policy)})).rejects.toThrow('junction');}finally{rmSync(root,{recursive:true,force:true});}});
  it('fails closed on helper hash, invocation quota, output policy and stale action plans',async()=>{const root=mkdtempSync(path.join(os.tmpdir(),'af-helper-policy-')),bundle=path.join(root,'bundle'),scratch=path.join(root,'scratch');mkdirSync(bundle);mkdirSync(scratch);const helper=path.join(bundle,'helper.mjs');writeFileSync(helper,'input=>({revision:input.revision,actions:[],padding:"x".repeat(100)})');const hash=createHash('sha256').update(readFileSync(helper)).digest('hex'),policy={wallMs:5000,inputBytes:100,outputBytes:40,scratchBytes:10,invocations:1,policyHash:'policy'},quota=new HelperQuota(policy);try{await expect(invokeConfinedHelper({worker:path.resolve('scripts/workshop-helper-worker.mjs'),bundleRoot:bundle,helper,expectedHash:'changed',scratch,value:{revision:1},policy,quota:new HelperQuota(policy)})).rejects.toThrow('hash mismatch');await expect(invokeConfinedHelper({worker:path.resolve('scripts/workshop-helper-worker.mjs'),bundleRoot:bundle,helper,expectedHash:hash,scratch,value:{revision:1},policy,quota})).rejects.toThrow('output quota');await expect(invokeConfinedHelper({worker:path.resolve('scripts/workshop-helper-worker.mjs'),bundleRoot:bundle,helper,expectedHash:hash,scratch,value:{revision:1},policy,quota})).rejects.toThrow('quota exhausted');expect(()=>authorizeHelperPlan({revision:2,actions:[]},1,['place'],1)).toThrow('Stale');expect(()=>authorizeHelperPlan({revision:1,actions:[{kind:'admin',payload:{}}]},1,['place'],1)).toThrow('Unauthorized');}finally{rmSync(root,{recursive:true,force:true});}});
});
