import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { createHash } from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import type { BlueprintDocument, WorkshopEvaluationReport } from '@autofactorio/contracts';
import { LiveWorkshopHost, ManagedWorkshopInference } from '../apps/runtime/workshop-live-host.js';
import type { WorkshopGame, WorkshopInference } from '../apps/runtime/workshop-live-host.js';
import { BlueprintLibrary } from '../packages/core/workshop/library.js';
import { LearningService } from '../packages/core/workshop/learning.js';
import { WorkshopOrchestrator } from '../packages/core/workshop/orchestrator.js';
import { WorkshopRuntime } from '../packages/core/workshop/runtime.js';
import { WorkshopUsageLedger } from '../packages/core/workshop/usage.js';
import type { EventContext } from '../packages/core/execution/durable.js';
import { SqliteJournal } from '../packages/storage/src/journal.js';

const selected={provider:'openai' as const,modelId:'gpt-6-astra',reasoningEffort:'low'};
const request=(id:string,overrides:Record<string,unknown>={})=>({schema:1,id,revision:1,comparisonSeries:`series-${id}`,objective:'Produce 60 electronic circuits per minute',source:{kind:'brief',id:null},profileId:'starter-assembly',construction:'direct',libraryAccess:false,improveRevision:null,requestedSpeed:{numerator:'10',denominator:'1'},settlingTicks:0,windowTicks:60,windows:1,rubric:{version:'rubric-1',weights:{throughput:{numerator:'1',denominator:'1'}},materiality:{throughput:{numerator:'0',denominator:'1'}},directions:{throughput:'maximize'}},iterations:{attempts:1,mode:'exact',earlyStop:false,plateauRounds:1},checkpoints:{brief:false,afterScore:false,libraryAdmission:false,learningActivation:false,timeoutMs:1000,timeoutAction:'finish'},budgets:{wallMs:60000,gameTicks:600,turns:3,toolCalls:8,reportedTokens:1000,learningReservedTurns:1,learningReservedTools:2},models:{sessionDefault:selected,overrides:{}},learning:{cadence:'off',batchSessions:2,candidateCap:2,attemptsPerCandidate:1,autoActivate:false},...overrides});
const installed={gameVersion:'2.0.77',mods:{base:'2.0.77'},profileId:'starter-assembly',profileRevision:1,surface:'nauvis',technologies:['automation'],allowedEquipment:['assembling-machine-1'],modules:[],beacons:[],recipe:{id:'electronic-circuit',category:'crafting',energy:0.5,ingredients:[{type:'item' as const,name:'iron-plate',amount:1}],products:[{type:'item' as const,name:'electronic-circuit',amount:1}]},machine:'assembling-machine-1'};
const document=(ports:BlueprintDocument['ports']):BlueprintDocument=>({schema:1,label:'Budgeted cell',description:'Acceptance candidate',entities:[{id:'assembler',entityNumber:1,name:'assembling-machine-1',position:{x:0,y:0},direction:0,quality:'normal',recipe:'electronic-circuit'}],wires:[],ports,icons:[{index:1,name:'electronic-circuit'}],tiles:[]});

function harness(inference:WorkshopInference,gameOverrides:Partial<WorkshopGame>={}){
  const root=mkdtempSync(path.join(os.tmpdir(),'af-live-host-')),journal=new SqliteJournal(path.join(root,'run.sqlite'));let clock=0;const context=():EventContext=>({run:'run',epoch:'epoch',wallTime:new Date(1_800_000_000_000+clock++).toISOString(),gameTick:null,actor:'operator',task:null,causation:null,correlation:null,visibility:{kind:'operator'}}),orchestrator=new WorkshopOrchestrator(journal,context),library=new BlueprintLibrary(path.join(root,'library')),learning=new LearningService(journal,context),usage=new WorkshopUsageLedger(journal,context),game:WorkshopGame={async resolveProfile(){return structuredClone(installed);},async build(session){return{id:`${session.id}-${session.activeIteration}`,generation:1,surface:'af-test',characterEvidence:null};},async measure(session):Promise<WorkshopEvaluationReport>{const rule=session.assignment.throughput[0]!,port=session.assignment.ports.find(value=>value.id===rule.portId)!;return{schema:1,attemptId:`${session.id}:${session.activeIteration}`,valid:true,passed:true,reasons:[],ports:[{portId:port.id,windows:[{index:0,required:{numerator:'1',denominator:'1'},productionLower:{numerator:'60',denominator:'1'},deliveryLower:{numerator:'60',denominator:'1'},passed:true,reasons:[]}]}],evidence:['fake-game']};},cancel(){return{acknowledged:true,failures:[]};},...gameOverrides},host=new LiveWorkshopHost(root,inference,game);host.bindServices({library,learning,usage,sessions:()=>journal.list('run','workshopSessions')});const runtime=new WorkshopRuntime(orchestrator,host,library,()=>[selected],id=>learning.pin(id).hash,()=>journal.list('run','workshopSessions'),()=>{});return{root,journal,orchestrator,library,learning,host,runtime,close:async()=>{await runtime.close();library.close();journal.close();rmSync(root,{recursive:true,force:true});}};
}

describe('production workshop host integration',()=>{
  it('enforces one durable aggregate budget across designer and scorer invocations',async()=>{let calls=0;const inference:WorkshopInference={async invoke(_session,role,_selection,observation){calls++;if(role==='workshop-designer'){const assignment=(observation as {assignment:{ports:BlueprintDocument['ports']}}).assignment;return{text:JSON.stringify(document(assignment.ports)),usage:{turns:1,tools:1,elapsedMs:5,tokens:10}};}return{text:JSON.stringify({feedback:'measured'}),usage:{turns:1,tools:1,elapsedMs:5,tokens:10}};},async close(){}};const h=harness(inference);try{const input=request('budget',{iterations:{attempts:2,mode:'exact',earlyStop:false,plateauRounds:1}});await h.runtime.launch(input);await h.runtime.pending('budget');expect(h.orchestrator.get('budget')).toMatchObject({stage:'stopped'});expect(h.orchestrator.get('budget').stopReason).toContain('aggregate provider budget exhausted');expect(calls).toBe(2);const state=JSON.parse(readFileSync(path.join(h.root,'workshop-live','budget','provider-budget.json'),'utf8'))as{workshop:{turns:number;tools:number};tokens:number};expect(state).toMatchObject({workshop:{turns:2,tools:2},tokens:20});expect(h.journal.list('run','usage')).toHaveLength(1);}finally{await h.close();}});

  it('persists trusted full assignments and supplies the exact compatible source revision to Improve',async()=>{const observations:unknown[]=[];const inference:WorkshopInference={async invoke(_session,role,_selection,observation){observations.push(observation);if(role==='workshop-designer'){const assignment=(observation as {assignment:{ports:BlueprintDocument['ports']}}).assignment;return{text:JSON.stringify(document(assignment.ports)),usage:{turns:1,tools:1,elapsedMs:5,tokens:10}};}return{text:JSON.stringify({feedback:'measured'}),usage:{turns:1,tools:1,elapsedMs:5,tokens:10}};},async close(){}};const h=harness(inference);try{const resolved=await h.host.resolve(request('resolved'));const full={...resolved,id:'full',comparisonSeries:'series-full'};await h.host.resolve(full);expect(JSON.parse(readFileSync(path.join(h.root,'workshop-live','full','resolved.json'),'utf8'))).toMatchObject({assignment:{id:'full'},installed:{gameVersion:'2.0.77'}});const first={...request('first'),libraryAccess:true};await h.runtime.launch(first);await h.runtime.pending('first');expect(h.orchestrator.get('first').stage).toBe('complete');const entry=h.library.search({product:'electronic-circuit'})[0]!;const improve={...request('improve'),source:{kind:'revision',id:entry.revisionHash},libraryAccess:true,improveRevision:entry.revisionHash};await h.runtime.launch(improve);await h.runtime.pending('improve');expect(h.orchestrator.get('improve').stage).toBe('complete');const source=(observations.find(value=>(value as {assignment?:{id?:string}}).assignment?.id==='improve') as {sourceRevision:{hash:string;document:BlueprintDocument}}).sourceRevision;expect(source.hash).toBe(entry.revisionHash);expect(source.document.label).toBe('Budgeted cell');expect(h.library.search({product:'electronic-circuit'})).toHaveLength(1);const incompatible={...request('rubric-collision'),source:{kind:'revision',id:entry.revisionHash},libraryAccess:true,improveRevision:entry.revisionHash,rubric:{version:'rubric-1',weights:{throughput:{numerator:'2',denominator:'1'}},materiality:{throughput:{numerator:'0',denominator:'1'}},directions:{throughput:'maximize'}}};await h.runtime.launch(incompatible);await h.runtime.pending('rubric-collision');expect(h.orchestrator.get('rubric-collision')).toMatchObject({stage:'stopped',stopReason:expect.stringContaining('rubric definition mismatch')});}finally{await h.close();}});

  it('cancels an active managed invocation before stopping the durable session',async()=>{let rejectInvocation:(error:Error)=>void=()=>{},started=false,cancelled=false;const inference:WorkshopInference={async invoke(){started=true;return new Promise((_resolve,reject)=>{rejectInvocation=reject;});},async cancel(){cancelled=true;rejectInvocation(new Error('cancelled by operator'));return{acknowledged:true,failures:[]};},async close(){}};const h=harness(inference);try{await h.runtime.launch(request('cancel'));await expect.poll(()=>started).toBe(true);await h.runtime.stop('cancel','operator_stop');await h.runtime.pending('cancel');expect(cancelled).toBe(true);expect(h.orchestrator.get('cancel')).toMatchObject({stage:'stopped',stopReason:'operator_stop'});}finally{await h.close();}});

  it.each([{name:'void',receipt:undefined,failure:'inference_cancellation:missing_receipt'},{name:'negative receipt without a reason',receipt:{acknowledged:false,failures:[]},failure:'inference_cancellation:unconfirmed_receipt'},{name:'malformed positive receipt',receipt:{acknowledged:true},failure:'inference_cancellation:malformed_receipt'},{name:'contradictory positive receipt',receipt:{acknowledged:true,failures:['adapter-reported-failure']},failure:'inference_cancellation:contradictory_receipt'}])('holds dispatched work for a $name cancellation result',async({name,receipt,failure})=>{let rejectInvocation:(error:Error)=>void=()=>{},started=false;const inference:WorkshopInference={async invoke(){started=true;return new Promise((_resolve,reject)=>{rejectInvocation=reject;});},async cancel(){rejectInvocation(new Error(`cancelled with ${name}`));return receipt as never;},async close(){}};const h=harness(inference);try{const id=`cancel-${name.replaceAll(' ','-')}`;await h.runtime.launch(request(id));await expect.poll(()=>started).toBe(true);const held=await h.runtime.stop(id,'operator_stop');await h.runtime.pending(id);expect(held).toMatchObject({stage:'held',stopReason:expect.stringContaining(failure)});expect(h.orchestrator.get(id).operationIntents[`${id}:1:design`]).toMatchObject({status:'unknown'});}finally{await h.close();}});

  it('fences cancellation while managed gateway setup is still pending',async()=>{const root=mkdtempSync(path.join(os.tmpdir(),'af-managed-setup-'));let release:()=>void=()=>{},closed=false,listening=false;const listener=async()=>new Promise<{url:string;close:()=>Promise<void>}>(resolve=>{listening=true;release=()=>resolve({url:'http://127.0.0.1:1',close:async()=>{closed=true;}});}),inference=new ManagedWorkshopInference('unused',root,[],()=>{},listener),id='setup-race',pending=inference.invoke({id} as never,'workshop-designer',selected,{},'prompt','instructions',{invocationId:`${id}:1:designer`,owner:'workshop',turns:1,tools:1,wallMs:1000,tokens:100});try{await expect.poll(()=>listening).toBe(true);expect(await inference.cancel(id)).toEqual({acknowledged:true,failures:[]});release();await expect(pending).rejects.toThrow('cancelled during setup');expect(closed).toBe(true);}finally{await inference.close();rmSync(root,{recursive:true,force:true});}});

  it('holds dispatched work when provider cancellation is not acknowledged',async()=>{let rejectInvocation:(error:Error)=>void=()=>{},started=false;const inference:WorkshopInference={async invoke(){started=true;return new Promise((_resolve,reject)=>{rejectInvocation=reject;});},async cancel(){rejectInvocation(new Error('provider remained uncertain'));throw new Error('interrupt rejected');},async close(){}};const h=harness(inference);try{await h.runtime.launch(request('cancel-failed'));await expect.poll(()=>started).toBe(true);const held=await h.runtime.stop('cancel-failed','operator_stop');await h.runtime.pending('cancel-failed');expect(held).toMatchObject({stage:'held',stopReason:expect.stringContaining('stop_cancellation_unconfirmed')});expect(h.orchestrator.get('cancel-failed').operationIntents['cancel-failed:1:design']).toMatchObject({status:'unknown'});}finally{await h.close();}});

  it('holds dispatched game work when the game adapter has no cancellation receipt',async()=>{let buildStarted=false,rejectBuild:(error:Error)=>void=()=>{};const inference:WorkshopInference={async invoke(_session,role,_selection,observation){if(role==='workshop-designer'){const assignment=(observation as {assignment:{ports:BlueprintDocument['ports']}}).assignment;return{text:JSON.stringify(document(assignment.ports)),usage:{turns:1,tools:1,elapsedMs:5,tokens:10}};}return{text:JSON.stringify({feedback:'unused'}),usage:{turns:1,tools:1,elapsedMs:5,tokens:10}};},async cancel(){return{acknowledged:true,failures:[]};},async close(){}};const h=harness(inference,{async build(){buildStarted=true;return new Promise((_resolve,reject)=>{rejectBuild=reject;});},async cancel(){rejectBuild(new Error('local game wait ended without a remote receipt'));return{acknowledged:false,failures:['game_cancellation:no_receipt']};}});try{await h.runtime.launch(request('game-cancel-failed'));await expect.poll(()=>buildStarted).toBe(true);const held=await h.runtime.stop('game-cancel-failed','operator_stop');await h.runtime.pending('game-cancel-failed');expect(held).toMatchObject({stage:'held',stopReason:expect.stringContaining('game_cancellation:no_receipt')});expect(h.orchestrator.get('game-cancel-failed').operationIntents['game-cancel-failed:1:build']).toMatchObject({status:'unknown'});}finally{await h.close();}});

  it('defers admitted learning failures without discarding completed blueprint work',async()=>{const inference:WorkshopInference={async invoke(_session,role,_selection,observation){if(role==='workshop-designer'){const assignment=(observation as {assignment:{ports:BlueprintDocument['ports']}}).assignment;return{text:JSON.stringify(document(assignment.ports)),usage:{turns:1,tools:1,elapsedMs:5,tokens:10}};}if(role==='workshop-scorer')return{text:JSON.stringify({feedback:'measured'}),usage:{turns:1,tools:1,elapsedMs:5,tokens:10}};throw new Error('malformed learning response after admission');},async close(){}};const h=harness(inference);try{await h.runtime.launch(request('learning-deferred',{learning:{cadence:'after-session',batchSessions:1,candidateCap:2,attemptsPerCandidate:1,autoActivate:false}}));await h.runtime.pending('learning-deferred');expect(h.orchestrator.get('learning-deferred').stage).toBe('complete');expect(h.learning.pin('future-session')).toMatchObject({generation:0,hash:'baseline'});expect(h.journal.get('run','learningOutcomes','learning-deferred-learning')).toMatchObject({decision:'defer',bundleHash:null,activatedGeneration:null,revisitCondition:'learning-inference-confirmed'});}finally{await h.close();}});

  it('reserves elapsed time and reported tokens for learning and consumes activated lessons and a confined helper',async()=>{const observations:unknown[]=[],limits:unknown[]=[];const inference:WorkshopInference={async invoke(_session,role,_selection,observation,_prompt,_instructions,assigned){observations.push(observation);limits.push(assigned);if(role==='workshop-designer'){const assignment=(observation as {assignment:{ports:BlueprintDocument['ports']}}).assignment;return{text:JSON.stringify(document(assignment.ports)),usage:{turns:1,tools:1,elapsedMs:100,tokens:100}};}if(role==='workshop-scorer')return{text:JSON.stringify({feedback:'measured'}),usage:{turns:1,tools:1,elapsedMs:100,tokens:100}};return{text:JSON.stringify({decision:'no-change',scope:'lesson',reason:'No repeated failure',evidence:['session-ok']}),usage:{turns:1,tools:1,elapsedMs:100,tokens:100}};},async close(){}};const h=harness(inference);try{const helper='input=>({revision:input.revision,actions:[{kind:"suggestion",payload:{text:"keep ports clear"}}]})',controls=['production-consumption'],bundle=h.learning.assemble({incumbentHash:'baseline',expectedGeneration:0,files:{'lessons.json':'[{"lesson":"keep ports visible"}]','design-helper.mjs':helper},requiredControls:controls,policyHash:'production-helper-v1',retrievalHash:'lessons-v1',catalogHash:'catalog-v1',candidates:[]});for(const kind of ['deterministic','interaction','behavior','review'] as const)h.learning.attest(bundle.hash,{kind,bundleHash:bundle.hash,incumbentHash:'baseline',generation:0,controlSuite:'production-v1',controls,environment:'test',passed:true,conclusive:true,evidence:[kind]});h.learning.activate(bundle.hash,'activate-production');await h.runtime.launch(request('learning-consumption',{learning:{cadence:'after-session',batchSessions:1,candidateCap:2,attemptsPerCandidate:1,autoActivate:false}}));await h.runtime.pending('learning-consumption');expect(h.orchestrator.get('learning-consumption').stage).toBe('complete');const design=observations[0] as {activatedLearning:ActivatedLearning};expect(design.activatedLearning).toMatchObject({bundleHash:bundle.hash,lessons:'[{"lesson":"keep ports visible"}]',helperPlan:{revision:1,actions:[{kind:'suggestion'}]}});expect(h.orchestrator.get('learning-consumption').iterations[0]?.artifact?.evidence).toContain(`activated-helper:${createHash('sha256').update(helper).digest('hex')}`);expect(limits).toMatchObject([{owner:'workshop',wallMs:40000,tokens:667},{owner:'workshop',wallMs:39900,tokens:567},{owner:'learning',wallMs:20000,tokens:333}]);const budget=JSON.parse(readFileSync(path.join(h.root,'workshop-live','learning-consumption','provider-budget.json'),'utf8'));expect(budget).toMatchObject({workshop:{elapsedMs:200,tokens:200,unknownTokens:false},learning:{elapsedMs:100,tokens:100,unknownTokens:false}});}finally{await h.close();}});
});

interface ActivatedLearning { bundleHash:string;lessons:string|null;helperPlan:{revision:number;actions:{kind:string}[]}|null }
