local C=require("common")
local M={}
function M.init() storage.af.workshops=storage.af.workshops or {} end
local function area(r) C.check(type(r)=="table" and #r==2,"invalid_workshop_area");C.pos(r[1]);C.pos(r[2]);C.check(r[1].x<r[2].x and r[1].y<r[2].y,"invalid_workshop_area");return r end
local function state(id) C.id(id);local w=storage.af.workshops[id];C.check(w,"unknown_workshop");return w end
local function in_area(p,a) return p.x>=a[1].x and p.x<=a[2].x and p.y>=a[1].y and p.y<=a[2].y end
local function ref(e) local ok,recipe=pcall(function()return e.get_recipe()end);return {name=e.name,quality=e.quality.name,position=e.position,direction=e.direction,unit=e.unit_number,recipe=ok and recipe and recipe.name or nil,undergroundType=e.type=="underground-belt" and e.belt_to_ground_type or nil} end
local function candidate_entities(w) local fixtures={};for _,fixture in pairs(w.fixtures) do fixtures[fixture.unit]=true end;local out={};for _,e in pairs(game.surfaces[w.surface].find_entities_filtered{area=w.area,force=w.force}) do if e.valid and e.unit_number and not fixtures[e.unit_number] then out[#out+1]=e end end;table.sort(out,function(a,b)return a.unit_number<b.unit_number end);return out end
local function fingerprint(w) local refs={};for _,e in ipairs(candidate_entities(w)) do refs[#refs+1]=ref(e) end;return helpers.table_to_json(refs) end
local function setup(r)
 C.keys(r,{"op","id","surface","force","profileFingerprint","technologies","recipes","allowedEquipment","surfaceProperties","area","maxTiles","fixtures"});C.id(r.id);C.id(r.surface);C.id(r.force);C.id(r.profileFingerprint);local a=area(r.area);C.integer(r.maxTiles,512*512,4096*4096);C.check((a[2].x-a[1].x)*(a[2].y-a[1].y)<=r.maxTiles,"workshop_area_cap")
 C.check(not storage.af.workshops[r.id],"workshop_exists");C.check(not game.surfaces[r.surface] and not game.forces[r.force],"workshop_identity_conflict")
 local surface=game.create_surface(r.surface,{width=0,height=0,water=0,autoplace_controls={trees={frequency=0,size=0,richness=0},["enemy-base"]={frequency=0,size=0,richness=0}},default_enable_all_autoplace_controls=false});surface.always_day=true;for name,value in pairs(r.surfaceProperties) do C.id(name);local ok=type(value)=="number" and pcall(function()surface.set_property(name,value)end);C.check(ok and surface.get_property(name)==value,"invalid_surface_property") end
 local center={x=(a[1].x+a[2].x)/2,y=(a[1].y+a[2].y)/2};local radius=math.ceil(math.max(a[2].x-a[1].x,a[2].y-a[1].y)/64);surface.request_to_generate_chunks(center,radius);surface.force_generate_chunk_requests()
 for _,e in pairs(surface.find_entities_filtered{area=a}) do if e.valid then e.destroy() end end
 local force=game.create_force(r.force);for _,technology in ipairs(r.technologies) do C.id(technology);C.check(force.technologies[technology],"unknown_workshop_technology");force.technologies[technology].researched=true end
 for _,recipe in ipairs(r.recipes) do C.id(recipe);C.check(force.recipes[recipe],"unknown_workshop_recipe");force.recipes[recipe].enabled=true end
 local allowed={};for _,name in ipairs(r.allowedEquipment) do C.id(name);C.check(prototypes.entity[name] or prototypes.item[name],"unknown_workshop_equipment");allowed[name]=true end
 local w={id=r.id,surface=r.surface,force=r.force,profileFingerprint=r.profileFingerprint,area=a,maxTiles=r.maxTiles,allowed=allowed,units={},fixtures={},generation=1}
 storage.af.workshops[r.id]=w
 for _,fixture in ipairs(r.fixtures) do C.keys(fixture,{"id","kind","position","product","rate"});C.id(fixture.id);C.pos(fixture.position);C.check(in_area(fixture.position,a),"fixture_outside_workshop");C.check(fixture.kind=="source" or fixture.kind=="sink" or fixture.kind=="power","invalid_fixture");C.check(type(fixture.rate)=="number" and fixture.rate>=0,"invalid_fixture_rate");C.keys(fixture.product,{"kind","name","quality"});C.check(fixture.product.quality=="normal","unsupported_fixture_quality");C.id(fixture.product.name)
  local name=fixture.kind=="power" and "electric-energy-interface" or (fixture.product.kind=="fluid" and "storage-tank" or "steel-chest");local e=surface.create_entity{name=name,position=fixture.position,force=force};C.check(e,"fixture_creation_failed");if fixture.kind=="power" then e.power_production=1000000000;e.electric_buffer_size=1000000000 end;storage.af.protected[e.unit_number]=true;w.fixtures[fixture.id]={unit=e.unit_number,entity=e.name,position={x=e.position.x,y=e.position.y},kind=fixture.kind,product=fixture.product,rate=fixture.rate,accumulator=0,delivered=0}
 end
 return {ok=true,id=w.id,surface=w.surface,force=w.force,area=w.area,maxTiles=w.maxTiles,generation=w.generation,fixtures=w.fixtures}
end
local function expand(r)
 C.keys(r,{"op","id","generation","area"});local w=state(r.id);C.check(not w.measurement or w.measurement.finished,"workshop_measurement_active");C.integer(r.generation,1,2147483647);C.check(r.generation==w.generation,"stale_workshop_generation");local a=area(r.area);C.check(a[1].x<=w.area[1].x and a[1].y<=w.area[1].y and a[2].x>=w.area[2].x and a[2].y>=w.area[2].y,"workshop_expansion_must_contain_existing");C.check((a[2].x-a[1].x)*(a[2].y-a[1].y)<=w.maxTiles,"workshop_area_cap");local before=fingerprint(w);local surface=game.surfaces[w.surface];local center={x=(a[1].x+a[2].x)/2,y=(a[1].y+a[2].y)/2};local radius=math.ceil(math.max(a[2].x-a[1].x,a[2].y-a[1].y)/64);surface.request_to_generate_chunks(center,radius);surface.force_generate_chunk_requests();w.area=a;w.generation=w.generation+1;C.check(before==fingerprint(w),"workshop_expansion_changed_candidate");return {ok=true,area=w.area,generation=w.generation,candidateFingerprint=before}
end
local function materialize(r)
 C.keys(r,{"op","id","generation","operationId","entities","wires"});local w=state(r.id);C.check(not w.measurement or w.measurement.finished,"workshop_measurement_active");C.integer(r.generation,1,2147483647);C.check(r.generation==w.generation,"stale_workshop_generation");C.id(r.operationId);w.operations=w.operations or {};if w.operations[r.operationId] then return w.operations[r.operationId] end
 local surface=game.surfaces[w.surface];local force=game.forces[w.force];local created={};local baseUnits=#w.units
 local ok,failure=pcall(function()
  for _,value in ipairs(r.entities) do C.keys(value,{"id","name","position","direction","quality","recipe","modules","filters","inventoryBar","undergroundType","settings"});C.id(value.id);C.id(value.name);C.pos(value.position);C.integer(value.direction,0,15);C.check(value.quality=="normal","unsupported_quality_placement");C.check(w.allowed[value.name],"profile_denied");C.check(in_area(value.position,w.area),"direct_outside_workshop");C.check(not created[value.id],"duplicate_blueprint_entity");C.check(surface.can_place_entity{name=value.name,position=value.position,direction=value.direction,force=force,build_check_type=defines.build_check_type.script},"direct_collision")
   local parameters={name=value.name,position=value.position,direction=value.direction,force=force,quality="normal",raise_built=false};if value.undergroundType then C.check(value.undergroundType=="input" or value.undergroundType=="output","invalid_underground_type");C.check(prototypes.entity[value.name].type=="underground-belt","underground_type_unsupported");parameters.type=value.undergroundType end
   local e=surface.create_entity(parameters);C.check(e,"direct_creation_failed");created[value.id]=e;w.units[#w.units+1]=e.unit_number
   if value.recipe then C.check(e.set_recipe and force.recipes[value.recipe] and force.recipes[value.recipe].enabled,"direct_recipe_unavailable");e.set_recipe(value.recipe,"normal") end;if value.undergroundType then C.check(e.belt_to_ground_type==value.undergroundType,"underground_type_failed") end
   if next(value.modules) then local inv=e.get_module_inventory();C.check(inv,"direct_modules_unsupported");for name,count in pairs(value.modules) do C.id(name);C.integer(count,1,100);C.check(inv.insert{name=name,quality="normal",count=count}==count,"direct_module_failed") end end
   for _,filter in ipairs(value.filters) do C.integer(filter.index,1,100);C.id(filter.name);C.check(e.filter_slot_count>=filter.index,"direct_filter_unsupported");e.set_filter(filter.index,{name=filter.name,quality="normal"}) end
   if value.inventoryBar then local inv=e.get_inventory(defines.inventory.chest);C.check(inv and inv.supports_bar(),"direct_bar_unsupported");inv.set_bar(value.inventoryBar) end
   for key,setting in pairs(value.settings) do
    C.check(key=="active" or key=="inserter_filter_mode" or key=="splitter_input_priority" or key=="splitter_output_priority","direct_setting_unsupported")
    local set=pcall(function()e[key]=setting end);C.check(set and e[key]==setting,"direct_setting_failed")
   end
  end
  for _,wire in ipairs(r.wires) do C.keys(wire,{"from","to"});C.keys(wire.from,{"entityId","connector"});C.keys(wire.to,{"entityId","connector"});local a=created[wire.from.entityId];local b=created[wire.to.entityId];C.check(a and b,"direct_wire_entity_missing");local ac=a.get_wire_connector(wire.from.connector,true);local bc=b.get_wire_connector(wire.to.connector,true);C.check(ac and bc and ac.can_wire_reach(bc) and (ac.is_connected_to(bc) or ac.connect_to(bc,true,defines.wire_origin.script)),"direct_wire_failed") end
 end)
 if not ok then for _,e in pairs(created) do if e.valid then e.destroy() end end;for index=#w.units,baseUnits+1,-1 do w.units[index]=nil end;error(failure,0) end
 local receipt={ok=true,operationId=r.operationId,generation=w.generation,entities={}};for id,e in pairs(created) do receipt.entities[id]=ref(e) end;w.operations[r.operationId]=receipt;return receipt
end
local function inspect(r) C.keys(r,{"op","id"});local w=state(r.id);local out={};for _,e in ipairs(candidate_entities(w)) do out[#out+1]=ref(e) end;return {ok=true,id=w.id,generation=w.generation,area=w.area,profileFingerprint=w.profileFingerprint,entities=out,fixtures=w.fixtures,candidateFingerprint=fingerprint(w)} end
local function installed_profile(r)
 C.keys(r,{"op","profileId","product"});C.id(r.profileId);C.id(r.product);C.check(r.profileId=="starter-assembly" or r.profileId=="advanced-assembly" or r.profileId=="electromagnetic-production","unknown_workshop_profile")
 local recipe=prototypes.recipe[r.product];C.check(recipe,"unknown_workshop_product_recipe");local machines=r.profileId=="starter-assembly" and {"assembling-machine-1","stone-furnace"} or r.profileId=="advanced-assembly" and {"assembling-machine-2","electric-furnace","chemical-plant"} or {"electromagnetic-plant","foundry","assembling-machine-3","chemical-plant"};local machine=nil
 for _,name in ipairs(machines) do local prototype=prototypes.entity[name];if prototype and prototype.crafting_categories and prototype.crafting_categories[recipe.category] then machine=name;break end end;C.check(machine,"profile_has_no_compatible_machine")
 local common={"transport-belt","underground-belt","splitter","inserter","fast-inserter","long-handed-inserter","wooden-chest","steel-chest","small-electric-pole","medium-electric-pole","pipe","pipe-to-ground","pump","beacon"};local allowed={machine};for _,name in ipairs(common) do if prototypes.entity[name] then allowed[#allowed+1]=name end end
 local technologies={};local requested=r.profileId=="starter-assembly" and {"automation","logistics"} or r.profileId=="advanced-assembly" and {"automation","automation-2","logistics","logistics-2","modules","speed-module"} or {"automation","modules","electromagnetic-plant","electromagnetic-science-pack"};for _,name in ipairs(requested) do if prototypes.technology[name] then technologies[#technologies+1]=name end end
 local function products(values)local out={};for _,value in pairs(values) do if value.name and value.amount and (not value.probability or value.probability==1) then out[#out+1]={type=value.type,name=value.name,amount=value.amount,temperature=value.temperature} end end;table.sort(out,function(a,b)return a.type..":"..a.name<b.type..":"..b.name end);return out end
 local mods={};for name,version in pairs(script.active_mods) do mods[name]=version end
 return {ok=true,gameVersion=script.active_mods.base,mods=mods,profileId=r.profileId,profileRevision=1,surface="nauvis",technologies=technologies,allowedEquipment=allowed,modules={},beacons=prototypes.entity.beacon and {"beacon"} or {},recipe={id=recipe.name,category=recipe.category,energy=recipe.energy,ingredients=products(recipe.ingredients),products=products(recipe.products)},machine=machine}
end
local function provision(r)
 C.keys(r,{"op","id","actor","operationId","items"});local w=state(r.id);C.check(not w.measurement or w.measurement.finished,"workshop_measurement_active");C.id(r.operationId);w.provisions=w.provisions or {};if w.provisions[r.operationId] then return w.provisions[r.operationId] end;local p=C.actor(r.actor);C.check(p.surface.name==w.surface and p.force.name==w.force,"actor_not_in_workshop");local inventory=p.get_main_inventory();C.check(inventory and inventory.valid,"actor_inventory_unavailable");local before=C.inventory(inventory);local seen={};for _,item in ipairs(r.items) do C.keys(item,{"name","quality","count"});C.id(item.name);C.check(item.quality=="normal" and w.allowed[item.name],"provision_profile_denied");C.integer(item.count,1,10000);C.check(not seen[item.name],"duplicate_provision_item");seen[item.name]=true end
 local inserted={};for _,item in ipairs(r.items) do local count=inventory.insert(item);inserted[#inserted+1]={name=item.name,quality=item.quality,count=count};if count~=item.count then for index=#inserted,1,-1 do local value=inserted[index];if value.count>0 then inventory.remove(value) end end;error("provision_inventory_full",0) end end;local receipt={ok=true,operationId=r.operationId,before=before,after=C.inventory(inventory),tick=game.tick};w.provisions[r.operationId]=receipt;return receipt
end
local function enter(r) C.keys(r,{"op","id","actor"});local w=state(r.id);local p=C.actor(r.actor);local surface=game.surfaces[w.surface];local position=surface.find_non_colliding_position("character",{0,0},64,1);C.check(position and p.teleport(position,surface),"workshop_actor_teleport_failed");p.force=game.forces[w.force];return {ok=true,id=w.id,actor=r.actor,surface=w.surface,force=w.force,position=p.position} end
local function actor_state(r) C.keys(r,{"op","id","actor"});local w=state(r.id);local p=C.actor(r.actor);C.check(p.surface.name==w.surface and p.force.name==w.force,"actor_not_in_workshop");return {ok=true,id=w.id,actor=r.actor,surface=w.surface,force=w.force,position=p.position,inventory=C.inventory(p.get_main_inventory())} end
local function production(w)
 local totals={};local stock={};local complete=true;local energy=true
 for _,e in ipairs(candidate_entities(w)) do
  if e.type=="assembling-machine" or e.type=="furnace" then local ok,recipe=pcall(function()return e.get_recipe()end);if not ok or not recipe then complete=false else for _,product in pairs(recipe.products) do if product.amount and (not product.probability or product.probability==1) then totals[product.type..":"..product.name]=(totals[product.type..":"..product.name] or 0)+e.products_finished*product.amount else complete=false end end end;if e.energy==0 then energy=false end
  end
  for _,inventory in pairs(C.inventory_ids) do local ok,inv=pcall(function()return e.get_inventory(inventory)end);if ok and inv then for _,item in pairs(inv.get_contents()) do local key="item:"..item.name;stock[key]=(stock[key] or 0)+item.count end end end
  local ok,boxes=pcall(function()return #e.fluidbox end);if ok then for i=1,boxes do local fluid=e.fluidbox[i];if fluid then local key="fluid:"..fluid.name;stock[key]=(stock[key] or 0)+fluid.amount end end end
 end
 return {production=totals,stock=stock,stageCoverage=complete and "complete" or "partial",energyCoverage=energy and "complete" or "partial"}
end
local function snapshot(w) local snap=production(w);snap.delivery={};for id,fixture in pairs(w.fixtures) do snap.delivery[id]=fixture.delivered end;snap.tick=game.tick;return snap end
local function measurement_configure(r)
 C.keys(r,{"op","id","generation","attemptId","settlingTicks","windowTicks","windows","requestedSpeed","ports"});local w=state(r.id);C.integer(r.generation,1,2147483647);C.check(r.generation==w.generation,"stale_workshop_generation");C.id(r.attemptId);C.integer(r.settlingTicks,0,216000);C.integer(r.windowTicks,1,216000);C.integer(r.windows,1,100);C.check(type(r.requestedSpeed)=="number" and r.requestedSpeed>=0.1 and r.requestedSpeed<=100,"invalid_workshop_speed");local seen={};for _,port in ipairs(r.ports) do C.keys(port,{"id","fixtureId","product"});C.id(port.id);C.id(port.fixtureId);C.check(not seen[port.id] and w.fixtures[port.fixtureId] and w.fixtures[port.fixtureId].kind=="sink","invalid_measurement_port");seen[port.id]=true;C.keys(port.product,{"kind","name","quality"});C.check(port.product.quality=="normal","unsupported_measurement_quality") end
 if w.measurement then C.check(w.measurement.attemptId==r.attemptId,"workshop_measurement_collision");return {ok=true,attemptId=r.attemptId,admittedTick=w.measurement.admitted,requestedSpeed=w.measurement.requestedSpeed,achievedSpeed=game.speed,reconciled=true} end
 w.measurement={attemptId=r.attemptId,settlingTicks=r.settlingTicks,windowTicks=r.windowTicks,windows=r.windows,requestedSpeed=r.requestedSpeed,previousSpeed=game.speed,previousPaused=game.tick_paused,ports=r.ports,state="settling",admitted=game.tick,nextTick=game.tick+r.settlingTicks,samples={},sequence=0,baseline=snapshot(w),finished=false};game.speed=r.requestedSpeed;game.tick_paused=false;return {ok=true,attemptId=r.attemptId,admittedTick=game.tick,requestedSpeed=r.requestedSpeed,achievedSpeed=game.speed}
end
local function complete_window(w,m,current)
 local remaining={};for key,total in pairs(current.production) do remaining[key]=total-(m.baseline.production[key] or 0) end;local ports={};table.sort(m.ports,function(a,b)return a.id<b.id end)
 for _,port in ipairs(m.ports) do local key=port.product.kind..":"..port.product.name;local delivery=current.delivery[port.fixtureId]-(m.baseline.delivery[port.fixtureId] or 0);local opening=m.baseline.stock[key] or 0;local closing=current.stock[key] or 0;local balanced=math.max(0,delivery+(closing-opening));local produced=math.min(remaining[key] or 0,balanced);remaining[key]=math.max(0,(remaining[key] or 0)-produced);ports[#ports+1]={portId=port.id,product={kind=port.product.kind,name=port.product.name,quality="normal",surface=w.surface},production={numerator=tostring(produced),denominator="1"},delivery={numerator=tostring(delivery),denominator="1"},openingStock={numerator=tostring(opening),denominator="1"},closingStock={numerator=tostring(closing),denominator="1"},residual={numerator=tostring(produced-delivery-(closing-opening)),denominator="1"},productionAllocationId=key..":"..m.sequence..":"..port.id,coverage="complete",evidence={"workshop-lua:"..m.attemptId..":"..m.sequence..":"..port.id}} end
 m.samples[#m.samples+1]={schema=1,attemptId=m.attemptId,index=m.sequence,startTick=m.baseline.tick,endTick=current.tick,interval="(startTick,endTick]",ports=ports,stageCoverage=current.stageCoverage,energyCoverage=current.energyCoverage,contamination={},mutationsFrozen=true,connected=true,evidence={"workshop-lua:"..m.attemptId..":"..m.sequence}};m.sequence=m.sequence+1;m.baseline=current
end
local function measurement_read(r) C.keys(r,{"op","id","attemptId","after"});local w=state(r.id);local m=w.measurement;C.check(m and m.attemptId==r.attemptId,"unknown_workshop_measurement");C.integer(r.after,-1,1000);local samples={};for _,sample in ipairs(m.samples) do if sample.index>r.after then samples[#samples+1]=sample end end;return {ok=true,tick=game.tick,state=m.state,finished=m.finished,samples=samples,requestedSpeed=m.requestedSpeed,achievedSpeed=game.speed} end
local function measurement_status(r) C.keys(r,{"op","id","attemptId"});local w=(storage.af.workshops or {})[r.id];local m=w and w.measurement;if not m then return {ok=true,attemptId=r.attemptId,present=false,state="not-admitted",finished=true} end;if m.attemptId~=r.attemptId then return {ok=true,attemptId=r.attemptId,present=false,state="identity-conflict",finished=false} end;return {ok=true,attemptId=m.attemptId,present=true,state=m.state,finished=m.finished} end
local function measurement_abort(r) C.keys(r,{"op","id","attemptId"});local w=state(r.id);local m=w.measurement;C.check(m and m.attemptId==r.attemptId,"unknown_workshop_measurement");if not m.finished then m.finished=true;m.state="aborted";m.error="host_aborted";game.speed=m.previousSpeed;game.tick_paused=m.previousPaused end;return {ok=true,attemptId=m.attemptId,state=m.state,finished=m.finished,restoredSpeed=game.speed,restoredPaused=game.tick_paused} end
function M.guard() for _,w in pairs(storage.af.workshops or {}) do if w.measurement and not w.measurement.finished then error("workshop_measurement_observation_only",0) end end end
function M.tick()
 for _,w in pairs(storage.af.workshops or {}) do
  for _,fixture in pairs(w.fixtures) do local e=game.surfaces[w.surface].find_entity(fixture.entity,fixture.position);if e and e.valid and fixture.kind~="power" then local amount=0;if fixture.product.kind=="item" then local inv=e.get_inventory(defines.inventory.chest);if fixture.kind=="source" then fixture.accumulator=fixture.accumulator+fixture.rate/60;amount=math.floor(fixture.accumulator);if amount>0 then amount=inv.insert{name=fixture.product.name,quality="normal",count=amount};fixture.accumulator=fixture.accumulator-amount end else amount=inv.get_item_count();if amount>0 then amount=inv.remove{name=fixture.product.name,quality="normal",count=amount};fixture.delivered=fixture.delivered+amount end end else local fluid=e.fluidbox[1];if fixture.kind=="source" then fixture.accumulator=fixture.accumulator+fixture.rate/60;amount=fixture.accumulator;if amount>=0.01 then e.fluidbox[1]={name=fixture.product.name,amount=(fluid and fluid.amount or 0)+amount,temperature=fluid and fluid.temperature or 15};fixture.accumulator=0 end elseif fluid and fluid.name==fixture.product.name then amount=fluid.amount;e.fluidbox[1]=nil;fixture.delivered=fixture.delivered+amount end end end end
  local m=w.measurement;if m and not m.finished then if game.tick==m.nextTick then local current=snapshot(w);if m.state=="settling" then m.state="scoring";m.baseline=current;m.nextTick=game.tick+m.windowTicks else complete_window(w,m,current);if m.sequence>=m.windows then m.finished=true;m.state="finished";game.speed=m.previousSpeed;game.tick_paused=m.previousPaused else m.nextTick=game.tick+m.windowTicks end end elseif game.tick>m.nextTick then m.finished=true;m.state="invalid";m.error="missed_exact_tick";game.speed=m.previousSpeed;game.tick_paused=m.previousPaused end end
 end
end
function M.rpc(r)
 M.init();if r.op=="workshop-profile" then return installed_profile(r) elseif r.op=="workshop-setup" then return setup(r) elseif r.op=="workshop-expand" then return expand(r) elseif r.op=="workshop-materialize" then return materialize(r) elseif r.op=="workshop-inspect" then return inspect(r) elseif r.op=="workshop-enter" then return enter(r) elseif r.op=="workshop-actor" then return actor_state(r) elseif r.op=="workshop-provision" then return provision(r) elseif r.op=="workshop-measure-configure" then return measurement_configure(r) elseif r.op=="workshop-measure-status" then return measurement_status(r) elseif r.op=="workshop-measure-abort" then return measurement_abort(r) elseif r.op=="workshop-measure-read" then return measurement_read(r) end;error("unsupported_workshop_operation",0)
end
return M
