import { useEffect, useMemo, useState } from 'react';
import type { DashboardSnapshot } from '../../runtime/dashboard-types.js';

type Api=(route:string,body?:unknown)=>Promise<unknown>;
type Selection={provider:'openai';modelId:string;reasoningEffort:string};
interface ModelOption{id:string;displayName:string|null;efforts:string[]}
interface Preset{id:string;assignment:Record<string,unknown>}
interface Options{provider:string;models:ModelOption[];profiles:string[];presets:Preset[];defaults:Record<string,unknown>}
interface LoadedAssignment{objective:string;profileId:string;construction:'direct'|'character';libraryAccess:boolean;iterations:{attempts:number;earlyStop:boolean};checkpoints:{brief:boolean;afterScore:boolean;libraryAdmission:boolean;learningActivation:boolean};requestedSpeed:{numerator:string;denominator:string};settlingTicks:number;throughput:{windowTicks:number;windows:number}[];budgets:{wallMs:number;turns:number;toolCalls:number;learningReservedTurns:number};learning:{cadence:string;batchSessions:number;candidateCap:number;attemptsPerCandidate:number;autoActivate:boolean};models:{sessionDefault:Selection;overrides:Partial<Record<'designer'|'scorer'|'learnings',Selection>>}}
const rational=(value:string)=>{const normalized=/^\d+(?:\.\d+)?$/.test(value)?value:'0';const[whole,fraction='']=normalized.split('.');return{numerator:String(BigInt(whole+fraction)),denominator:String(10n**BigInt(fraction.length))};};
const selection=(modelId:string,reasoningEffort:string):Selection=>({provider:'openai',modelId,reasoningEffort});
const numeric=(value:string,min:number,max:number,fallback:number)=>{const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback;};

export function WorkshopPanel({api,data,inspect}:{api:Api;data:DashboardSnapshot|undefined;inspect:(v:unknown)=>void}){
  const[options,setOptions]=useState<Options>();const[objective,setObjective]=useState('Produce 60 electronic circuits per minute');const[profile,setProfile]=useState('starter-assembly');const[construction,setConstruction]=useState<'direct'|'character'>('direct');const[libraryAccess,setLibraryAccess]=useState(true);const[attempts,setAttempts]=useState(5);const[earlyStop,setEarlyStop]=useState(true);const[checkpoints,setCheckpoints]=useState({brief:false,afterScore:false,libraryAdmission:false,learningActivation:false});
  const[model,setModel]=useState('');const[effort,setEffort]=useState('');const[designerModel,setDesignerModel]=useState('');const[designerEffort,setDesignerEffort]=useState('');const[scorerModel,setScorerModel]=useState('');const[scorerEffort,setScorerEffort]=useState('');const[learningsModel,setLearningsModel]=useState('');const[learningsEffort,setLearningsEffort]=useState('');
  const[speed,setSpeed]=useState('10');const[settling,setSettling]=useState(600);const[windowTicks,setWindowTicks]=useState(3600);const[windows,setWindows]=useState(5);const[wallMinutes,setWallMinutes]=useState(60);const[turns,setTurns]=useState(30);const[toolCalls,setToolCalls]=useState(200);const[learningCadence,setLearningCadence]=useState('after-session');const[learningBatch,setLearningBatch]=useState(5);const[learningCandidates,setLearningCandidates]=useState(3);const[learningAttempts,setLearningAttempts]=useState(2);const[learningTurns,setLearningTurns]=useState(3);const[autoActivate,setAutoActivate]=useState(true);
  const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[query,setQuery]=useState('');const[library,setLibrary]=useState<Record<string,unknown>[]>([]);const[presetName,setPresetName]=useState('');
  useEffect(()=>{if(!data)return;void api('workshop/options').then(raw=>{const value=raw as Options;setOptions(value);const preferred=value.models.find(v=>v.displayName==='Astra'&&v.efforts.includes('low'))??value.models[0];if(preferred){setModel(preferred.id);setEffort(preferred.efforts.includes('low')?'low':preferred.efforts[0]??'');}}).catch(e=>setError(String(e)));},[data?.run]);
  const modelOption=(id:string)=>options?.models.find(v=>v.id===id);const inherited=(id:string,base:string)=>id||base;const inheritedEffort=(id:string,value:string,base:string)=>id?value:base;
  const makeRequest=(id:string,improveRevision:string|null=null)=>{const session=selection(model,effort);const overrides:Record<string,Selection>={};if(designerModel)overrides.designer=selection(designerModel,designerEffort);if(scorerModel)overrides.scorer=selection(scorerModel,scorerEffort);if(learningsModel)overrides.learnings=selection(learningsModel,learningsEffort);return{schema:1,id,revision:1,comparisonSeries:crypto.randomUUID(),objective,source:{kind:improveRevision?'revision':'brief',id:improveRevision},profileId:profile,construction,libraryAccess:improveRevision?true:libraryAccess,improveRevision,requestedSpeed:rational(speed),settlingTicks:settling,windowTicks,windows,rubric:{version:'rubric-1',weights:{throughput:rational('1')},materiality:{throughput:{numerator:'1',denominator:'100'}},directions:{throughput:'maximize'}},iterations:{attempts,mode:earlyStop?'maximum':'exact',earlyStop,plateauRounds:2},checkpoints:{...checkpoints,timeoutMs:600000,timeoutAction:'finish'},budgets:{wallMs:wallMinutes*60000,gameTicks:settling+windowTicks*windows,turns,toolCalls,reportedTokens:null,learningReservedTurns:learningTurns,learningReservedTools:12},models:{sessionDefault:session,overrides},learning:{cadence:learningCadence,batchSessions:learningBatch,candidateCap:learningCandidates,attemptsPerCandidate:learningAttempts,autoActivate}};};
  async function launch(improveRevision:string|null=null){setBusy(true);setError('');try{const id=crypto.randomUUID();inspect(await api('workshop/launch',{assignment:makeRequest(id,improveRevision)}));}catch(e){setError(String(e));}finally{setBusy(false);}}
  async function savePreset(){setError('');try{if(!presetName.trim())throw new Error('Preset name is required');const id=presetName.trim().toLowerCase().replace(/[^a-z0-9.-]+/g,'-');inspect(await api('workshop/preset',{id,assignment:{...makeRequest(id),source:{kind:'preset',id}}}));setOptions(await api('workshop/options') as Options);}catch(e){setError(String(e));}}
  function loadPreset(id:string){const preset=options?.presets.find(v=>v.id===id);if(!preset)return;const a=preset.assignment as unknown as LoadedAssignment;setObjective(String(a.objective));setProfile(String(a.profileId));setConstruction(a.construction);setLibraryAccess(Boolean(a.libraryAccess));setAttempts(Number(a.iterations.attempts));setEarlyStop(Boolean(a.iterations.earlyStop));setCheckpoints(a.checkpoints);setSpeed(String(Number(a.requestedSpeed.numerator)/Number(a.requestedSpeed.denominator)));setSettling(Number(a.settlingTicks));setWindowTicks(Number(a.throughput[0]!.windowTicks));setWindows(Number(a.throughput[0]!.windows));setWallMinutes(Number(a.budgets.wallMs)/60000);setTurns(Number(a.budgets.turns));setToolCalls(Number(a.budgets.toolCalls));setLearningTurns(Number(a.budgets.learningReservedTurns));setLearningCadence(a.learning.cadence);setLearningBatch(Number(a.learning.batchSessions));setLearningCandidates(Number(a.learning.candidateCap));setLearningAttempts(Number(a.learning.attemptsPerCandidate));setAutoActivate(Boolean(a.learning.autoActivate));setModel(a.models.sessionDefault.modelId);setEffort(a.models.sessionDefault.reasoningEffort);for(const[role,setM,setE]of [['designer',setDesignerModel,setDesignerEffort],['scorer',setScorerModel,setScorerEffort],['learnings',setLearningsModel,setLearningsEffort]] as const){const s=a.models.overrides[role];setM(s?.modelId??'');setE(s?.reasoningEffort??'');}}
  async function search(){try{const value=await api('workshop/library?q='+encodeURIComponent(query)) as {items:Record<string,unknown>[]};setLibrary(value.items);}catch(e){setError(String(e));}}
  async function exportRevision(hash:string){try{inspect(await api(`workshop/library/${encodeURIComponent(hash)}/export`));}catch(e){setError(String(e));}}
  async function learningControl(action:'rollback'|'quarantine',hash:string){try{inspect(await api('workshop/learning',action==='rollback'?{action,hash,operationId:crypto.randomUUID()}:{action,hash,reason:'Operator quarantine'}));}catch(e){setError(String(e));}}
  async function checkpoint(session:Record<string,unknown>,action:'continue'|'finish'){try{inspect(await api('workshop/checkpoint',{sessionId:session.id,revision:Number(session.steeringRevision)+1,action,text:action==='continue'?'Operator approved checkpoint':'Operator ended session at checkpoint'}));}catch(e){setError(String(e));}}
  const sessions=data?.projections.workshopSessions??[],iterations=data?.projections.workshopIterations??[],candidates=data?.projections.learningCandidates??[],outcomes=data?.projections.learningOutcomes??[],bundles=data?.projections.learningBundles??[],activations=data?.projections.activations??[];const active=activations[0] as Record<string,unknown>|undefined;
  const effective=useMemo(()=>({designer:`${inherited(designerModel,model)}/${inheritedEffort(designerModel,designerEffort,effort)}`,scorer:`${inherited(scorerModel,model)}/${inheritedEffort(scorerModel,scorerEffort,effort)}`,learnings:`${inherited(learningsModel,model)}/${inheritedEffort(learningsModel,learningsEffort,effort)}`}),[designerModel,designerEffort,scorerModel,scorerEffort,learningsModel,learningsEffort,model,effort]);
  const roleSelector=(label:string,id:string,setId:(v:string)=>void,valueEffort:string,setValueEffort:(v:string)=>void)=>{const aria=label.replace(' override','');return <><label>{label}<select aria-label={`${aria} model`} value={id} onChange={e=>{const next=e.target.value;setId(next);setValueEffort(next?(modelOption(next)?.efforts[0]??''):'' );}}><option value="">Inherit session default</option>{options?.models.map(v=><option key={v.id} value={v.id}>{v.displayName??v.id}</option>)}</select></label><label>{label} effort<select aria-label={`${aria} effort`} value={id?valueEffort:effort} disabled={!id} onChange={e=>setValueEffort(e.target.value)}>{(id?modelOption(id):modelOption(model))?.efforts.map(v=><option key={v}>{v}</option>)}</select></label></>;};
  return <section className="panel workshop" data-testid="workshop"><div className="sectiontitle"><div><p className="eyebrow">BLUEPRINT WORKSHOP</p><h2>Design, prove, preserve.</h2></div><span>{sessions.length} sessions</span></div>{error&&<p className="alert" role="alert">{error}</p>}
    <div className="workshop-grid"><form onSubmit={e=>{e.preventDefault();void launch();}}><h3>Launch / Improve</h3><label>Brief<textarea value={objective} onChange={e=>setObjective(e.target.value)}/></label><label>Capability profile<select value={profile} onChange={e=>setProfile(e.target.value)}>{options?.profiles.map(v=><option key={v}>{v}</option>)}</select></label><label>Construction<select value={construction} onChange={e=>setConstruction(e.target.value as 'direct'|'character')}><option value="direct">Direct workshop</option><option value="character">Legal character</option></select></label><label><input type="checkbox" checked={libraryAccess} onChange={e=>setLibraryAccess(e.target.checked)}/> Allow library access</label><div className="inline"><label>Attempts<input type="number" min="1" max="100" value={attempts} onChange={e=>setAttempts(numeric(e.target.value,1,100,5))}/></label><label><input type="checkbox" checked={earlyStop} onChange={e=>setEarlyStop(e.target.checked)}/> Early stop (maximum)</label></div>
      <label>Session model<select aria-label="Session model" value={model} onChange={e=>{setModel(e.target.value);setEffort(modelOption(e.target.value)?.efforts[0]??'');}}><option value="">Select managed model</option>{options?.models.map(v=><option key={v.id} value={v.id}>{v.displayName??v.id}</option>)}</select></label><label>Session effort<select aria-label="Session effort" value={effort} onChange={e=>setEffort(e.target.value)}>{modelOption(model)?.efforts.map(v=><option key={v}>{v}</option>)}</select></label>{roleSelector('Designer override',designerModel,setDesignerModel,designerEffort,setDesignerEffort)}{roleSelector('Scorer override',scorerModel,setScorerModel,scorerEffort,setScorerEffort)}{roleSelector('Learnings override',learningsModel,setLearningsModel,learningsEffort,setLearningsEffort)}<p className="hint" data-testid="effective-selections">Effective: designer {effective.designer}; scorer {effective.scorer}; learnings {effective.learnings}</p>
      <fieldset><legend>Evaluation manifest</legend><div className="inline"><label>Speed<input aria-label="Evaluation speed" value={speed} onChange={e=>setSpeed(e.target.value)}/></label><label>Settling ticks<input type="number" value={settling} onChange={e=>setSettling(numeric(e.target.value,0,3600000,600))}/></label><label>Window ticks<input type="number" value={windowTicks} onChange={e=>setWindowTicks(numeric(e.target.value,1,3600000,3600))}/></label><label>Windows<input type="number" value={windows} onChange={e=>setWindows(numeric(e.target.value,1,100,5))}/></label></div><div className="inline"><label>Wall minutes<input type="number" value={wallMinutes} onChange={e=>setWallMinutes(numeric(e.target.value,1,1440,60))}/></label><label>Turns<input type="number" value={turns} onChange={e=>setTurns(numeric(e.target.value,1,1000,30))}/></label><label>Tool calls<input type="number" value={toolCalls} onChange={e=>setToolCalls(numeric(e.target.value,1,10000,200))}/></label></div></fieldset>
      <fieldset><legend>Human checkpoints</legend>{Object.keys(checkpoints).map(key=><label key={key}><input type="checkbox" checked={checkpoints[key as keyof typeof checkpoints]} onChange={e=>setCheckpoints(v=>({...v,[key]:e.target.checked}))}/>{key}</label>)}</fieldset><fieldset><legend>Learning policy</legend><label>Learning cadence<select value={learningCadence} onChange={e=>setLearningCadence(e.target.value)}><option value="after-session">After session</option><option value="batch">After configured batch</option><option value="off">Off</option></select></label><div className="inline"><label>Batch sessions<input type="number" value={learningBatch} onChange={e=>setLearningBatch(numeric(e.target.value,1,100,5))}/></label><label>Candidate cap<input type="number" value={learningCandidates} onChange={e=>setLearningCandidates(numeric(e.target.value,1,20,3))}/></label><label>Patch attempts<input type="number" value={learningAttempts} onChange={e=>setLearningAttempts(numeric(e.target.value,1,10,2))}/></label><label>Reserved learning turns<input type="number" min="0" max={turns} value={learningTurns} onChange={e=>setLearningTurns(numeric(e.target.value,0,turns,3))}/></label></div><label><input type="checkbox" checked={autoActivate} onChange={e=>setAutoActivate(e.target.checked)}/> Automatically activate after all gates pass</label></fieldset>
      <div className="inline"><input aria-label="Preset name" value={presetName} onChange={e=>setPresetName(e.target.value)} placeholder="Preset name"/><button type="button" onClick={()=>void savePreset()}>Save preset</button><select aria-label="Load preset" defaultValue="" onChange={e=>loadPreset(e.target.value)}><option value="">Load preset…</option>{options?.presets.map(v=><option key={v.id} value={v.id}>{v.id}</option>)}</select></div><button className="primary" disabled={busy||!model||!effort}>Launch workshop →</button></form>
      <div><h3>Live and final evidence</h3>{!sessions.length&&<p className="empty">No workshop session recorded.</p>}{sessions.map(s=><div className="workshop-row" key={String(s.id)}><button onClick={()=>inspect(s)}><strong>{String((s.assignment as Record<string,unknown>)?.objective??s.id)}</strong><span>{String(s.stage)} · iteration {String(s.activeIteration??'—')} · best {String(s.bestIteration??'none')} · {Array.isArray(s.assistance)&&s.assistance.length?'assisted':'unassisted'}</span><small>{JSON.stringify(s.selections)}</small></button>{s.stage==='checkpoint'&&<div className="inline" data-testid={`checkpoint-${String(s.id)}`}><span>{String((s.checkpoint as Record<string,unknown>|undefined)?.kind??'checkpoint')} until {String((s.checkpoint as Record<string,unknown>|undefined)?.deadline??s.checkpointDeadline)}</span><button type="button" onClick={()=>void checkpoint(s,'continue')}>Continue</button><button type="button" onClick={()=>void checkpoint(s,'finish')}>Finish</button></div>}</div>)}{iterations.map(i=><button className="workshop-row" key={String(i.id)} onClick={()=>inspect(i)}><strong>Iteration {String(i.number)}</strong><span>{String(i.stage)} · {i.valid===true?'eligible':i.valid===false?'invalid':'pending'}</span><small>{String(i.feedback??'No scorer feedback yet')}</small></button>)}<h3>Library</h3><div className="inline"><input aria-label="Library search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="product, profile, machine"/><button type="button" onClick={()=>void search()}>Search</button></div>{library.map((v,i)=><div className="workshop-row" key={String(v.revisionHash??i)}><button onClick={()=>inspect(v)}><strong>{String(v.label??v.id)}</strong><span>{String(v.profileId??'')}</span><small>{String(v.revisionHash??'')}</small></button><button onClick={()=>void launch(String(v.revisionHash))}>Improve</button><button onClick={()=>void exportRevision(String(v.revisionHash))}>Export</button></div>)}</div>
      <div><h3>Learning and activation</h3>{!outcomes.length&&!candidates.length&&!bundles.length&&<p className="empty">No maintenance outcome recorded yet.</p>}{outcomes.map(v=><button className="workshop-row" key={String(v.id)} onClick={()=>inspect(v)}><strong>{String(v.decision)}</strong><span>{String(v.scope)} · {String(v.reason)}</span><small>{Array.isArray(v.evidence)?v.evidence.join(' · '):'No evidence recorded'}</small></button>)}{candidates.map(v=><button className="workshop-row" key={String(v.id)} onClick={()=>inspect(v)}><strong>{String(v.scope)}</strong><span>{String(v.state)} · {String(v.reason??'pending')}</span><small>{String(v.contentHash)}</small></button>)}{bundles.map(v=><button className="workshop-row" key={String(v.hash)} onClick={()=>inspect(v)}><strong>Bundle {String(v.hash).slice(0,12)}</strong><span>{Array.isArray(v.attestations)?v.attestations.length:0} attestations</span><small>{JSON.stringify(v.files??{})}</small></button>)}{active&&<div className="workshop-row"><strong>Active generation {String(active.generation)}</strong><span>{String(active.activeHash)}</span><button onClick={()=>void learningControl('quarantine',String(active.activeHash))}>Quarantine active</button>{Array.isArray(active.verifiedHashes)&&active.verifiedHashes.filter(v=>v!==active.activeHash).map(v=><button key={String(v)} onClick={()=>void learningControl('rollback',String(v))}>Roll back to {String(v).slice(0,8)}</button>)}</div>}</div></div>
  </section>;
}
