import { useEffect, useMemo, useRef, useState } from 'react';
import type { DashboardSnapshot } from '../../runtime/dashboard-types.js';
import { clearWorkshopDraft, readWorkshopDraft, saveWorkshopDraft, WORKSHOP_DRAFT_KEY } from './workshop-draft.js';
import type { WorkshopDraftValues } from './workshop-draft.js';
import { clearPendingWorkshop, readPendingWorkshop, savePendingWorkshop } from './workshop-request.js';
import type { PendingWorkshopRequest } from './workshop-request.js';
import { AsyncFeedback, useAsyncActions } from './async-feedback.js';

type Api=(route:string,body?:unknown)=>Promise<unknown>;
type Selection={provider:'openai';modelId:string;reasoningEffort:string};
interface ModelOption{id:string;displayName:string|null;efforts:string[]}
interface Preset{id:string;assignment:Record<string,unknown>}
interface Options{provider:string;models:ModelOption[];profiles:string[];presets:Preset[];defaults:Record<string,unknown>}
interface ProfileFacts{profileId:string;profileRevision:number;gameVersion:string;allowedEquipment:string[];technologies:string[];modules:string[];beacons:string[]}
interface LoadedAssignment{objective:string;profileId:string;construction:'direct'|'character';libraryAccess:boolean;iterations:{attempts:number;earlyStop:boolean};checkpoints:{brief:boolean;afterScore:boolean;libraryAdmission:boolean;learningActivation:boolean};requestedSpeed:{numerator:string;denominator:string};settlingTicks:number;throughput:{windowTicks:number;windows:number}[];budgets:{wallMs:number;turns:number;toolCalls:number;learningReservedTurns:number};learning:{cadence:string;batchSessions:number;candidateCap:number;attemptsPerCandidate:number;autoActivate:boolean};models:{sessionDefault:Selection;overrides:Partial<Record<'designer'|'scorer'|'learnings',Selection>>}}
const rational=(value:string)=>{const normalized=/^\d+(?:\.\d+)?$/.test(value)?value:'0';const[whole,fraction='']=normalized.split('.');return{numerator:String(BigInt(whole+fraction)),denominator:String(10n**BigInt(fraction.length))};};
const selection=(modelId:string,reasoningEffort:string):Selection=>({provider:'openai',modelId,reasoningEffort});
const numeric=(value:string,min:number,max:number,fallback:number)=>{const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback;};
const checkpointLabels:Record<string,string>={brief:'Review before starting',afterScore:'Review after each score',libraryAdmission:'Approve library save',learningActivation:'Approve learning activation'};
const defaultObjective='create 15 green circuits per second';
const defaultSession=(models:ModelOption[])=>{const preferred=models.find(value=>value.displayName==='Astra')??models[0];return{model:preferred?.id??'',effort:preferred?.efforts.includes('medium')?'medium':preferred?.efforts[0]??''};};
const profileLabels:Record<string,string>={'starter-assembly':'Basic assembling equipment','advanced-assembly':'Advanced assembling equipment','electromagnetic-production':'Electromagnetic production'};

export function WorkshopPanel({api,data,inspect,beginInspect,mode,navigate,launchBlocked}:{api:Api;data:DashboardSnapshot|undefined;inspect:(v:unknown)=>void;beginInspect:()=>((v:unknown)=>void);mode:'setup'|'library';navigate:(url:string)=>void;launchBlocked:boolean}){
  const actions=useAsyncActions(mode);
  const panelRef=useRef<HTMLElement>(null);
  const[launchProblem,setLaunchProblem]=useState<{field:string;message:string}|null>(null);
  const[optionsError,setOptionsError]=useState('');
  function rejectLaunch(field:string,message:string){
    setLaunchProblem({field,message});
    const target=panelRef.current?.querySelector<HTMLElement>(`[data-launch-field="${field}"]`);
    const advanced=target?.closest('details');if(advanced)advanced.open=true;
    target?.focus({preventScroll:true});target?.scrollIntoView({block:'center',behavior:'smooth'});
  }
  const fieldError=(field:string)=>launchProblem?.field===field?<small className="alert" role="alert">{launchProblem.message}</small>:null;
  const draft=useMemo(()=>{try{return readWorkshopDraft(window.localStorage);}catch(error){return{values:null,message:`Saved setup unavailable; edits will stay in memory: ${String(error)}`,writable:true};}},[]);
  const recoveredRequest=useMemo(()=>{try{return readPendingWorkshop(window.localStorage);}catch{return null;}},[]);
  const[pendingRequest,setPendingRequest]=useState<PendingWorkshopRequest|null>(recoveredRequest);
  const restored=draft.values,writable=useRef(draft.writable);
  const[draftNotice,setDraftNotice]=useState(draft.message??'');
  const[improveRevision,setImproveRevision]=useState<string|null>(restored?.improveRevision??null);
  const[selectedGroupId,setSelectedGroupId]=useState<string|null>(restored?.selectedGroupId??null);
  const[options,setOptions]=useState<Options>();const[profileFacts,setProfileFacts]=useState<ProfileFacts|null>(null);const[profileNotice,setProfileNotice]=useState('');const[objective,setObjective]=useState(restored?.objective??defaultObjective);const[profile,setProfile]=useState(restored?.profile??'starter-assembly');const[construction,setConstruction]=useState<'direct'|'character'>(restored?.construction??'direct');const[libraryAccess,setLibraryAccess]=useState(restored?.libraryAccess??true);const[attempts,setAttempts]=useState(restored?.attempts??5);const[earlyStop,setEarlyStop]=useState(restored?.earlyStop??true);const[checkpoints,setCheckpoints]=useState(restored?.checkpoints??{brief:false,afterScore:false,libraryAdmission:false,learningActivation:false});
  const[model,setModel]=useState(restored?.model??'');const[effort,setEffort]=useState(restored?.effort??'medium');const[designerModel,setDesignerModel]=useState(restored?.designerModel??'');const[designerEffort,setDesignerEffort]=useState(restored?.designerEffort??'');const[scorerModel,setScorerModel]=useState(restored?.scorerModel??'');const[scorerEffort,setScorerEffort]=useState(restored?.scorerEffort??'');const[learningsModel,setLearningsModel]=useState(restored?.learningsModel??'');const[learningsEffort,setLearningsEffort]=useState(restored?.learningsEffort??'');
  const[speed,setSpeed]=useState(restored?.speed??'10');const[settling,setSettling]=useState(restored?.settling??600);const[windowTicks,setWindowTicks]=useState(restored?.windowTicks??3600);const[windows,setWindows]=useState(restored?.windows??5);const[wallMinutes,setWallMinutes]=useState(restored?.wallMinutes??60);const[turns,setTurns]=useState(restored?.turns??30);const[toolCalls,setToolCalls]=useState(restored?.toolCalls??200);const[learningCadence,setLearningCadence]=useState(restored?.learningCadence??'after-session');const[learningBatch,setLearningBatch]=useState(restored?.learningBatch??5);const[learningCandidates,setLearningCandidates]=useState(restored?.learningCandidates??3);const[learningAttempts,setLearningAttempts]=useState(restored?.learningAttempts??2);const[learningTurns,setLearningTurns]=useState(restored?.learningTurns??3);const[autoActivate,setAutoActivate]=useState(restored?.autoActivate??true);
  const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);const[query,setQuery]=useState('');const[library,setLibrary]=useState<Record<string,unknown>[]>([]);const[presetName,setPresetName]=useState('');
  useEffect(()=>{if(mode!=='setup')return;const query=new URLSearchParams(window.location.search),source=query.get('improve'),groupId=query.get('group');if(source){setImproveRevision(source);setNotice(`Improving exact library revision ${source}. Launch when ready.`);}
    if(groupId)setSelectedGroupId(groupId);
    if(groupId){void api(`workspace/groups/${encodeURIComponent(groupId)}`).then(raw=>{const group=raw as {kind:string;objective:string|null};if(group.kind==='brief'&&group.objective)setObjective(group.objective);}).catch(e=>setError(String(e)));}
  },[mode,api]);
  useEffect(()=>{if(!recoveredRequest)return;void checkPending(recoveredRequest);},[recoveredRequest]);
  useEffect(()=>{if(!data)return;void api('workshop/options').then(raw=>{const value=raw as Options;setOptions(value);
    if(restored?.model)return;
    const preferred=defaultSession(value.models);setModel(preferred.model);setEffort(preferred.effort);
  }).catch(e=>setOptionsError(String(e)));},[data?.run]);
  useEffect(()=>{if(!options?.profiles.includes(profile)){setProfileFacts(null);return;}let current=true;setProfileFacts(null);setProfileNotice('Loading installed profile details…');void api(`workshop/profile?profileId=${encodeURIComponent(profile)}`).then(raw=>{if(current){setProfileFacts(raw as ProfileFacts);setProfileNotice('');}}).catch(()=>{if(current)setProfileNotice('Installed profile details are unavailable until the game is connected.');});return()=>{current=false;};},[options,profile,api]);
  useEffect(()=>{const onStorage=(event:StorageEvent)=>{if(event.key===WORKSHOP_DRAFT_KEY){writable.current=false;setDraftNotice('Setup changed in another tab. Reset or reload before saving here.');}};
    window.addEventListener('storage',onStorage);return()=>window.removeEventListener('storage',onStorage);},[]);
  useEffect(()=>{if(!writable.current)return;const values:WorkshopDraftValues={objective,profile,construction,libraryAccess,attempts,earlyStop,checkpoints,model,effort,designerModel,designerEffort,scorerModel,scorerEffort,learningsModel,learningsEffort,speed,settling,windowTicks,windows,wallMinutes,turns,toolCalls,learningCadence,learningBatch,learningCandidates,learningAttempts,learningTurns,autoActivate,improveRevision,selectedGroupId};
    try{const problem=saveWorkshopDraft(window.localStorage,values);if(problem)setDraftNotice(problem);}catch(error){setDraftNotice(`Could not save setup on this device: ${String(error)}`);}
  },[objective,profile,construction,libraryAccess,attempts,earlyStop,checkpoints,model,effort,designerModel,designerEffort,scorerModel,scorerEffort,learningsModel,learningsEffort,speed,settling,windowTicks,windows,wallMinutes,turns,toolCalls,learningCadence,learningBatch,learningCandidates,learningAttempts,learningTurns,autoActivate,improveRevision,selectedGroupId]);
  function resetDraft(){let problem:string|null;try{problem=clearWorkshopDraft(window.localStorage);}catch(error){problem=String(error);}if(problem){setDraftNotice(problem);return;}writable.current=true;setObjective(defaultObjective);setLaunchProblem(null);setProfile('starter-assembly');setConstruction('direct');setLibraryAccess(true);setAttempts(5);setEarlyStop(true);setCheckpoints({brief:false,afterScore:false,libraryAdmission:false,learningActivation:false});const preferred=defaultSession(options?.models??[]);setModel(preferred.model);setEffort(preferred.effort);setDesignerModel('');setDesignerEffort('');setScorerModel('');setScorerEffort('');setLearningsModel('');setLearningsEffort('');setSpeed('10');setSettling(600);setWindowTicks(3600);setWindows(5);setWallMinutes(60);setTurns(30);setToolCalls(200);setLearningCadence('after-session');setLearningBatch(5);setLearningCandidates(3);setLearningAttempts(2);setLearningTurns(3);setAutoActivate(true);setImproveRevision(null);setSelectedGroupId(null);window.history.replaceState(null,'','/workshop');setDraftNotice('Saved setup reset to default settings.');}
  const modelOption=(id:string)=>options?.models.find(v=>v.id===id);const inherited=(id:string,base:string)=>id||base;const inheritedEffort=(id:string,value:string,base:string)=>id?value:base;
  const selectionProblems=options?[...(!options.profiles.includes(profile)?[`Profile ${profile} is unavailable in this installation.`]:[]),...([[model,effort,'Session default'],[designerModel,designerEffort,'Designer'],[scorerModel,scorerEffort,'Scorer'],[learningsModel,learningsEffort,'Learnings']] as const).flatMap(([id,reason,label])=>id&&!modelOption(id)?.efforts.includes(reason)?[`${label} model ${id}/${reason} is unavailable.`]:[])]:[];
  const makeRequest=(id:string,improveRevision:string|null=null)=>{const session=selection(model,effort);const overrides:Record<string,Selection>={};if(designerModel)overrides.designer=selection(designerModel,designerEffort);if(scorerModel)overrides.scorer=selection(scorerModel,scorerEffort);if(learningsModel)overrides.learnings=selection(learningsModel,learningsEffort);return{schema:1,id,revision:1,comparisonSeries:crypto.randomUUID(),objective,source:{kind:improveRevision?'revision':'brief',id:improveRevision},profileId:profile,construction,libraryAccess:improveRevision?true:libraryAccess,improveRevision,requestedSpeed:rational(speed),settlingTicks:settling,windowTicks,windows,rubric:{version:'rubric-1',weights:{throughput:rational('1')},materiality:{throughput:{numerator:'1',denominator:'100'}},directions:{throughput:'maximize'}},iterations:{attempts,mode:earlyStop?'maximum':'exact',earlyStop,plateauRounds:2},checkpoints:{...checkpoints,timeoutMs:600000,timeoutAction:'finish'},budgets:{wallMs:wallMinutes*60000,gameTicks:settling+windowTicks*windows,turns,toolCalls,reportedTokens:null,learningReservedTurns:learningTurns,learningReservedTools:12},models:{sessionDefault:session,overrides},learning:{cadence:learningCadence,batchSessions:learningBatch,candidateCap:learningCandidates,attemptsPerCandidate:learningAttempts,autoActivate}};};
  async function checkPending(pending:PendingWorkshopRequest){try{const result=await api(`workspace/requests/${encodeURIComponent(pending.id)}`) as {request:{state:string;reason:string|null};run:unknown};
    if(result.request.state==='preparing'||result.request.state==='active'||result.request.state==='stopping'||result.request.state==='held'){
      clearPendingWorkshop(window.localStorage);setPendingRequest(null);navigate(`/history/${pending.id}`);return;
    }
    setNotice(`Request ${pending.id}: ${result.request.state}${result.request.reason?` · ${result.request.reason}`:''}`);
    clearPendingWorkshop(window.localStorage);setPendingRequest(null);
  }catch{setNotice('The last launch response is unconfirmed. Check status or retry the same request.');}}
  async function launch(){
    // Keep the launch control available for guidance, but never admit a duplicate submission.
    if(busy)return;
    if(!writable.current){rejectLaunch('setup','Reset saved setup or load the other tab settings before launching.');return;}
    if(launchBlocked){rejectLaunch('ownership','Another run owns the managed game. Finish it or use Stop run in the active-run banner before launching.');return;}
    if(!options){rejectLaunch('model',optionsError?'Could not load managed options. Reload this page and check your ChatGPT connection.':'Managed options are still loading. Wait for the session model options, then try again.');return;}
    if(!objective.trim()){rejectLaunch('brief','Enter a product and target rate, for example create 15 green circuits per second.');return;}
    if(!options.profiles.includes(profile)){rejectLaunch('profile','Choose an available capability profile from this list.');return;}
    if(!modelOption(model)){rejectLaunch('model',options.models.length?'Choose an available session model from this list.':'No managed models are available. Check your ChatGPT connection and reload this page.');return;}
    if(!modelOption(model)?.efforts.includes(effort)){rejectLaunch('effort','Choose an available session effort for the selected model.');return;}
    for(const[id,reason,field,label]of [[designerModel,designerEffort,'designer','Designer'],[scorerModel,scorerEffort,'scorer','Scorer'],[learningsModel,learningsEffort,'learnings','Learnings']]as const){
      if(id&&!modelOption(id)){rejectLaunch(`${field}-model`,`${label} model is unavailable. Choose an available model or Inherit session default.`);return;}
      if(id&&!modelOption(id)?.efforts.includes(reason)){rejectLaunch(`${field}-effort`,`Choose an available ${label.toLowerCase()} effort, or set its model to Inherit session default.`);return;}
    }
    if(!/^\d+(?:\.\d+)?$/.test(speed)||!Number.isFinite(Number(speed))||Number(speed)<=0){rejectLaunch('speed','Enter a positive simulation speed, for example 10.');return;}
    setLaunchProblem(null);setBusy(true);setError('');setNotice('Submitting run request…');
    const id=pendingRequest?.id??crypto.randomUUID(),pending=pendingRequest??{schema:1 as const,id,assignment:makeRequest(id,improveRevision),selectedGroupId,createdAt:new Date().toISOString()};
    if(!pendingRequest){setPendingRequest(pending);try{const problem=savePendingWorkshop(window.localStorage,pending);if(problem)setNotice(`Submitting; local recovery unavailable: ${problem}`);}catch(error){setNotice(`Submitting; local recovery unavailable: ${String(error)}`);}}
    const timer=setTimeout(()=>setNotice('Launch response is still unconfirmed. Check status before trying again.'),10000);
    try{const session=await api('workshop/launch',{assignment:pending.assignment,selectedGroupId:pending.selectedGroupId}) as Record<string,unknown>;
      setNotice(`Workshop ${pending.id} accepted · ${String(session.state??'preparing')}`);
      try{clearPendingWorkshop(window.localStorage);}catch{}setPendingRequest(null);navigate(`/history/${pending.id}`);
    }catch(e){setError(`Launch outcome unconfirmed: ${String(e)}. Check request status before retrying.`);}finally{clearTimeout(timer);setBusy(false);}}
  async function stopPending(){if(!pendingRequest)return;setBusy(true);setNotice('Stop requested before admission…');try{await api('workshop/stop',{sessionId:pendingRequest.id,reason:'operator_stop'});
    try{clearPendingWorkshop(window.localStorage);}catch{}setPendingRequest(null);setNotice('Pre-admission stop recorded.');
  }catch(e){setError(`Stop outcome unconfirmed: ${String(e)}`);}finally{setBusy(false);}}
  async function savePreset(){await actions.run('preset','Saving preset…',async current=>{if(!presetName.trim())throw new Error('Preset name is required');const id=presetName.trim().toLowerCase().replace(/[^a-z0-9.-]+/g,'-');const saved=await api('workshop/preset',{id,assignment:{...makeRequest(id),source:{kind:'preset',id}}});const options=await api('workshop/options') as Options;if(current()){inspect(saved);setOptions(options);}},'Preset saved.');}
  function loadPreset(id:string){const preset=options?.presets.find(v=>v.id===id);if(!preset)return;const a=preset.assignment as unknown as LoadedAssignment;setObjective(String(a.objective));setProfile(String(a.profileId));setConstruction(a.construction);setLibraryAccess(Boolean(a.libraryAccess));setAttempts(Number(a.iterations.attempts));setEarlyStop(Boolean(a.iterations.earlyStop));setCheckpoints(a.checkpoints);setSpeed(String(Number(a.requestedSpeed.numerator)/Number(a.requestedSpeed.denominator)));setSettling(Number(a.settlingTicks));setWindowTicks(Number(a.throughput[0]!.windowTicks));setWindows(Number(a.throughput[0]!.windows));setWallMinutes(Number(a.budgets.wallMs)/60000);setTurns(Number(a.budgets.turns));setToolCalls(Number(a.budgets.toolCalls));setLearningTurns(Number(a.budgets.learningReservedTurns));setLearningCadence(a.learning.cadence);setLearningBatch(Number(a.learning.batchSessions));setLearningCandidates(Number(a.learning.candidateCap));setLearningAttempts(Number(a.learning.attemptsPerCandidate));setAutoActivate(Boolean(a.learning.autoActivate));setModel(a.models.sessionDefault.modelId);setEffort(a.models.sessionDefault.reasoningEffort);for(const[role,setM,setE]of [['designer',setDesignerModel,setDesignerEffort],['scorer',setScorerModel,setScorerEffort],['learnings',setLearningsModel,setLearningsEffort]] as const){const s=a.models.overrides[role];setM(s?.modelId??'');setE(s?.reasoningEffort??'');}setNotice(`Preset ${id} loaded into this setup. Launch when ready.`);}
  async function search(){await actions.run('search','Searching library…',async current=>{const value=await api('workshop/library?q='+encodeURIComponent(query)) as {items:Record<string,unknown>[]};if(current())setLibrary(value.items);},'Library search complete.');}
  async function exportRevision(hash:string){await actions.run(`export:${hash}`,'Exporting blueprint…',async current=>{const publish=beginInspect();const value=await api(`workshop/library/${encodeURIComponent(hash)}/export`);if(current())publish(value);},'Blueprint export ready.');}
  async function learningControl(action:'rollback'|'quarantine',hash:string){try{inspect(await api('workshop/learning',action==='rollback'?{action,hash,operationId:crypto.randomUUID()}:{action,hash,reason:'Operator quarantine'}));}catch(e){setError(String(e));}}
  async function checkpoint(session:Record<string,unknown>,action:'continue'|'finish'){try{inspect(await api('workshop/checkpoint',{sessionId:session.id,revision:Number(session.steeringRevision)+1,action,text:action==='continue'?'Operator approved checkpoint':'Operator ended session at checkpoint'}));}catch(e){setError(String(e));}}
  const sessions=data?.projections.workshopSessions??[],iterations=data?.projections.workshopIterations??[],operations=(data?.projections.workshopOperations??[]).slice().sort((a,b)=>String(b.at??'').localeCompare(String(a.at??''))).slice(0,30),candidates=data?.projections.learningCandidates??[],outcomes=data?.projections.learningOutcomes??[],bundles=data?.projections.learningBundles??[],activations=data?.projections.activations??[];const active=activations[0] as Record<string,unknown>|undefined;
  const effective=useMemo(()=>({designer:`${inherited(designerModel,model)}/${inheritedEffort(designerModel,designerEffort,effort)}`,scorer:`${inherited(scorerModel,model)}/${inheritedEffort(scorerModel,scorerEffort,effort)}`,learnings:`${inherited(learningsModel,model)}/${inheritedEffort(learningsModel,learningsEffort,effort)}`}),[designerModel,designerEffort,scorerModel,scorerEffort,learningsModel,learningsEffort,model,effort]);
  const roleSelector=(label:string,id:string,setId:(v:string)=>void,valueEffort:string,setValueEffort:(v:string)=>void)=>{const aria=label.replace(' override','');return <><label>{label}<select data-launch-field={`${aria.toLowerCase()}-model`} aria-label={`${aria} model`} value={id} onChange={e=>{const next=e.target.value;setId(next);setValueEffort(next?(modelOption(next)?.efforts[0]??''):'' );}}><option value="">Inherit session default</option>{id&&!modelOption(id)&&<option value={id}>{id} (unavailable)</option>}{options?.models.map(v=><option key={v.id} value={v.id}>{v.displayName??v.id}</option>)}</select>{fieldError(`${aria.toLowerCase()}-model`)}</label><label>{label} effort<select data-launch-field={`${aria.toLowerCase()}-effort`} aria-label={`${aria} effort`} value={id?valueEffort:effort} disabled={!id} onChange={e=>setValueEffort(e.target.value)}>{id&&<option value="">Select effort</option>}{id&&valueEffort&&!modelOption(id)?.efforts.includes(valueEffort)&&<option value={valueEffort}>{valueEffort} (unavailable)</option>}{(id?modelOption(id):modelOption(model))?.efforts.map(v=><option key={v}>{v}</option>)}</select>{fieldError(`${aria.toLowerCase()}-effort`)}</label></>;};
  return <section ref={panelRef} className="panel workshop" data-mode={mode} data-testid="workshop"><AsyncFeedback actions={actions}/><div className="sectiontitle"><div><p className="eyebrow">{mode==='library'?'BLUEPRINT LIBRARY':'BLUEPRINT WORKSHOP'}</p><h2>{mode==='library'?'Preserved designs':'Design, prove, preserve.'}</h2></div><span>{sessions.length} sessions</span></div>{error&&<p className="alert" role="alert">{error}</p>}{notice&&<p className="notice" role="status" aria-live="polite">{notice}</p>}{selectionProblems.map(problem=><p className="alert" role="alert" key={problem}>{problem}</p>)}{mode==='setup'&&<div className="inline"><p className="hint" role="status">{draftNotice||'Setup is saved on this device.'}</p>{!writable.current&&<button type="button" onClick={()=>window.location.reload()}>Load other tab settings</button>}<button type="button" data-launch-field="setup" onClick={resetDraft}>Reset saved setup</button>{fieldError('setup')}</div>}
    <div className="workshop-grid"><form onSubmit={e=>{e.preventDefault();void launch();}}><h3>Launch / Improve</h3><label>Brief<textarea data-launch-field="brief" value={objective} onChange={e=>setObjective(e.target.value)}/>{fieldError('brief')}<small>The exact wording identifies this brief in Run History. Editing it starts a linked brief.</small></label><label>Capability profile<select data-launch-field="profile" value={profile} onChange={e=>setProfile(e.target.value)}>{options&&!options.profiles.includes(profile)&&<option value={profile}>{profile} (unavailable)</option>}{options?.profiles.map(v=><option key={v} value={v}>{profileLabels[v]??v}</option>)}</select>{fieldError('profile')}<small>Equipment and research come from the installed game. Technical profile: {profile}.</small>{profileFacts&&<small>Permitted equipment: {profileFacts.allowedEquipment.join(', ')||'none'}. Research: {profileFacts.technologies.join(', ')||'none'}. Game {profileFacts.gameVersion}; profile revision {profileFacts.profileRevision}.</small>}{profileNotice&&<small role="status">{profileNotice}</small>}</label><label>Build method<select aria-label="Construction" value={construction} onChange={e=>setConstruction(e.target.value as 'direct'|'character')}><option value="direct">Instant sandbox placement</option><option value="character">Build with a character</option></select><small>{construction==='direct'?'A separate sandbox creates entities instantly and supplies its test fixtures. This does not measure character travel or placement time.':'The connected builder walks, reaches, crafts and places under normal game rules. Materials are provisioned to finite character inventory before construction.'}</small></label><label><input type="checkbox" checked={libraryAccess} onChange={e=>setLibraryAccess(e.target.checked)}/> Allow library access</label><div className="inline"><label>Number of attempts<input aria-label="Attempts" type="number" min="1" max="100" value={attempts} onChange={e=>setAttempts(numeric(e.target.value,1,100,5))}/></label><label><input type="checkbox" checked={earlyStop} onChange={e=>setEarlyStop(e.target.checked)}/> Stop early after a plateau</label></div>
      <label>Session model<select data-launch-field="model" aria-label="Session model" value={model} onChange={e=>{setModel(e.target.value);setEffort(modelOption(e.target.value)?.efforts.includes('medium')?'medium':modelOption(e.target.value)?.efforts[0]??'');}}><option value="">Select managed model</option>{model&&!modelOption(model)&&<option value={model}>{model} (unavailable)</option>}{options?.models.map(v=><option key={v.id} value={v.id}>{v.displayName??v.id}</option>)}</select>{fieldError('model')}</label><label>Session effort<select data-launch-field="effort" aria-label="Session effort" value={effort} onChange={e=>setEffort(e.target.value)}><option value="">Select session effort</option>{effort&&!modelOption(model)?.efforts.includes(effort)&&<option value={effort}>{effort} (unavailable)</option>}{modelOption(model)?.efforts.map(v=><option key={v}>{v}</option>)}</select>{fieldError('effort')}</label><small>Uses your managed ChatGPT selection. No model or billing fallback is applied.</small><details className="advanced-options"><summary>Advanced settings</summary>{roleSelector('Designer override',designerModel,setDesignerModel,designerEffort,setDesignerEffort)}{roleSelector('Scorer override',scorerModel,setScorerModel,scorerEffort,setScorerEffort)}{roleSelector('Learnings override',learningsModel,setLearningsModel,learningsEffort,setLearningsEffort)}<p className="hint" data-testid="effective-selections">Effective: designer {effective.designer}; scorer {effective.scorer}; learnings {effective.learnings}</p>
      <fieldset><legend>Evaluation</legend><div className="inline"><label>Simulation speed<input data-launch-field="speed" aria-label="Evaluation speed" value={speed} onChange={e=>setSpeed(e.target.value)}/>{fieldError('speed')}</label><label>Warm-up time (seconds)<input type="number" value={settling/60} onChange={e=>setSettling(numeric(e.target.value,0,60000,10)*60)}/><small>{settling} ticks</small></label><label>Measurement window (seconds)<input type="number" value={windowTicks/60} onChange={e=>setWindowTicks(numeric(e.target.value,1/60,60000,60)*60)}/><small>{windowTicks} ticks per window</small></label><label>Number of windows<input type="number" value={windows} onChange={e=>setWindows(numeric(e.target.value,1,100,5))}/></label></div><p className="hint">Measurements use fixed game ticks: 60 ticks per game second, independent of simulation speed.</p><div className="inline"><label>Real-time limit (minutes)<input type="number" value={wallMinutes} onChange={e=>setWallMinutes(numeric(e.target.value,1,1440,60))}/></label><label>Model turn limit<input type="number" value={turns} onChange={e=>setTurns(numeric(e.target.value,1,1000,30))}/></label><label>Tool-call limit<input type="number" value={toolCalls} onChange={e=>setToolCalls(numeric(e.target.value,1,10000,200))}/></label></div></fieldset>
      <fieldset><legend>Human checkpoints</legend><p className="hint">A checkpoint waits for your decision; Finish after this attempt ends normally, while Stop run cancels remaining work.</p>{Object.keys(checkpoints).map(key=><label key={key}><input aria-label={key} type="checkbox" checked={checkpoints[key as keyof typeof checkpoints]} onChange={e=>setCheckpoints(v=>({...v,[key]:e.target.checked}))}/>{checkpointLabels[key]}</label>)}</fieldset><fieldset><legend>Improvement between runs</legend><label>Improvement cadence<select value={learningCadence} onChange={e=>setLearningCadence(e.target.value)}><option value="after-session">After session</option><option value="batch">After configured batch</option><option value="off">Off</option></select></label><div className="inline"><label>Batch sessions<input type="number" value={learningBatch} onChange={e=>setLearningBatch(numeric(e.target.value,1,100,5))}/></label><label>Candidate cap<input type="number" value={learningCandidates} onChange={e=>setLearningCandidates(numeric(e.target.value,1,20,3))}/></label><label>Patch attempts<input type="number" value={learningAttempts} onChange={e=>setLearningAttempts(numeric(e.target.value,1,10,2))}/></label><label>Reserved learning turns<input type="number" min="0" max={turns} value={learningTurns} onChange={e=>setLearningTurns(numeric(e.target.value,0,turns,3))}/></label></div><label><input type="checkbox" checked={autoActivate} onChange={e=>setAutoActivate(e.target.checked)}/> Automatically activate after all verification gates pass</label></fieldset></details>
      <div className="inline"><input aria-label="Preset name" value={presetName} onChange={e=>setPresetName(e.target.value)} placeholder="Preset name"/><button type="button" disabled={actions.pending('preset')} onClick={()=>void savePreset()}>{actions.pending('preset')?'Saving preset…':'Save preset'}</button><select aria-label="Load preset" defaultValue="" onChange={e=>loadPreset(e.target.value)}><option value="">Load preset…</option>{options?.presets.map(v=><option key={v.id} value={v.id}>{v.id}</option>)}</select></div>{improveRevision&&<p className="hint">Improving revision {improveRevision} <button type="button" onClick={()=>setImproveRevision(null)}>Clear source</button></p>}<button className="primary" aria-busy={busy}>{busy?'Submitting run…':pendingRequest?'Retry same launch request':'Launch workshop'} →</button>{pendingRequest&&<div className="inline"><button type="button" onClick={()=>void checkPending(pendingRequest)}>Check launch status</button><button type="button" onClick={()=>void stopPending()}>Stop run before admission</button></div>}{launchBlocked&&<p className="hint" tabIndex={-1} data-launch-field="ownership">{launchProblem?.field==='ownership'?fieldError('ownership'):'Another run owns the managed game. Finish or stop it before launching.'}</p>}</form>
      <div className="workshop-recorded"><h3>Live and final evidence</h3>{!sessions.length&&<p className="empty">No workshop session recorded.</p>}{sessions.map(s=><div className={`workshop-row ${String(s.stage)}`} key={String(s.id)}><button onClick={()=>inspect(s)}><strong>{String((s.assignment as Record<string,unknown>)?.objective??s.id)}</strong><span>{String(s.stage)} · iteration {String(s.activeIteration??'—')} · best {String(s.bestIteration??'none')} · {Array.isArray(s.assistance)&&s.assistance.length?'assisted':'unassisted'}</span>{Boolean(s.stopReason)&&<small className="failure">{String(s.stopReason)}</small>}<small>{JSON.stringify(s.selections)}</small></button>{s.stage==='checkpoint'&&<div className="inline" data-testid={`checkpoint-${String(s.id)}`}><span>{String((s.checkpoint as Record<string,unknown>|undefined)?.kind??'checkpoint')} until {String((s.checkpoint as Record<string,unknown>|undefined)?.deadline??s.checkpointDeadline)}</span><button type="button" onClick={()=>void checkpoint(s,'continue')}>Continue</button><button type="button" onClick={()=>void checkpoint(s,'finish')}>Finish</button></div>}</div>)}{iterations.map(i=><button className="workshop-row" key={String(i.id)} onClick={()=>inspect(i)}><strong>Iteration {String(i.number)}</strong><span>{String(i.stage)} · {i.valid===true?'eligible':i.valid===false?'invalid':'pending'}</span><small>{String(i.feedback??'No scorer feedback yet')}</small></button>)}<h3>Workshop activity</h3>{!operations.length&&<p className="empty">No workshop activity recorded.</p>}{operations.map(v=><button className={`workshop-row activity-${String(v.status)}`} key={String(v.id)} onClick={()=>inspect(v)}><strong>{String(v.category)} · {String(v.status)}</strong><span>{String(v.role??v.detail??v.sessionId)}</span><small>{String(v.at??'')}</small></button>)}</div><div className="workshop-library"><h3>Library</h3><div className="inline"><input aria-label="Library search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="product, profile, machine"/><button type="button" disabled={actions.pending('search')} onClick={()=>void search()}>{actions.pending('search')?'Searching…':'Search'}</button></div>{library.map((v,i)=><div className="workshop-row" key={String(v.revisionHash??i)}><button onClick={()=>inspect(v)}><strong>{String(v.label??v.id)}</strong><span>{String(v.profileId??'')}</span><small>{String(v.revisionHash??'')}</small></button><button onClick={()=>{setImproveRevision(String(v.revisionHash));navigate(`/workshop?improve=${encodeURIComponent(String(v.revisionHash))}`);}}>Improve</button><button disabled={actions.pending(`export:${String(v.revisionHash)}`)} onClick={()=>void exportRevision(String(v.revisionHash))}>{actions.pending(`export:${String(v.revisionHash)}`)?'Exporting…':'Export'}</button></div>)}</div>
      <div className="workshop-learning"><h3>Learning and activation</h3>{!outcomes.length&&!candidates.length&&!bundles.length&&<p className="empty">No maintenance outcome recorded yet.</p>}{outcomes.map(v=><button className="workshop-row" key={String(v.id)} onClick={()=>inspect(v)}><strong>{String(v.decision)}</strong><span>{String(v.scope)} · {String(v.reason)}</span><small>{Array.isArray(v.evidence)?v.evidence.join(' · '):'No evidence recorded'}</small></button>)}{candidates.map(v=><button className="workshop-row" key={String(v.id)} onClick={()=>inspect(v)}><strong>{String(v.scope)}</strong><span>{String(v.state)} · {String(v.reason??'pending')}</span><small>{String(v.contentHash)}</small></button>)}{bundles.map(v=><button className="workshop-row" key={String(v.hash)} onClick={()=>inspect(v)}><strong>Bundle {String(v.hash).slice(0,12)}</strong><span>{Array.isArray(v.attestations)?v.attestations.length:0} attestations</span><small>{JSON.stringify(v.files??{})}</small></button>)}{active&&<div className="workshop-row"><strong>Active generation {String(active.generation)}</strong><span>{String(active.activeHash)}</span><button onClick={()=>void learningControl('quarantine',String(active.activeHash))}>Quarantine active</button>{Array.isArray(active.verifiedHashes)&&active.verifiedHashes.filter(v=>v!==active.activeHash).map(v=><button key={String(v)} onClick={()=>void learningControl('rollback',String(v))}>Roll back to {String(v).slice(0,8)}</button>)}</div>}</div></div>
  </section>;
}
