import { spawn, spawnSync } from 'node:child_process';
import { mkdir, mkdtemp, writeFile, cp } from 'node:fs/promises';
import { openSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import path from 'node:path';

const headless = process.argv.includes('--headless');
const prepareOnly = process.argv.includes('--prepare-only');
const installation = 'C:/Program Files (x86)/Steam/steamapps/common/Factorio';
const executable = path.join(installation, 'bin/x64/factorio.exe');
const base = path.resolve('.runtime/phase03'); await mkdir(base, { recursive: true });
const dir = await mkdtemp(path.join(base, 'game-'));
await mkdir(path.join(dir, 'mods')); await mkdir(path.join(dir, 'data/saves'), {recursive:true});
await cp('mods/autofactorio', path.join(dir, 'mods/autofactorio_0.1.0'), { recursive: true });
await writeFile(path.join(dir, 'mods/mod-list.json'), JSON.stringify({mods:['base','space-age','quality','elevated-rails','autofactorio'].map(name=>({name,enabled:true}))}));
const config = path.join(dir,'config.ini');
await writeFile(config, '[path]\nread-data=' + installation + '/data\nwrite-data=' + dir.replaceAll('\\','/') + '/data\n[general]\nlocale=en\n[graphics]\nfull-screen=false\n[other]\ncheck-updates=false\nenable-blueprint-storage-cloud-sync=false\n');
const settings=path.join(dir,'server-settings.json');
await writeFile(settings,JSON.stringify({name:'AutoFactorio phase 03',description:'Dedicated legal-action validation',visibility:{public:false,lan:false},require_user_verification:false,auto_pause:false,autosave_interval:0,allow_commands:'admins-only'}));
const gen=path.join(dir,'map-gen.json'); await writeFile(gen,JSON.stringify({width:128,height:128,seed:42,water:0,autoplace_controls:{'enemy-base':{frequency:0},trees:{frequency:0}}}));
const save=path.join(dir,'sandbox.zip');
const common=['--config',config,'--mod-directory',path.join(dir,'mods')];
const created=spawnSync(executable,[...common,'--create',save,'--map-gen-settings',gen],{encoding:'utf8',windowsHide:true,timeout:120000});
await writeFile(path.join(dir,'create.log'),(created.stdout??'')+(created.stderr??''));
if(created.status!==0)throw new Error('Map creation failed: '+dir);
const password=randomBytes(24).toString('hex');
const port=headless?27019:27018;
const log=openSync(path.join(dir,'host-process.log'),'a');
const args=[...common,'--start-server',save,'--server-settings',settings,'--bind',headless?'127.0.0.1:34199':'127.0.0.1:34198','--rcon-bind','127.0.0.1:'+port,'--rcon-password',password,'--disable-audio','--window-size','1280x800'];
const child=prepareOnly?undefined:spawn(executable,args,{detached:true,stdio:['ignore',log,log],windowsHide:true});
child?.unref();
const observerData=path.join(dir,'observer-data');await mkdir(observerData);
const observerConfig=path.join(dir,'observer-config.ini');
await writeFile(observerConfig,'[path]\nread-data='+installation+'/data\nwrite-data='+observerData.replaceAll('\\','/')+'\n[general]\nlocale=en\n[graphics]\nfull-screen=false\n[other]\nenable-blueprint-storage-cloud-sync=false\n');
const observerArgs=['-applaunch','427520','--config',observerConfig,'--mod-directory',path.join(dir,'mods'),'--mp-connect','127.0.0.1:'+(headless?34199:34198),'--disable-audio','--window-size','1280x800'];
if(!headless&&!prepareOnly){const observer=spawn('C:/Program Files (x86)/Steam/steam.exe',observerArgs,{detached:true,stdio:'ignore',windowsHide:false});observer.unref();}
await writeFile(path.join(dir,'launch-observer.ps1'),'& '+['C:/Program Files (x86)/Steam/steam.exe',...observerArgs].map(v=>"'"+v.replaceAll("'","''")+"'").join(' ')+'\n');
await writeFile(path.join(dir,'launch.ps1'), '& ' + [executable,...args].map(v=>"'"+v.replaceAll("'","''")+"'").join(' ') + '\n');
await writeFile(path.join(dir,'launch.json'),JSON.stringify({dir,pid:child?.pid,port,password,save,config,executable,observerConfig,observerData},null,2));
await writeFile(path.join(base,headless?'headless.json':'current.json'),JSON.stringify({dir}));
console.log(JSON.stringify({dir,pid:child?.pid,port,visible:!headless&&!prepareOnly}));
