import assert from 'node:assert/strict';
import { access, mkdtemp, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { validateWorkshopAssignment } from '@autofactorio/contracts';
import type { BlueprintDocument, WorkshopAssignment, WorkshopWindowMeasurement } from '@autofactorio/contracts';
import type { CapabilityProfile } from '../packages/core/workshop/profiles.js';
import { evaluateWorkshop } from '../packages/core/workshop/evaluation.js';
import { WorkshopControl } from '../packages/factorio/src/workshop.js';
import { reconcileWorkshopMeasurementFence } from '../apps/runtime/workshop-live-host.js';
import { createProfile, startServer, stopProfile, waitForServer } from './dev/game-processes.js';

const gameProfile=await createProfile(false,true),evidence=await mkdtemp(path.join(gameProfile.dir,'workshop-measure-probe-'));const checks:string[]=[];let failure:string|null=null;const pass=(message:string)=>{checks.push(message);console.log(message);};console.log(JSON.stringify({evidence,profile:gameProfile.config}));await startServer(gameProfile);const port=await waitForServer(gameProfile);await port.command('/silent-command rcon.print("workshop console authorization")');await port.command('/silent-command rcon.print("workshop console ready")');const control=new WorkshopControl(port);
const capability:CapabilityProfile={schema:1,id:'measurement',revision:1,fingerprint:'live-2.0.77',source:'custom',technologies:['automation','automation-2'],researchBonuses:{},recipes:['iron-gear-wheel'],allowedEquipment:['assembling-machine-2','inserter','small-electric-pole'],locallyManufacturable:[],modules:[],beacons:[],quality:'normal',surface:'nauvis'};
const document:BlueprintDocument={schema:1,label:'Measured gear cell',description:'Live measurement reference',entities:[
  {id:'assembler',entityNumber:1,name:'assembling-machine-2',position:{x:0,y:0},direction:0,quality:'normal',recipe:'iron-gear-wheel'},
  {id:'output',entityNumber:2,name:'inserter',position:{x:2,y:0},direction:12,quality:'normal'},
  {id:'pole-machine',entityNumber:3,name:'small-electric-pole',position:{x:0,y:3},direction:0,quality:'normal'},
  {id:'pole-output',entityNumber:4,name:'small-electric-pole',position:{x:2,y:2},direction:0,quality:'normal'},
],wires:[],ports:[],icons:[{index:1,name:'iron-gear-wheel'}],tiles:[]};
const integer=(value:{numerator:string;denominator:string})=>{assert.equal(value.denominator,'1');return Number(value.numerator);};
async function preload(surface:string,input:number,buffer:number){
  const raw=await port.command(`/silent-command local s=game.surfaces[${JSON.stringify(surface)}];local a=s.find_entities_filtered{name="assembling-machine-2"}[1];local i=0;if ${input}>0 then i=a.get_inventory(defines.inventory.assembling_machine_input).insert{name="iron-plate",count=${input}} end;local o=0;if ${buffer}>0 then o=a.get_inventory(defines.inventory.assembling_machine_output).insert{name="iron-gear-wheel",count=${buffer}} end;rcon.print(helpers.table_to_json{input=i,buffer=o})`);if(!raw.startsWith('{'))throw new Error(`Workshop preload failed: ${raw}`);
  const inserted=JSON.parse(raw) as {input:number;buffer:number};
  assert.deepEqual(inserted,{input,buffer});
}
interface RunOptions{speed:number;settlingTicks:number;windowTicks:number;windows:number;inputStock:number;bufferStock?:number;pause?:boolean;initiallyPaused?:boolean}
async function run(id:string,options:RunOptions){const setup=await control.setup({id,surface:`af-${id}`,force:`af-${id}`,profile:capability,area:[{x:-256,y:-256},{x:256,y:256}],maxTiles:512*512,fixtures:[{id:'source',kind:'source',position:{x:-3,y:0},product:{kind:'item',name:'iron-plate',quality:'normal'},rate:0},{id:'sink',kind:'sink',position:{x:3,y:0},product:{kind:'item',name:'iron-gear-wheel',quality:'normal'},rate:0},{id:'power',kind:'power',position:{x:0,y:5},product:{kind:'item',name:'electricity',quality:'normal'},rate:0}]});await control.materialize(id,Number(setup.generation),`${id}-build`,document);await preload(`af-${id}`,options.inputStock,options.bufferStock??0);if(options.initiallyPaused)assert.equal((await port.command('/silent-command game.tick_paused=true;rcon.print(tostring(game.tick_paused))')).trim(),'true');const admitted=await control.measureConfigure({id,generation:Number(setup.generation),attemptId:`${id}-attempt`,settlingTicks:options.settlingTicks,windowTicks:options.windowTicks,windows:options.windows,requestedSpeed:options.speed,ports:[{id:'gears',fixtureId:'sink',product:{kind:'item',name:'iron-gear-wheel',quality:'normal'}}]});assert.equal(admitted.requestedSpeed,options.speed);let after=-1;const samples:WorkshopWindowMeasurement[]=[];let pausedTick:number|undefined;const deadline=Date.now()+((options.settlingTicks+options.windowTicks*options.windows)/60/options.speed)*1500+30000;
  while(Date.now()<deadline){const page=await control.measureRead(id,`${id}-attempt`,after);for(const sample of page.samples){samples.push(sample);after=Math.max(after,sample.index);console.log(JSON.stringify({id,window:sample.index+1,windows:options.windows,tick:page.tick,production:sample.ports[0]?.production,delivery:sample.ports[0]?.delivery,opening:sample.ports[0]?.openingStock,closing:sample.ports[0]?.closingStock}));}if(options.pause&&pausedTick===undefined&&page.state==='scoring'){await port.command('/silent-command game.tick_paused=true;rcon.print("paused")');const held=await control.measureRead(id,`${id}-attempt`,after);pausedTick=held.tick;await delay(300);const heldAgain=await control.measureRead(id,`${id}-attempt`,after);assert.equal(heldAgain.tick,pausedTick);await port.command('/silent-command game.tick_paused=false;rcon.print("resumed")');}if(page.finished){if(options.initiallyPaused){assert.equal((await port.command('/silent-command rcon.print(tostring(game.tick_paused))')).trim(),'true');await port.command('/silent-command game.tick_paused=false;rcon.print("unpaused after restoration check")');}return{samples,pausedTick};}await delay(100);}throw new Error('Workshop measurement timeout');}
function assignment(id:string,samples:WorkshopWindowMeasurement[],required:number,maxStockDrawdown:number):WorkshopAssignment{const windowTicks=samples[0]!.endTick-samples[0]!.startTick;return validateWorkshopAssignment({schema:1,id,revision:1,comparisonSeries:`${id}-series`,objective:'Prove live gear throughput',source:{kind:'brief',id:null},ports:[{id:'iron',direction:'input',product:{kind:'item',name:'iron-plate',quality:'normal',surface:'nauvis'},position:{x:-3,y:0},facing:4,transport:'belt',lane:1,rate:{numerator:'0',denominator:'1'},unit:'units-per-game-second',required:true},{id:'gears',direction:'output',product:{kind:'item',name:'iron-gear-wheel',quality:'normal',surface:'nauvis'},position:{x:3,y:0},facing:4,transport:'belt',lane:1,rate:{numerator:String(required*60),denominator:String(windowTicks)},unit:'units-per-game-second',required:true}],profileId:'measurement',profileRevision:1,gameFingerprint:'live-2.0.77',footprint:{width:16,height:8,clearance:1,maxTiles:512*512},construction:'direct',libraryAccess:false,improveRevision:null,requestedSpeed:{numerator:'1',denominator:'1'},settlingTicks:0,throughput:[{portId:'gears',windowTicks,windows:samples.length,quantum:{numerator:'1',denominator:'1'},productionError:{numerator:'0',denominator:'1'},deliveryError:{numerator:'0',denominator:'1'},maxStockDrawdown:{numerator:String(maxStockDrawdown),denominator:'1'},maxResidual:{numerator:'1',denominator:'1'},interval:'(startTick,endTick]'}],rubric:{version:'live-control-1',weights:{throughput:{numerator:'1',denominator:'1'}},materiality:{throughput:{numerator:'1',denominator:'1'}}},iterations:{attempts:1,mode:'exact',earlyStop:false,plateauRounds:1},checkpoints:{brief:false,afterScore:false,libraryAdmission:false,learningActivation:false,timeoutMs:600000,timeoutAction:'finish'},budgets:{wallMs:600000,gameTicks:100000,turns:1,toolCalls:1,reportedTokens:null,learningReservedTurns:0,learningReservedTools:0},models:{sessionDefault:{provider:'openai',modelId:'gpt-6-astra',reasoningEffort:'low'},overrides:{}},learning:{cadence:'off',batchSessions:1,candidateCap:1,attemptsPerCandidate:1,autoActivate:false}});}
try{
  const abortSetup=await control.setup({id:'measure-abort',surface:'af-measure-abort',force:'af-measure-abort',profile:capability,area:[{x:-256,y:-256},{x:256,y:256}],maxTiles:512*512,fixtures:[{id:'source',kind:'source',position:{x:-3,y:0},product:{kind:'item',name:'iron-plate',quality:'normal'},rate:0},{id:'sink',kind:'sink',position:{x:3,y:0},product:{kind:'item',name:'iron-gear-wheel',quality:'normal'},rate:0},{id:'power',kind:'power',position:{x:0,y:5},product:{kind:'item',name:'electricity',quality:'normal'},rate:0}]});await control.materialize('measure-abort',Number(abortSetup.generation),'measure-abort-build',document);await port.command('/silent-command game.speed=2;game.tick_paused=true;rcon.print("abort setup ready")');await control.measureConfigure({id:'measure-abort',generation:Number(abortSetup.generation),attemptId:'measure-abort-attempt',settlingTicks:600,windowTicks:600,windows:2,requestedSpeed:10,ports:[{id:'gears',fixtureId:'sink',product:{kind:'item',name:'iron-gear-wheel',quality:'normal'}}]});const aborted=await control.measureAbort('measure-abort','measure-abort-attempt');assert.deepEqual({state:aborted.state,finished:aborted.finished,restoredSpeed:aborted.restoredSpeed,restoredPaused:aborted.restoredPaused},{state:'aborted',finished:true,restoredSpeed:2,restoredPaused:true});const abortedRead=await control.measureRead('measure-abort','measure-abort-attempt',-1);assert.equal(abortedRead.state,'aborted');assert.equal(abortedRead.finished,true);await port.command('/silent-command game.speed=1;game.tick_paused=false;rcon.print("abort restoration checked")');pass('An acknowledged host abort terminated measurement and restored its prior speed and pause state');
  const restartSetup=await control.setup({id:'measure-restart',surface:'af-measure-restart',force:'af-measure-restart',profile:capability,area:[{x:-256,y:-256},{x:256,y:256}],maxTiles:512*512,fixtures:[{id:'source',kind:'source',position:{x:-3,y:0},product:{kind:'item',name:'iron-plate',quality:'normal'},rate:0},{id:'sink',kind:'sink',position:{x:3,y:0},product:{kind:'item',name:'iron-gear-wheel',quality:'normal'},rate:0},{id:'power',kind:'power',position:{x:0,y:5},product:{kind:'item',name:'electricity',quality:'normal'},rate:0}]});await control.materialize('measure-restart',Number(restartSetup.generation),'measure-restart-build',document);await port.command('/silent-command game.speed=2;game.tick_paused=true;rcon.print("restart reconciliation setup ready")');await control.measureConfigure({id:'measure-restart',generation:Number(restartSetup.generation),attemptId:'measure-restart-attempt',settlingTicks:600,windowTicks:600,windows:2,requestedSpeed:10,ports:[{id:'gears',fixtureId:'sink',product:{kind:'item',name:'iron-gear-wheel',quality:'normal'}}]});const fenceFile=path.join(evidence,'workshop-measurement-fence.json');await writeFile(fenceFile,JSON.stringify({schema:1,sessionId:'replacement-session',id:'measure-restart',attemptId:'measure-restart-attempt'}));assert.equal(await reconcileWorkshopMeasurementFence(evidence,control),true);await assert.rejects(()=>access(fenceFile));assert.equal((await port.command('/silent-command rcon.print(tostring(game.tick_paused)..":"..tostring(game.speed))')).trim(),'true:2');await port.command('/silent-command game.speed=1;game.tick_paused=false;rcon.print("restart reconciliation checked")');pass('Replacement startup reconciled the durable measurement fence before operator pause recovery');
  await control.setup({id:'measure-not-admitted',surface:'af-measure-not-admitted',force:'af-measure-not-admitted',profile:capability,area:[{x:-256,y:-256},{x:256,y:256}],maxTiles:512*512,fixtures:[]});await writeFile(fenceFile,JSON.stringify({schema:1,sessionId:'before-dispatch',id:'measure-not-admitted',attemptId:'never-admitted-attempt'}));assert.equal(await reconcileWorkshopMeasurementFence(evidence,control),true);await assert.rejects(()=>access(fenceFile));pass('Replacement startup cleared a pre-admission fence only after exact not-admitted status');
  const stable={settlingTicks:300,windowTicks:300,windows:5,inputStock:120};const normal=await run('measure-normal',{...stable,speed:1,initiallyPaused:true});const accelerated=await run('measure-fast',{...stable,speed:10,pause:true});assert.equal(normal.samples.length,5);assert.equal(accelerated.samples.length,5);for(const samples of [normal.samples,accelerated.samples])for(const [index,sample] of samples.entries()){assert.equal(sample.startTick+stable.windowTicks,sample.endTick);assert.equal(sample.index,index);assert.equal(sample.interval,'(startTick,endTick]');assert.equal(sample.ports[0]?.coverage,'complete');assert.equal(sample.stageCoverage,'complete');assert.equal(sample.energyCoverage,'complete');assert(integer(sample.ports[0]!.production)>0);assert(integer(sample.ports[0]!.delivery)>0);}
  const total=(samples:WorkshopWindowMeasurement[])=>samples.reduce((sum,s)=>sum+integer(s.ports[0]!.delivery),0);assert(Math.abs(total(normal.samples)-total(accelerated.samples))<=2,JSON.stringify({normal:total(normal.samples),accelerated:total(accelerated.samples)}));pass('A measurement admitted from a paused dashboard advanced exact windows and restored the prior pause');pass('Normal and accelerated dedicated-process runs produced equivalent positive exact-tick windows');assert.notEqual(accelerated.pausedTick,undefined);pass('Paused polling held the game tick and resumed the same measurement without skipping a boundary');
  const minimum=Math.min(...normal.samples.map(sample=>Math.min(integer(sample.ports[0]!.production),integer(sample.ports[0]!.delivery))));assert(minimum>0);const exact=evaluateWorkshop(assignment('threshold-pass',normal.samples,minimum,1000),normal.samples);const above=evaluateWorkshop(assignment('threshold-fail',normal.samples,minimum+1,1000),normal.samples);assert.equal(exact.passed,true);assert.equal(above.passed,false);assert(above.ports[0]!.windows.some(window=>window.reasons.includes('production_below_target')||window.reasons.includes('delivery_below_target')));pass('Game-backed integer threshold passes exactly and fails one quantum above the observed lower bound');
  const burst=await run('measure-burst',{speed:10,settlingTicks:60,windowTicks:600,windows:5,inputStock:20});const burstValues=burst.samples.map(sample=>integer(sample.ports[0]!.production));assert(burstValues.some(value=>value>0));assert.equal(burstValues.at(-1),0);const burstReport=evaluateWorkshop(assignment('burst-control',burst.samples,1,1000),burst.samples);assert.equal(burstReport.valid,true);assert.equal(burstReport.passed,false);assert(burstReport.ports[0]!.windows.some(window=>window.reasons.includes('production_below_target')));pass('Finite live input produced an early burst followed by starvation and failed the every-window predicate');
  const stock=await run('measure-stock',{speed:10,settlingTicks:60,windowTicks:600,windows:2,inputStock:0,bufferStock:100});assert(stock.samples.some(sample=>integer(sample.ports[0]!.openingStock)>integer(sample.ports[0]!.closingStock)));const stockReport=evaluateWorkshop(assignment('stock-control',stock.samples,1,0),stock.samples);assert.equal(stockReport.valid,true);assert.equal(stockReport.passed,false);assert(stockReport.ports[0]!.windows.some(window=>window.reasons.includes('stock_drawdown')));pass('Preloaded live settling stock was baselined and its drawdown could not satisfy sustained production');
  await writeFile(path.join(evidence,'normal.json'),JSON.stringify(normal,null,2));await writeFile(path.join(evidence,'accelerated.json'),JSON.stringify(accelerated,null,2));await writeFile(path.join(evidence,'controls.json'),JSON.stringify({minimum,exact,above,burst,burstReport,stock,stockReport},null,2));
}catch(error){failure=String(error);process.exitCode=1;await writeFile(path.join(evidence,'failure.txt'),failure);console.error(failure.slice(0,1500));}finally{port.close();let cleanup=false;try{await stopProfile(gameProfile.config);cleanup=true;}catch(error){failure??=String(error);process.exitCode=1;}await writeFile(path.join(evidence,'result.json'),JSON.stringify({passed:failure===null,checks,failure,cleanup,modelInference:false},null,2));console.log(JSON.stringify({evidence,checks:checks.length,failure:failure?.slice(0,300),cleanup}));}
