import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { BlueprintDocument } from '@autofactorio/contracts';
import { exportBlueprint, exportBlueprintBook } from '../packages/core/workshop/blueprint.js';
import { createProfile, startServer, stopProfile, waitForServer } from './dev/game-processes.js';

const profile=await createProfile(false,true),evidence=await mkdtemp(path.join(profile.dir,'native-blueprint-probe-'));let failure:string|null=null;let cleanup=false;const checks:string[]=[];const document:BlueprintDocument={schema:1,label:'Native chests',description:'No-mod native import proof',entities:[{id:'a',entityNumber:1,name:'steel-chest',position:{x:0,y:0},direction:0,quality:'normal'},{id:'b',entityNumber:2,name:'steel-chest',position:{x:2,y:0},direction:0,quality:'normal'},{id:'c',entityNumber:3,name:'steel-chest',position:{x:4,y:0},direction:0,quality:'normal'}],wires:[],ports:[],icons:[{index:1,name:'steel-chest'}],tiles:[]};const blueprint=exportBlueprint(document),book=exportBlueprintBook('Native workshop book',[document,{...document,label:'Second cell'}]);
try{const list=JSON.parse(await readFile(path.join(profile.mods,'mod-list.json'),'utf8')) as {mods:{name:string;enabled:boolean}[]};for(const mod of list.mods)if(mod.name==='autofactorio')mod.enabled=false;await writeFile(path.join(profile.mods,'mod-list.json'),JSON.stringify(list));await startServer(profile);const port=await waitForServer(profile);try{await port.command('/silent-command rcon.print("native blueprint authorization")');await port.command('/silent-command rcon.print("native blueprint ready")');const lua=`local inv=game.create_inventory(2);local a=inv[1].import_stack(${JSON.stringify(blueprint)});local b=inv[2].import_stack(${JSON.stringify(book)});local entities=inv[1].get_blueprint_entities();local bi=inv[2].get_inventory(defines.inventory.item_main);rcon.print(helpers.table_to_json({blueprint=a,book=b,entityCount=entities and #entities or 0,bookCount=bi and #bi or 0,modAbsent=remote.interfaces.autofactorio==nil,roundtrip=inv[1].export_stack()}));inv.destroy()`;const result=JSON.parse(await port.command('/silent-command '+lua)) as {blueprint:number;book:number;entityCount:number;bookCount:number;modAbsent:boolean;roundtrip:string};assert.equal(result.blueprint,0);assert.equal(result.book,0);assert.equal(result.entityCount,3);assert.equal(result.bookCount,2);assert.equal(result.modAbsent,true);assert.match(result.roundtrip,/^0/);checks.push('Factorio without AutoFactorio imported and re-exported the native blueprint and two-entry book');await writeFile(path.join(evidence,'native-result.json'),JSON.stringify(result,null,2));}finally{port.close();}}
catch(error){failure=String(error);process.exitCode=1;await writeFile(path.join(evidence,'failure.txt'),failure);console.error(failure.slice(0,1500));}
finally{try{await stopProfile(profile.config);cleanup=true;}catch(error){failure??=String(error);process.exitCode=1;}await writeFile(path.join(evidence,'result.json'),JSON.stringify({passed:failure===null,checks,failure,cleanup,modelInference:false},null,2));console.log(JSON.stringify({evidence,checks:checks.length,failure:failure?.slice(0,300),cleanup}));}
