import assert from 'node:assert/strict';
import { mkdtemp, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { BlueprintDocument } from '@autofactorio/contracts';
import type { CapabilityProfile } from '../packages/core/workshop/profiles.js';
import { WorkshopControl } from '../packages/factorio/src/workshop.js';
import { createProfile, startServer, stopProfile, waitForServer } from './dev/game-processes.js';

const gameProfile=await createProfile(false,true),evidence=await mkdtemp(path.join(gameProfile.dir,'workshop-spaceage-probe-'));const checks:string[]=[];let failure:string|null=null,cleanup=false;console.log(JSON.stringify({evidence,profile:gameProfile.config}));await startServer(gameProfile);const port=await waitForServer(gameProfile);await port.command('/silent-command rcon.print("space age workshop authorization")');await port.command('/silent-command rcon.print("space age workshop ready")');const control=new WorkshopControl(port);
const capability:CapabilityProfile={schema:1,id:'space-age-machines',revision:1,fingerprint:'live-2.0.77-space-age',source:'custom',technologies:['oil-processing','advanced-oil-processing'],researchBonuses:{},recipes:['advanced-oil-processing'],allowedEquipment:['electromagnetic-plant','foundry','beacon','speed-module-3','productivity-module-3','substation','oil-refinery','pipe','pump','storage-tank'],locallyManufacturable:[],modules:['speed-module-3','productivity-module-3'],beacons:['beacon'],quality:'normal',surface:'custom',surfaceProperties:{'magnetic-field':1200,pressure:4000,gravity:40,'solar-power':100}};
const document:BlueprintDocument={schema:1,label:'Space Age and fluid machines',description:'EM/foundry/module/beacon plus deterministic fluid/byproduct configuration proof',entities:[{id:'em',entityNumber:1,name:'electromagnetic-plant',position:{x:-12,y:0},direction:0,quality:'normal',modules:{'speed-module-3':2}},{id:'foundry',entityNumber:2,name:'foundry',position:{x:0,y:0},direction:0,quality:'normal',modules:{'productivity-module-3':2}},{id:'beacon',entityNumber:3,name:'beacon',position:{x:10,y:0},direction:0,quality:'normal',modules:{'speed-module-3':2}},{id:'power',entityNumber:4,name:'substation',position:{x:5,y:5},direction:0,quality:'normal'},{id:'refinery',entityNumber:5,name:'oil-refinery',position:{x:0,y:16},direction:0,quality:'normal',recipe:'advanced-oil-processing'},{id:'pipe',entityNumber:6,name:'pipe',position:{x:5,y:16},direction:0,quality:'normal'},{id:'pump',entityNumber:7,name:'pump',position:{x:7,y:16},direction:4,quality:'normal'},{id:'tank',entityNumber:8,name:'storage-tank',position:{x:10,y:16},direction:0,quality:'normal'}],wires:[],ports:[{id:'crude',direction:'input',product:{kind:'fluid',name:'crude-oil',quality:'normal',surface:'af-workshop-space-age'},position:{x:-4,y:16},facing:4,transport:'pipe',rate:{numerator:'100',denominator:'1'},unit:'units-per-game-second',required:true},{id:'heavy',direction:'byproduct',product:{kind:'fluid',name:'heavy-oil',quality:'normal',surface:'af-workshop-space-age'},position:{x:4,y:14},facing:12,transport:'pipe',rate:{numerator:'1',denominator:'1'},unit:'units-per-game-second',required:true},{id:'light',direction:'output',product:{kind:'fluid',name:'light-oil',quality:'normal',surface:'af-workshop-space-age'},position:{x:4,y:16},facing:12,transport:'pipe',rate:{numerator:'1',denominator:'1'},unit:'units-per-game-second',required:true},{id:'petroleum',direction:'byproduct',product:{kind:'fluid',name:'petroleum-gas',quality:'normal',surface:'af-workshop-space-age'},position:{x:4,y:18},facing:12,transport:'pipe',rate:{numerator:'1',denominator:'1'},unit:'units-per-game-second',required:true}],icons:[{index:1,name:'electromagnetic-plant'}],tiles:[]};
try{const setup=await control.setup({id:'space-age',surface:'af-workshop-space-age',force:'af-workshop-space-age',profile:capability,area:[{x:-256,y:-256},{x:256,y:256}],maxTiles:512*512,fixtures:[]});await control.materialize('space-age',Number(setup.generation),'space-age-build',document);const result=JSON.parse(await port.command('/silent-command local s=game.surfaces["af-workshop-space-age"];local em=s.find_entity("electromagnetic-plant",{-12,0});local f=s.find_entity("foundry",{0,0});local b=s.find_entity("beacon",{10,0});local refinery=s.find_entity("oil-refinery",{0,16});local recipe=refinery and refinery.get_recipe();rcon.print(helpers.table_to_json({magnetic=s.get_property("magnetic-field"),pressure=s.get_property("pressure"),em=em and em.get_module_inventory().get_item_count("speed-module-3") or -1,foundry=f and f.get_module_inventory().get_item_count("productivity-module-3") or -1,beacon=b and b.get_module_inventory().get_item_count("speed-module-3") or -1,recipe=recipe and recipe.name or "none",fluidboxes=refinery and #refinery.fluidbox or -1}))')) as {magnetic:number;pressure:number;em:number;foundry:number;beacon:number;recipe:string;fluidboxes:number};assert.deepEqual({...result,recipe:undefined,fluidboxes:undefined},{magnetic:1200,pressure:4000,em:2,foundry:2,beacon:2,recipe:undefined,fluidboxes:undefined});assert.equal(result.recipe,'advanced-oil-processing');assert(result.fluidboxes>=5);checks.push('Surface properties admitted EM and foundry placement with pinned module and beacon configuration');checks.push('Direct reconstruction retained a deterministic multi-fluid recipe, explicit byproduct ports, pipe, pump and tank content');await writeFile(path.join(evidence,'space-age.json'),JSON.stringify({setup,result,ports:document.ports},null,2));}
catch(error){failure=String(error);process.exitCode=1;await writeFile(path.join(evidence,'failure.txt'),failure);console.error(failure.slice(0,1500));}
finally{port.close();try{await stopProfile(gameProfile.config);cleanup=true;}catch(error){failure??=String(error);process.exitCode=1;}await writeFile(path.join(evidence,'result.json'),JSON.stringify({passed:failure===null,checks,failure,cleanup,modelInference:false},null,2));console.log(JSON.stringify({evidence,checks:checks.length,failure:failure?.slice(0,300),cleanup}));}
