import assert from 'node:assert/strict';
import { mkdtemp, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import type { Assignment, BlueprintDocument, Receipt as GameReceipt } from '@autofactorio/contracts';
import { compileCharacterBlueprint, constructionBatches } from '../packages/core/workshop/construction.js';
import { GameClient } from '../packages/factorio/src/client.js';
import { Lifecycle, barrier } from '../packages/factorio/src/lifecycle.js';
import { WorkshopControl } from '../packages/factorio/src/workshop.js';
import type { CapabilityProfile } from '../packages/core/workshop/profiles.js';
import { createProfile, identifyObserver, startObserver, startServer, stopProfile, waitFor, waitForServer } from './dev/game-processes.js';
type Receipt=GameReceipt|null;
const record=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};

const profile=await createProfile(false,false),evidence=await mkdtemp(path.join(profile.dir,'workshop-character-probe-'));let failure:string|null=null,cleanup=false;const checks:string[]=[];console.log(JSON.stringify({evidence,profile:profile.config}));await startServer(profile);const port=await waitForServer(profile);let observer=false;const events:unknown[]=[];const game=new GameClient(port,event=>events.push(event));const life=new Lifecycle(port,game,event=>events.push(event));
const document:BlueprintDocument={schema:1,label:'Reusable character cell',description:'Finite-inventory legal build',entities:[{id:'input',entityNumber:1,name:'wooden-chest',position:{x:-3.5,y:3.5},direction:0,quality:'normal',inventoryBar:8},{id:'assembler',entityNumber:2,name:'assembling-machine-1',position:{x:0.5,y:3.5},direction:0,quality:'normal',recipe:'iron-gear-wheel'},{id:'output',entityNumber:3,name:'wooden-chest',position:{x:4.5,y:3.5},direction:0,quality:'normal'}],wires:[],ports:[],icons:[{index:1,name:'iron-gear-wheel'}],tiles:[]};
const capability:CapabilityProfile={schema:1,id:'character-live',revision:1,fingerprint:'character-live-2.0.77',source:'custom',technologies:['automation','logistics'],researchBonuses:{},recipes:['iron-gear-wheel'],allowedEquipment:['wooden-chest','assembling-machine-1'],locallyManufacturable:[],modules:[],beacons:[],quality:'normal',surface:'nauvis'};
const count=(inventory:unknown,name:string)=>(inventory as {name:string;count:number}[]).find(v=>v.name===name)?.count??0;
try{await port.command('/silent-command rcon.print("character workshop authorization")');await port.command('/silent-command rcon.print("character workshop ready")');await startObserver(profile);observer=true;await identifyObserver(profile);const workshop=new WorkshopControl(port);await waitFor('workshop builder',async()=>{const value=await game.request({op:'observe',surface:'nauvis',area:[{x:-32,y:-32},{x:32,y:32}],offset:0,limit:50});const actor=record(record(value.actors)['builder-1']);return actor.connected===true?value:undefined;},60000,200);const setup=await workshop.setup({id:'character-live',surface:'af-character-live',force:'af-character-live',profile:capability,area:[{x:-256,y:-256},{x:256,y:256}],maxTiles:512*512,fixtures:[]});await workshop.enter('character-live','builder-1');const beforeFailed=record(await workshop.actor('character-live','builder-1'));await assert.rejects(workshop.provision('character-live','builder-1','character-live-provision',[{name:'assembling-machine-1',quality:'normal',count:1},{name:'wooden-chest',quality:'normal',count:10000}]),/provision_inventory_full/);const afterFailed=record(await workshop.actor('character-live','builder-1'));assert.deepEqual(afterFailed.inventory,beforeFailed.inventory);const provision=await workshop.provision('character-live','builder-1','character-live-provision',[{name:'assembling-machine-1',quality:'normal',count:1},{name:'wooden-chest',quality:'normal',count:2}]),actor=record(await workshop.actor('character-live','builder-1')),inventory=Object.fromEntries((actor.inventory as {name:string;count:number}[]).map(v=>[v.name,v.count]));let control=await life.inspect();if(control.armed||!control.paused||!control.neutral)control=await life.pause(control);const generation=control.generation+1,assignment:Assignment={id:'character-workshop',owner:'workshop-runtime',task:'workshop-build',revision:1,actor:'builder-1',resources:[{grant:{id:'character-area',generation},resource:{kind:'area',surface:'af-character-live',bounds:[{x:-256,y:-256},{x:256,y:256}]}},{grant:{id:'character-items',generation},resource:{kind:'items',actor:'builder-1'}},{grant:{id:'character-actor',generation},resource:{kind:'actor',actor:'builder-1'}}]};control=await life.reconcile(control,[assignment]);control=await life.arm(control);const plan=compileCharacterBlueprint(document,inventory,()=>true);const beforeAssembler=count(actor.inventory,'assembling-machine-1'),beforeChest=count(actor.inventory,'wooden-chest');const batches=constructionBatches(plan,{commandPrefix:'workshop-character',epoch:control.epoch,session:control.session,task:assignment.task,revision:assignment.revision,actor:'builder-1',surface:'af-character-live',grants:assignment.resources.map(value=>value.grant),deadline:control.tick+36000},100);
  for(const batch of batches){await game.request({op:'submit',batch});let receipt:Receipt|undefined;for(let i=0;i<600;i++){control=await life.heartbeat(control);receipt=await game.receipt(batch.commandId);if(receipt&&!['accepted','running'].includes(receipt.status))break;await delay(25);}assert.equal(receipt?.status,'completed');}
  control=await life.pause(control);barrier(control);const afterActor=record(await workshop.actor('character-live','builder-1')),inspection=record(await workshop.inspect('character-live'));assert.equal(beforeAssembler-count(afterActor.inventory,'assembling-machine-1'),1);assert.equal(beforeChest-count(afterActor.inventory,'wooden-chest'),2);const built=inspection.entities as Record<string,unknown>[];assert.equal(built.filter(e=>['assembling-machine-1','wooden-chest'].includes(String(e.name))&&Number(record(e.position).y)>2).length,3);assert.equal(String(inspection.profileFingerprint),capability.fingerprint);checks.push('Failed multi-item provisioning rolled back every inserted delta and the same operation id then succeeded with an exact finite inventory');checks.push('Ordinary character executor entered an isolated workshop, consumed only provisioned finite inventory, and rebuilt recipe and inventory-bar settings under workshop-surface ownership');await writeFile(path.join(evidence,'character-result.json'),JSON.stringify({setup,beforeFailed,afterFailed,provision,plan,batches,afterActor,inspection,events},null,2));}
catch(error){failure=String(error);process.exitCode=1;await writeFile(path.join(evidence,'failure.txt'),failure);console.error(failure.slice(0,1500));}
finally{port.close();try{if(observer)await stopProfile(profile.observerConfig);await stopProfile(profile.config);cleanup=true;}catch(error){failure??=String(error);process.exitCode=1;}await writeFile(path.join(evidence,'result.json'),JSON.stringify({passed:failure===null,checks,failure,cleanup,modelInference:false},null,2));console.log(JSON.stringify({evidence,checks:checks.length,failure:failure?.slice(0,300),cleanup}));}
