import assert from 'node:assert/strict';
import { mkdtemp, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { prepareLiveWorkshopHost } from '../apps/runtime/workshop-live-host.js';
import { composeWorkshop } from '../apps/runtime/workshop-composition.js';
import { SqliteJournal } from '../packages/storage/src/journal.js';
import { GameClient } from '../packages/factorio/src/client.js';
import { Lifecycle } from '../packages/factorio/src/lifecycle.js';
import { createProfile, startServer, stopProfile, waitForServer } from './dev/game-processes.js';

const value=(name:string)=>{const index=process.argv.indexOf(name);return index<0?undefined:process.argv[index+1];};
const executable=value('--codex');if(!process.argv.includes('--live')||!executable||!path.isAbsolute(executable))throw new Error('Usage: workshop-live-composition-probe --live --codex <absolute managed Codex executable>');
const profile=await createProfile(false,true),evidence=await mkdtemp(path.join(profile.dir,'workshop-live-composition-'));let failure:string|null=null,cleanup=false;console.log(JSON.stringify({evidence,profile:profile.config}));await startServer(profile);const port=await waitForServer(profile),events:unknown[]=[];const game=new GameClient(port,event=>events.push(event)),life=new Lifecycle(port,game,event=>events.push(event));const journal=new SqliteJournal(path.join(evidence,'runtime.sqlite')),context=()=>({run:'live-composition',epoch:'live-composition',wallTime:new Date().toISOString(),gameTick:null,actor:'operator',task:null,causation:null,correlation:null,visibility:{kind:'operator'} as const});let composition:ReturnType<typeof composeWorkshop>|undefined,runtime:NonNullable<ReturnType<typeof composeWorkshop>['controller']>|undefined;
try{
  await port.command('/silent-command rcon.print("live workshop composition authorization")');await port.command('/silent-command rcon.print("live workshop composition ready")');const prepared=await prepareLiveWorkshopHost({directory:evidence,codexExecutable:executable,port,game,lifecycle:life});const available=prepared.catalog.models.flatMap(model=>model.efforts.map(reasoningEffort=>({provider:'openai',modelId:model.id,reasoningEffort})));assert(available.some(selection=>selection.modelId==='gpt-6-astra'&&selection.reasoningEffort==='low'));
  const store={directory:evidence,run:'live-composition',journal,context,record(type:string,changes:Parameters<SqliteJournal['append']>[2]){journal.append(context(),type,changes);}};composition=composeWorkshop(store as never,{workshopHost:prepared.host,managedModels:prepared.catalog.models,workshopBundleHash:'baseline'});runtime=composition.controller??undefined;if(!runtime)throw new Error('Production workshop composition did not create a controller');const orchestrator=composition.orchestrator,input={schema:1,id:'live-composition',revision:1,comparisonSeries:'live-composition-series',objective:'Produce 1 electronic circuit per minute',source:{kind:'brief',id:null},profileId:'starter-assembly',construction:'direct',libraryAccess:false,improveRevision:null,requestedSpeed:{numerator:'10',denominator:'1'},settlingTicks:0,windowTicks:60,windows:1,rubric:{version:'rubric-1',weights:{throughput:{numerator:'1',denominator:'1'}},materiality:{throughput:{numerator:'0',denominator:'1'}},directions:{throughput:'maximize'}},iterations:{attempts:1,mode:'exact',earlyStop:false,plateauRounds:1},checkpoints:{brief:false,afterScore:false,libraryAdmission:false,learningActivation:false,timeoutMs:60000,timeoutAction:'finish'},budgets:{wallMs:180000,gameTicks:600,turns:3,toolCalls:8,reportedTokens:60000,learningReservedTurns:0,learningReservedTools:0},models:{sessionDefault:{provider:'openai',modelId:'gpt-6-astra',reasoningEffort:'low'},overrides:{}},learning:{cadence:'off',batchSessions:1,candidateCap:1,attemptsPerCandidate:1,autoActivate:false}};await runtime.launch(input);const deadline=Date.now()+240000;for(;;){const session=orchestrator.get('live-composition');if(session.stage==='complete'){assert.equal(session.iterations.length,1);assert(session.iterations[0]?.artifact);assert(session.iterations[0]?.evaluation);assert(session.iterations[0]?.score);await writeFile(path.join(evidence,'report.json'),JSON.stringify({schema:1,passed:true,catalog:prepared.catalog,session,events:events.length,providerEvents:path.join(evidence,'workshop-provider-events.jsonl')},null,2));console.log(JSON.stringify({evidence,stage:session.stage,outcome:session.finalOutcome,valid:session.iterations[0]!.valid}));break;}if(session.stage==='stopped')throw new Error(session.stopReason??'Workshop stopped');if(Date.now()>deadline)throw new Error(`Live composition timeout at ${session.stage}`);await new Promise(resolve=>setTimeout(resolve,100));}
}catch(error){failure=String(error);process.exitCode=1;await writeFile(path.join(evidence,'report.json'),JSON.stringify({schema:1,passed:false,failure,events},null,2));console.error(failure.slice(0,1500));}
finally{await runtime?.close();composition?.library.close();journal.close();port.close();try{await stopProfile(profile.config);cleanup=true;}catch(error){failure??=String(error);process.exitCode=1;}await writeFile(path.join(evidence,'cleanup.json'),JSON.stringify({cleanup,failure},null,2));console.log(JSON.stringify({evidence,cleanup,failure:failure?.slice(0,300)}));}
