import { appendFileSync } from 'node:fs';
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { performance } from 'node:perf_hooks';
import { Budget, PROBE_CAPS } from '../packages/codex/src/budget.js';
import { AppServerRpc } from '../packages/codex/src/rpc.js';
import { Provider } from '../packages/codex/src/provider.js';
import { managedCatalog, profileOverrides, requireManagedSelection } from '../packages/codex/src/preflight.js';
import { object } from '../packages/codex/src/protocol.js';
import type { Activity, Sink } from '../packages/codex/src/protocol.js';
import { Gateway } from '../packages/tools/src/gateway.js';
import type { Role } from '../packages/tools/src/gateway.js';
import type { ModelSelection } from '@autofactorio/contracts';
import { SqliteJournal } from '../packages/storage/src/journal.js';
import { LearningService } from '../packages/core/workshop/learning.js';
import { HelperQuota, invokeConfinedHelper } from '../packages/core/workshop/helper-worker.js';

const arg=(name:string)=>{const index=process.argv.indexOf(name);return index<0?undefined:process.argv[index+1];};
const executableArg=arg('--codex');if(!process.argv.includes('--live')||!executableArg||!path.isAbsolute(executableArg))throw new Error('Usage: workshop-provider-exercise --live --codex <absolute managed Codex executable>');const executable:string=executableArg;
const selection:ModelSelection={provider:'openai',modelId:arg('--model')??'gpt-6-astra',reasoningEffort:arg('--effort')??'low'};
const root=path.resolve('.runtime/phase17');await mkdir(root,{recursive:true});const evidence=await mkdtemp(path.join(root,'provider-workshop-'));const events:Activity[]=[];const sink:Sink=event=>{events.push(event);appendFileSync(path.join(evidence,'events.jsonl'),JSON.stringify(event)+'\n');if(['provider/ready','turn/submitted','turn/completed','steer/acknowledged','tool/attempt'].includes(event.kind))console.log(JSON.stringify(event));};
const learningJournal=new SqliteJournal(path.join(evidence,'learning.sqlite'));const learningContext=()=>({run:'managed-workshop-exercise',epoch:'provider-exercise',wallTime:new Date().toISOString(),gameTick:null,actor:'workshop-learnings',task:'managed-workshop-exercise',causation:null,correlation:null,visibility:{kind:'operator'} as const});const learning=new LearningService(learningJournal,learningContext);
const caps={...PROBE_CAPS,turns:12,tools:40,tokens:250000,runMs:20*60_000,turnMs:90_000};const controls:Promise<void>[]=[];const active=new Map<string,Provider>();const budget=new Budget(caps,()=>performance.now(),turn=>{gateway.revokeTurn(turn.id);const provider=active.get(turn.id);if(provider)controls.push(provider.interrupt());});const gateway=new Gateway(budget,sink);const server=await gateway.listen();const bootstrap=new AppServerRpc(executable,evidence,{forced_login_method:'chatgpt',model_provider:'openai','features.apps':false,'features.plugins':false});
const assignment={schema:1,id:'managed-workshop-exercise',comparisonSeries:'fixed-series',objective:'Choose a supported circuit-cell plan and state one measurable distinction.',profile:'starter-assembly',construction:'direct',ports:['iron-plate input','copper-cable input','electronic-circuit output 60/min'],attempts:{count:5,mode:'exact',earlyStop:false},rubric:'fixed-r1',budgets:caps,selection,checkpoints:{brief:false,afterScore:false,libraryAdmission:false,learningActivation:false}};
const manifest={schema:1,createdAt:new Date().toISOString(),codexExecutable:executable,assignment,experiments:['five-unattended-attempts','separate-human-checkpoint','learning-no-change','deterministic-helper-improvement','fresh-session-consumption'],inferenceStarted:false};await writeFile(path.join(evidence,'manifest.json'),JSON.stringify(manifest,null,2));
let mcpNames:string[]=[];let failed:string|null=null;const results:{attempts:string[];checkpoint:string|null;noChange:string|null;review:string|null;fresh:string|null;helper:{incumbent:number;candidate:number;control:number;activated:boolean;bundleHash:string|null;pinnedSession:string|null;invocation:unknown}}={attempts:[],checkpoint:null,noChange:null,review:null,fresh:null,helper:{incumbent:Math.round(60.1),candidate:0,control:0,activated:false,bundleHash:null,pinnedSession:null,invocation:null}};
const wait=async(predicate:()=>boolean,timeout=95_000)=>{const deadline=performance.now()+timeout;while(!predicate()){if(performance.now()>deadline||budget.state.closed)throw new Error(`Managed exercise wait failed: ${budget.state.reason??'timeout'}`);await new Promise(resolve=>setTimeout(resolve,50));}};
try{
  await bootstrap.call('initialize',{clientInfo:{name:'autofactorio_workshop_exercise',version:'0.1.0'},capabilities:{experimentalApi:true}});const catalog=await managedCatalog(bootstrap);requireManagedSelection(catalog,selection);const config=object(object(await bootstrap.call('config/read',{cwd:evidence})).config);mcpNames=Object.keys(object(config.mcp_servers??{}));bootstrap.close();
  async function turn(role:Extract<Role,`workshop-${string}`>,prompt:string,instructions:string,beforeStart?:(session:string)=>Promise<void>):Promise<{read:()=>string;provider:Provider;close:()=>void}>{const directory=await mkdtemp(path.join(evidence,`${role}-`));const token=gateway.issue(role);const overrides=profileOverrides(mcpNames,path.join(directory,'logs'),selection);overrides['mcp_servers.autofactorio.url']=server.url;overrides['mcp_servers.autofactorio.http_headers.Authorization']=`Bearer ${token}`;overrides['mcp_servers.autofactorio.enabled']=true;overrides['mcp_servers.autofactorio.default_tools_approval_mode']='approve';const rpc=new AppServerRpc(executable,directory,overrides);let text='';const local:Sink=event=>{sink(event);if(event.kind==='item/agentMessage/delta'){const data=event.data as Record<string,unknown>;if(typeof data.delta==='string')text+=data.delta;}};const provider=new Provider(role,rpc,budget,local,()=>gateway.revoke(token),async()=>{gateway.revoke(token);return true;},selection);await provider.initialize();await provider.sessionStart(directory,undefined,instructions);if(!provider.session)throw new Error('Managed provider session missing');await beforeStart?.(provider.session);const expected=(role==='workshop-designer'?['observe','checkpoint']:['observe']).map(name=>`autofactorio:${name}`);await provider.catalog(expected);await provider.start(prompt,id=>{gateway.bind(token,id);active.set(id,provider);});return{read:()=>text,provider,close:()=>{if(provider.turn)active.delete(provider.turn.id);provider.close();}};}
  manifest.inferenceStarted=true;await writeFile(path.join(evidence,'manifest.json'),JSON.stringify(manifest,null,2));
  for(let attempt=1;attempt<=5;attempt++){const run=await turn('workshop-designer',`Attempt ${attempt} of exactly 5. ${assignment.objective} Return a concise plan tagged ATTEMPT_${attempt}. Do not stop the series early.`,`You are the library-independent workshop designer. The fixed assignment is ${JSON.stringify(assignment)}. You may only observe synthetic public state; do not claim game measurements.`);await wait(()=>run.provider.turn?.finished===true);results.attempts.push(run.read());run.close();}
  const checkpoint=await turn('workshop-designer','Call checkpoint immediately. After operator steering arrives and the checkpoint returns, acknowledge the steering with CHECKPOINT_ACK.','This is a separate assisted workshop flow. Call the checkpoint tool once and wait for operator steering.');await wait(()=>gateway.attempts.some(v=>v.role==='workshop-designer'&&v.tool==='checkpoint'&&v.allowed));await checkpoint.provider.steer('Operator feedback: keep the output port on the east edge and label this run assisted.');await wait(()=>checkpoint.provider.turn?.finished===true);results.checkpoint=checkpoint.read();checkpoint.close();
  const noChange=await turn('workshop-learnings','The five attempts have valid bounded plans and no repeated unsupported error. Decide whether a permanent instruction/tool change is warranted. Reply with NO_CHANGE and a reason when none is warranted.','You are the scoped learnings role. Prefer existing deterministic guards and no-change over invented prompt growth. You cannot activate changes.');await wait(()=>noChange.provider.turn?.finished===true);results.noChange=noChange.read();noChange.close();
  const bundleRoot=path.join(evidence,'candidate-bundle'),scratch=path.join(evidence,'helper-scratch');await mkdir(bundleRoot);await mkdir(scratch);const helperSource='input=>({revision:input.revision,required:Math.ceil(input.rate*input.seconds/input.quantum)*input.quantum,fs:typeof require==="undefined"?"denied":"allowed",network:typeof fetch==="undefined"?"denied":"allowed",child:typeof process==="undefined"?"denied":"allowed"})';const helperFile=path.join(bundleRoot,'design-helper.mjs');await writeFile(helperFile,helperSource);const helperHash=createHash('sha256').update(helperSource).digest('hex');const candidate=learning.candidate({id:'quantized-threshold-helper',batchId:'managed-exercise',scope:'design-helper',content:helperSource,evidence:['fractional-threshold-regression'],contextLineage:['managed-workshop-exercise'],libraryIndependent:true});learning.attempt(candidate.id);learning.decide(candidate.id,'accept','Exact quantum ceiling corrects the fractional threshold without changing integer controls',null);const bundle=learning.assemble({incumbentHash:'baseline',expectedGeneration:0,files:{'design-helper.mjs':helperSource},requiredControls:['confinement','fractional-threshold','integer-control'],policyHash:'provider-exercise-policy-v1',retrievalHash:'none',catalogHash:'managed-catalog',candidates:[candidate.id]});results.helper.bundleHash=bundle.hash;const helperPolicy={wallMs:5000,inputBytes:2048,outputBytes:4096,scratchBytes:4096,invocations:3,policyHash:'provider-exercise-policy-v1'},quota=new HelperQuota(helperPolicy);const fractional=await invokeConfinedHelper({worker:path.resolve('scripts/workshop-helper-worker.mjs'),bundleRoot,helper:helperFile,expectedHash:helperHash,scratch,value:{revision:1,rate:60.1,seconds:1,quantum:1},policy:helperPolicy,quota}) as Record<string,unknown>;const integer=await invokeConfinedHelper({worker:path.resolve('scripts/workshop-helper-worker.mjs'),bundleRoot,helper:helperFile,expectedHash:helperHash,scratch,value:{revision:1,rate:60,seconds:1,quantum:1},policy:helperPolicy,quota}) as Record<string,unknown>;results.helper.candidate=Number(fractional.required);results.helper.control=Number(integer.required);
  const review=await turn('workshop-learnings',`Fresh read-only review. Incumbent helper rounds 60.1 to ${results.helper.incumbent}; the confined exact-bundle candidate returned ${results.helper.candidate}; the exact-60 control returned ${results.helper.control}; forbidden host capabilities reported ${fractional.fs}/${fractional.network}/${fractional.child}. State APPROVE only if the candidate fixes the regression, preserves the control and remains confined.`,`You are an independent learning reviewer in a fresh read-only managed context. Review supplied evidence only; you have no activation or filesystem authority.`);await wait(()=>review.provider.turn?.finished===true);results.review=review.read();review.close();const controls=['confinement','fractional-threshold','integer-control'];const attest=(kind:'deterministic'|'interaction'|'behavior'|'review',passed:boolean,evidenceRows:string[])=>learning.attest(bundle.hash,{kind,bundleHash:bundle.hash,incumbentHash:'baseline',generation:0,controlSuite:'provider-exercise-controls-v1',controls,environment:`node-${process.version}`,passed,conclusive:true,evidence:evidenceRows});attest('deterministic',results.helper.candidate===61&&results.helper.control===60,['confined-helper:fractional=61','confined-helper:integer=60']);attest('interaction',fractional.fs==='denied'&&fractional.network==='denied'&&fractional.child==='denied',['confined-helper:host-capabilities-denied']);attest('behavior',results.helper.incumbent===60&&results.helper.candidate===61&&results.helper.control===60,['incumbent-regression','candidate-correction','unchanged-control']);attest('review',/approve/i.test(results.review),['managed-independent-review']);const activated=learning.activate(bundle.hash,'managed-exercise-activation');results.helper.activated=activated.activeHash===bundle.hash;
  if(!results.helper.activated)throw new Error('Evidence-backed helper candidate did not pass independent managed review');
  const fresh=await turn('workshop-designer','Call observe once. Read the activatedHelper result from observed state, return FRESH_USES_<required>, and explain the threshold in one sentence. Do not recompute it or accept a value from this prompt.','You are a fresh workshop designer session. Consume only the helper output pinned and exposed by the trusted runtime observation.',async session=>{const pin=learning.pin(session);if(pin.hash!==bundle.hash)throw new Error('Fresh session did not pin activated bundle');results.helper.pinnedSession=session;const invocation=await invokeConfinedHelper({worker:path.resolve('scripts/workshop-helper-worker.mjs'),bundleRoot,helper:helperFile,expectedHash:helperHash,scratch,value:{revision:2,rate:60.1,seconds:1,quantum:1},policy:helperPolicy,quota});results.helper.invocation=invocation;gateway.setObservation('workshop-designer',{activation:{generation:pin.generation,bundleHash:pin.hash},activatedHelper:invocation});});await wait(()=>fresh.provider.turn?.finished===true);results.fresh=fresh.read();fresh.close();
  if(results.attempts.length!==5||results.attempts.some((v,i)=>!v.includes(`ATTEMPT_${i+1}`)))throw new Error('Five exact managed attempts were not demonstrated');if(!/checkpoint_ack/i.test(results.checkpoint??''))throw new Error('Managed checkpoint acknowledgement missing');if(!/no_change/i.test(results.noChange??''))throw new Error('Managed no-change decision missing');if(!new RegExp(`FRESH_USES_${results.helper.candidate}`,'i').test(results.fresh??''))throw new Error('Fresh session did not consume activated helper result');
}catch(error){failed=String(error);process.exitCode=1;}finally{if(failed)budget.closeRun('workshop_exercise_failed');await Promise.allSettled(controls);for(const provider of active.values())provider.close();bootstrap.close();await server.close();learningJournal.close();const report={schema:1,failed,manifest,results,budget:budget.snapshot(),usageReported:Object.keys(budget.state.usageBySession).length?budget.state.reportedTokens:null,permissions:{'workshop-designer':['observe','checkpoint'],'workshop-scorer':['observe'],'workshop-learnings':['observe']},gatewayAttempts:gateway.attempts,interference:'Dedicated synthetic MCP and fresh provider processes; no Factorio mutation.',events:events.length};await writeFile(path.join(evidence,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({evidence,failed,spentTurns:budget.state.spentTurns,reportedTokens:report.usageReported}));}
