import type { Batch, BlueprintDocument, BlueprintEntity, Grant, Position, Step, Target } from '@autofactorio/contracts';
import { billOfMaterials, normalizeBlueprint } from './blueprint.js';

export interface ConstructionPlan { document:BlueprintDocument; footprint:[Position,Position]; approach:[Position,Position]; steps:Step[]; required:Record<string,number> }
const distance=(a:Position,b:Position)=>Math.hypot(a.x-b.x,a.y-b.y);
const target=(entity:BlueprintEntity):Target=>({name:entity.name,quality:'normal',position:entity.position,unit:null});
export function compileCharacterBlueprint(input:BlueprintDocument,inventory:Record<string,number>,canStand:(position:Position)=>boolean,undergroundReach:(name:string)=>number=(name=>name==='turbo-underground-belt'?11:name==='express-underground-belt'?9:name==='fast-underground-belt'?7:5)):ConstructionPlan{
  const document=normalizeBlueprint(input);const required=billOfMaterials(document);for(const[name,count]of Object.entries(required))if((inventory[name]??0)<count)throw new Error(`Insufficient material: ${name}`);
  const underground=document.entities.filter(e=>e.undergroundType!==undefined);for(const entity of underground){const reach=undergroundReach(entity.name),vector=[{x:0,y:-1},{x:1,y:0},{x:0,y:1},{x:-1,y:0}][entity.direction/4];if(!vector)throw new Error(`Underground belt direction must be cardinal: ${entity.id}`);const partner=underground.find(other=>{if(other===entity||other.name!==entity.name||other.direction!==entity.direction||other.undergroundType===entity.undergroundType)return false;const dx=other.position.x-entity.position.x,dy=other.position.y-entity.position.y,along=dx*vector.x+dy*vector.y,cross=dx*vector.y-dy*vector.x;return cross===0&&along!==0&&Math.abs(along)<=reach+1;});if(!partner)throw new Error(`Unconnected underground belt: ${entity.id}`);}
  const xs=document.entities.map(e=>e.position.x),ys=document.entities.map(e=>e.position.y);const footprint:[Position,Position]=[{x:Math.min(...xs)-1,y:Math.min(...ys)-1},{x:Math.max(...xs)+1,y:Math.max(...ys)+1}];const approach:[Position,Position]=[{x:footprint[0].x-3,y:footprint[0].y-3},{x:footprint[1].x+3,y:footprint[1].y+3}];
  const work=new Map<string,Position>();for(const entity of document.entities){const candidates=[{x:entity.position.x-2,y:entity.position.y},{x:entity.position.x+2,y:entity.position.y},{x:entity.position.x,y:entity.position.y-2},{x:entity.position.x,y:entity.position.y+2}].filter(canStand);if(!candidates.length)throw new Error(`Unreachable work position: ${entity.id}`);work.set(entity.id,candidates[0]!);}
  const remaining=[...document.entities],ordered:BlueprintEntity[]=[];let cursor:Position={x:footprint[0].x-2,y:footprint[0].y-2};while(remaining.length){remaining.sort((a,b)=>distance(cursor,work.get(a.id)!)-distance(cursor,work.get(b.id)!)||a.id.localeCompare(b.id));const next=remaining.shift()!;ordered.push(next);const nextWork=work.get(next.id);if(!nextWork)throw new Error(`Missing work position: ${next.id}`);cursor=nextWork;}
  const steps:Step[]=[];for(const entity of ordered){steps.push({kind:'walk',position:work.get(entity.id)!},{kind:'place',position:entity.position,item:entity.name,quality:'normal',direction:entity.direction});const ref=target(entity);if(entity.recipe)steps.push({kind:'recipe',target:ref,recipe:entity.recipe});for(const[name,count]of Object.entries(entity.modules??{}))steps.push({kind:'module',target:ref,item:{name,quality:'normal',count}});for(const filter of entity.filters??[])steps.push({kind:'filter',target:ref,slot:filter.index,item:{name:filter.name,quality:'normal'}});if(entity.inventoryBar!==undefined)steps.push({kind:'bar',target:ref,inventory:'chest',limit:entity.inventoryBar});if(entity.undergroundType)steps.push({kind:'setting',target:ref,name:'underground_type',value:entity.undergroundType});for(const[name,value]of Object.entries(entity.settings??{})){if(!['active','inserter_filter_mode','splitter_input_priority','splitter_output_priority'].includes(name)||!['string','boolean'].includes(typeof value))throw new Error(`Unsupported character setting: ${name}`);steps.push({kind:'setting',target:ref,name:name as 'active'|'inserter_filter_mode'|'splitter_input_priority'|'splitter_output_priority',value:value as string|boolean});}}
  for(const wire of document.wires){const from=document.entities.find(e=>e.id===wire.from.entityId)!,to=document.entities.find(e=>e.id===wire.to.entityId)!;steps.push({kind:'walk',position:work.get(from.id)!},{kind:'wire',target:target(from),other:target(to),fromConnector:Number(wire.from.connector),toConnector:Number(wire.to.connector)});}
  return{document,footprint,approach,steps,required};
}
export function constructionBatches(plan:ConstructionPlan,input:{commandPrefix:string;epoch:string;session:string;task:string;revision:number;actor:string;surface:string;grants:Grant[];deadline:number},limit=100):Batch[]{
  if(limit<1||limit>100)throw new Error('Invalid construction batch limit');const{commandPrefix,...batch}=input;const batches:Batch[]=[];for(let offset=0;offset<plan.steps.length;offset+=limit)batches.push({...batch,commandId:`${commandPrefix}-${batches.length+1}`,steps:plan.steps.slice(offset,offset+limit)});return batches;
}
