import { createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import { realpath, readdir, stat, readFile } from 'node:fs/promises';
import path from 'node:path';
export interface HelperPolicy { wallMs:number; inputBytes:number; outputBytes:number; scratchBytes:number; invocations:number; policyHash:string }
export interface HelperPlan { revision:number; actions:{kind:string;payload:Record<string,unknown>}[] }
export class HelperQuota { used=0; constructor(readonly policy:HelperPolicy){} admit(){if(++this.used>this.policy.invocations)throw new Error('Helper invocation quota exhausted');} }
export async function invokeConfinedHelper(input:{worker:string;bundleRoot:string;helper:string;expectedHash:string;scratch:string;value:unknown;policy:HelperPolicy;quota:HelperQuota}):Promise<unknown>{
  input.quota.admit();const [worker,bundleRoot,helper,scratch]=await Promise.all([realpath(input.worker),realpath(input.bundleRoot),realpath(input.helper),realpath(input.scratch)]);if(!helper.startsWith(bundleRoot+path.sep))throw new Error('Helper path escape denied');
  const bytes=Buffer.from(JSON.stringify(input.value));if(bytes.length>input.policy.inputBytes)throw new Error('Helper input quota exceeded');const actual=createHash('sha256').update(await readFile(helper)).digest('hex');if(actual!==input.expectedHash)throw new Error('Helper bundle hash mismatch');
  let stdout:Buffer;try{stdout=await launch(worker,helper,scratch,bytes,input.policy);}catch(error){throw new Error(`Confined helper rejected: ${String(error)}`);}
  await enforceScratch(scratch,input.policy.scratchBytes);let value:unknown;try{value=JSON.parse(stdout.toString('utf8'));}catch{throw new Error('Confined helper returned malformed output');}return value;
}
function launch(worker:string,helper:string,scratch:string,input:Buffer,policy:HelperPolicy):Promise<Buffer>{return new Promise((resolve,reject)=>{const child=spawn(process.execPath,['--permission',`--allow-fs-read=${worker}`,`--allow-fs-read=${helper}`,`--allow-fs-write=${scratch}`,'--max-old-space-size=64',worker,helper],{cwd:scratch,env:{},stdio:['pipe','pipe','pipe'],windowsHide:true});const out:Buffer[]=[];const err:Buffer[]=[];let size=0;let forced:Error|undefined;const stop=(error:Error)=>{if(!forced){forced=error;child.kill();}};const timer=setTimeout(()=>stop(new Error('Helper timeout')),policy.wallMs);child.stdout.on('data',(chunk:Buffer)=>{if(forced)return;size+=chunk.length;if(size>policy.outputBytes)stop(new Error('Helper output quota exceeded'));else out.push(chunk);});child.stderr.on('data',(chunk:Buffer)=>{if(Buffer.concat(err).length<4096)err.push(chunk);});child.once('error',error=>{clearTimeout(timer);reject(error);});child.once('close',code=>{clearTimeout(timer);if(forced)reject(forced);else if(code===0)resolve(Buffer.concat(out));else reject(new Error(`worker exit ${code}: ${Buffer.concat(err).toString('utf8').slice(0,4096)}`));});child.stdin.on('error',()=>{});child.stdin.end(input);});}
async function enforceScratch(root:string,limit:number):Promise<void>{let total=0;for(const name of await readdir(root)){const file=await realpath(path.join(root,name));if(!file.startsWith(root+path.sep))throw new Error('Helper scratch junction escape denied');const info=await stat(file);if(!info.isFile())throw new Error('Helper scratch may contain files only');total+=info.size;}if(total>limit)throw new Error('Helper scratch quota exceeded');}
export function authorizeHelperPlan(value:unknown,expectedRevision:number,allowedKinds:string[],remaining:number):HelperPlan{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Invalid helper plan');const plan=value as Partial<HelperPlan>;if(Object.keys(plan).sort().join('|')!=='actions|revision'||plan.revision!==expectedRevision||!Array.isArray(plan.actions)||plan.actions.length>remaining)throw new Error('Stale or over-budget helper plan');for(const action of plan.actions)if(!action||typeof action!=='object'||Object.keys(action).sort().join('|')!=='kind|payload'||!allowedKinds.includes(action.kind)||!action.payload||typeof action.payload!=='object'||Array.isArray(action.payload))throw new Error('Unauthorized helper action');return structuredClone(plan as HelperPlan);}
