import { createHash } from 'node:crypto';
import type { EventContext, Journal } from '../execution/durable.js';
import type { LearningOutcome } from '@autofactorio/contracts';

const digest=(value:unknown)=>createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value)).digest('hex');
const bundleBytes=(b:Pick<LearningBundle,'incumbentHash'|'expectedGeneration'|'files'|'requiredControls'|'behaviorChanging'|'policyHash'|'retrievalHash'|'catalogHash'|'candidates'>)=>({incumbentHash:b.incumbentHash,expectedGeneration:b.expectedGeneration,files:b.files,requiredControls:b.requiredControls,behaviorChanging:b.behaviorChanging,policyHash:b.policyHash,retrievalHash:b.retrievalHash,catalogHash:b.catalogHash,candidates:b.candidates});
export type LearningScope='designer-instructions'|'scorer-instructions'|'lesson'|'design-helper';
export type LearningBundlePath='designer.instructions'|'scorer.instructions'|'lessons.json'|'design-helper.mjs';
export interface LearningCandidate { id:string; batchId:string; scope:LearningScope; content:string; contentHash:string; evidence:string[]; contextLineage:string[]; libraryIndependent:boolean; attempts:number; state:'proposed'|'staged'|'accepted'|'refined'|'merged'|'rejected'|'deferred'|'no-change'|'relocated'|'retired'; reason:string; revisitCondition:string|null }
export interface LearningAttestation { kind:'deterministic'|'interaction'|'behavior'|'review'; bundleHash:string; incumbentHash:string; generation:number; controlSuite:string; controls:string[]; environment:string; passed:boolean; conclusive:boolean; evidence:string[] }
export interface LearningBundle { hash:string; incumbentHash:string; expectedGeneration:number; files:Partial<Record<LearningBundlePath,string>>; requiredControls:string[]; behaviorChanging:boolean; policyHash:string; retrievalHash:string; catalogHash:string; candidates:string[]; attestations:LearningAttestation[]; immutable:true }
export interface ActivationCatalog { generation:number; activeHash:string; verifiedHashes:string[]; quarantined:string[]; history:{generation:number;hash:string;operationId:string;reason:string}[]; pinnedSessions:Record<string,{generation:number;hash:string}> }
export interface LearningPolicy { maxCandidates:number; maxAttempts:number; maxLessonsPerRole:number; maxBriefingBytes:number; maxBundles:number }
export const DEFAULT_LEARNING_POLICY:LearningPolicy={maxCandidates:3,maxAttempts:2,maxLessonsPerRole:10,maxBriefingBytes:16*1024,maxBundles:1};

export class LearningService {
  constructor(private journal:Journal,private context:()=>EventContext,readonly policy=DEFAULT_LEARNING_POLICY){}
  candidate(input:Omit<LearningCandidate,'contentHash'|'attempts'|'state'|'reason'|'revisitCondition'>):LearningCandidate{
    if(!input.evidence.length||!input.contextLineage.length)throw new Error('Learning provenance required');
    if(!input.libraryIndependent&&['designer-instructions','lesson','design-helper'].includes(input.scope))throw new Error('Private library lineage cannot enter reusable learning');
    const all=this.journal.list<LearningCandidate>(this.context().run,'learningCandidates'),existing=all.filter(v=>v.batchId===input.batchId);
    if(existing.length>=this.policy.maxCandidates)throw new Error('Learning candidate cap reached');
    const contentHash=digest(input.content);const duplicate=all.find(v=>v.scope===input.scope&&v.contentHash===contentHash);
    if(duplicate&&(!duplicate.revisitCondition||!input.evidence.includes(duplicate.revisitCondition)))throw new Error('Duplicate learning candidate has no satisfied revisit condition');
    const value:LearningCandidate={...structuredClone(input),contentHash,attempts:0,state:'proposed',reason:'',revisitCondition:null};this.saveCandidate(value,'learning/proposed');return value;
  }
  attempt(id:string):LearningCandidate{const c=this.getCandidate(id);if(c.attempts>=this.policy.maxAttempts)throw new Error('Learning patch attempt cap reached');c.attempts++;c.state='staged';this.saveCandidate(c,'learning/staged');return c;}
  decide(id:string,decision:LearningOutcome['decision'],reason:string,revisitCondition:string|null):LearningCandidate{const c=this.getCandidate(id);if(!reason.trim())throw new Error('Learning decision reason required');const next=decision==='accept'?'accepted':decision==='refine'?'refined':decision==='merge'?'merged':decision==='reject'?'rejected':decision==='defer'?'deferred':'no-change';if(['accepted','merged'].includes(next)){const active=this.journal.list<LearningCandidate>(this.context().run,'learningCandidates').filter(v=>v.id!==id&&v.scope===c.scope&&['accepted','merged'].includes(v.state));if(active.length>=this.policy.maxLessonsPerRole)throw new Error('Active lesson count cap reached');}c.state=next;c.reason=reason;c.revisitCondition=revisitCondition;this.saveCandidate(c,'learning/decided');return c;}
  relocate(id:string,scope:LearningScope,reason:string):LearningCandidate{const c=this.getCandidate(id);if(!reason.trim()||scope===c.scope)throw new Error('Learning relocation requires a new scope and reason');c.scope=scope;c.state='relocated';c.reason=reason;this.saveCandidate(c,'learning/relocated');return c;}
  retire(id:string,reason:string):LearningCandidate{const c=this.getCandidate(id);if(!reason.trim())throw new Error('Learning retirement reason required');c.state='retired';c.reason=reason;this.saveCandidate(c,'learning/retired');return c;}
  retrieve(scope:LearningScope,maxBytes=this.policy.maxBriefingBytes):{values:LearningCandidate[];omitted:string[]}{let used=0;const values:LearningCandidate[]=[];const omitted:string[]=[];for(const c of this.journal.list<LearningCandidate>(this.context().run,'learningCandidates').filter(v=>v.scope===scope&&v.libraryIndependent&&['accepted','merged'].includes(v.state)).sort((a,b)=>a.id.localeCompare(b.id))){const bytes=Buffer.byteLength(c.content);if(values.length>=this.policy.maxLessonsPerRole||used+bytes>maxBytes)omitted.push(c.id);else{values.push(c);used+=bytes;}}return{values,omitted};}
  duplicate(scope:LearningScope,content:string):LearningCandidate|null{return this.journal.list<LearningCandidate>(this.context().run,'learningCandidates').find(value=>value.scope===scope&&value.contentHash===digest(content))??null;}
  assemble(input:{incumbentHash:string;expectedGeneration:number;files:Partial<Record<LearningBundlePath,string>>;requiredControls:string[];policyHash:string;retrievalHash:string;catalogHash:string;candidates:string[]}):LearningBundle{
    const prior=this.journal.list<LearningBundle>(this.context().run,'learningBundles').filter(v=>v.expectedGeneration===input.expectedGeneration&&v.incumbentHash===input.incumbentHash);if(prior.length>=this.policy.maxBundles)throw new Error('Learning bundle cap reached');if(input.candidates.length>this.policy.maxCandidates)throw new Error('Learning bundle candidate cap reached');
    const allowed:LearningBundlePath[]=['designer.instructions','scorer.instructions','lessons.json','design-helper.mjs'];const changedPaths=Object.keys(input.files);if(!changedPaths.length||changedPaths.some(value=>!allowed.includes(value as LearningBundlePath))||Object.values(input.files).some(value=>typeof value!=='string'||!value.length))throw new Error('Learning bundle contains an unregistered or empty file');
    const incumbent=input.incumbentHash==='baseline'?null:this.bundle(input.incumbentHash),files=Object.fromEntries(Object.entries({...incumbent?.files,...input.files}).sort(([a],[b])=>a.localeCompare(b))) as Partial<Record<LearningBundlePath,string>>,paths=Object.keys(files);if(Object.values(files).reduce((n,v)=>n+Buffer.byteLength(v),0)>this.policy.maxBriefingBytes)throw new Error('Learning bundle instruction budget exceeded');
    const requiredControls=[...new Set([...(incumbent?.requiredControls??[]),...input.requiredControls])].sort();if(!requiredControls.length||requiredControls.some(value=>!value.trim()))throw new Error('Learning bundle requires declared controls');
    const behaviorChanging=paths.length>0;
    const manifest={incumbentHash:input.incumbentHash,expectedGeneration:input.expectedGeneration,files,requiredControls,behaviorChanging,policyHash:input.policyHash,retrievalHash:input.retrievalHash,catalogHash:input.catalogHash,candidates:input.candidates};const bundle:LearningBundle={...structuredClone(manifest),hash:digest(manifest),attestations:[],immutable:true};this.saveBundle(bundle,'learning/bundle-assembled');return bundle;
  }
  attest(hash:string,attestation:LearningAttestation):LearningBundle{const b=this.bundle(hash);const controls=[...new Set(attestation.controls)].sort();if(attestation.bundleHash!==hash||attestation.incumbentHash!==b.incumbentHash||attestation.generation!==b.expectedGeneration||!attestation.controlSuite||!attestation.environment||!attestation.evidence.length||JSON.stringify(controls)!==JSON.stringify(b.requiredControls))throw new Error('Attestation does not bind exact bundle and complete controls');if(digest(bundleBytes(b))!==hash)throw new Error('Bundle changed after assembly');const prior=b.attestations[0];if(prior&&(prior.controlSuite!==attestation.controlSuite||prior.environment!==attestation.environment))throw new Error('Attestation environment or controls changed');b.attestations.push({...structuredClone(attestation),controls});this.saveBundle(b,'learning/attested');return b;}
  activate(hash:string,operationId:string):ActivationCatalog{const b=this.bundle(hash),catalog=this.catalog();const prior=catalog.history.find(v=>v.operationId===operationId);if(prior){if(prior.hash!==hash)throw new Error('Activation operation collision');return catalog;}if(catalog.generation!==b.expectedGeneration||catalog.activeHash!==b.incumbentHash)throw new Error('Stale activation evidence; rebase and revalidate');
    const needed=['deterministic','interaction','review',...(b.behaviorChanging?['behavior' as const]:[])] as const;for(const kind of needed){const matching=b.attestations.filter(v=>v.kind===kind);if(!matching.length||matching.some(v=>!v.passed||!v.conclusive))throw new Error(`Missing exclusively passing and conclusive ${kind} attestation`);}
    catalog.generation++;catalog.activeHash=hash;catalog.verifiedHashes.push(hash);catalog.history.push({generation:catalog.generation,hash,operationId,reason:'activation'});this.saveCatalog(catalog,'learning/activated',operationId);return catalog;}
  pin(sessionId:string):{generation:number;hash:string}{const c=this.catalog();return c.pinnedSessions[sessionId]??(()=>{const pin={generation:c.generation,hash:c.activeHash};c.pinnedSessions[sessionId]=pin;this.saveCatalog(c,'learning/session-pinned',sessionId);return pin;})();}
  pinnedBundle(sessionId:string):{generation:number;hash:string;files:Partial<Record<LearningBundlePath,string>>;policyHash:string;retrievalHash:string;catalogHash:string}{const pin=this.pin(sessionId);if(pin.hash==='baseline')return{...pin,files:{},policyHash:'baseline',retrievalHash:'baseline',catalogHash:'baseline'};const bundle=this.bundle(pin.hash);return{...pin,files:structuredClone(bundle.files),policyHash:bundle.policyHash,retrievalHash:bundle.retrievalHash,catalogHash:bundle.catalogHash};}
  activationReady(hash:string):boolean{const b=this.bundle(hash),c=this.catalog();if(c.generation!==b.expectedGeneration||c.activeHash!==b.incumbentHash)return false;const needed=['deterministic','interaction','review',...(b.behaviorChanging?['behavior' as const]:[])] as const;return needed.every(kind=>{const values=b.attestations.filter(v=>v.kind===kind);return values.length>0&&values.every(v=>v.passed&&v.conclusive);});}
  recordOutcome(outcome:LearningOutcome):LearningOutcome{if(outcome.schema!==1||!outcome.id||!outcome.reason.trim()||!outcome.evidence.length)throw new Error('Invalid learning outcome');const existing=this.journal.get<LearningOutcome>(this.context().run,'learningOutcomes',outcome.id);if(existing){const prior={...existing,activatedGeneration:null},next={...outcome,activatedGeneration:null};if(JSON.stringify(prior)!==JSON.stringify(next)||existing.activatedGeneration!==null&&existing.activatedGeneration!==outcome.activatedGeneration)throw new Error('Learning outcome identity collision');if(existing.activatedGeneration===outcome.activatedGeneration)return structuredClone(existing);}this.journal.append(this.context(),'learning/outcome',[{entity:'learningOutcomes',id:outcome.id,value:{...outcome}}]);return structuredClone(outcome);}
  rollback(hash:string,operationId:string):ActivationCatalog{const c=this.catalog();if(!c.verifiedHashes.includes(hash)||c.quarantined.includes(hash))throw new Error('Rollback target is not an eligible verified bundle');if(c.history.some(v=>v.operationId===operationId))return c;c.generation++;c.activeHash=hash;c.history.push({generation:c.generation,hash,operationId,reason:'rollback'});this.saveCatalog(c,'learning/rolled-back',operationId);return c;}
  quarantine(hash:string,reason:string):ActivationCatalog{const c=this.catalog();if(!reason.trim())throw new Error('Quarantine reason required');if(!c.quarantined.includes(hash))c.quarantined.push(hash);if(c.activeHash===hash){const fallback=[...c.history].reverse().map(v=>v.hash).find(v=>v!==hash&&c.verifiedHashes.includes(v)&&!c.quarantined.includes(v))??'baseline';c.generation++;c.activeHash=fallback;c.history.push({generation:c.generation,hash:fallback,operationId:`quarantine:${hash}:${c.generation}`,reason:`quarantine: ${reason}`});}this.saveCatalog(c,'learning/quarantined',hash);return c;}
  inspectCatalog():ActivationCatalog{return structuredClone(this.catalog());}
  private getCandidate(id:string):LearningCandidate{const c=this.journal.get<LearningCandidate>(this.context().run,'learningCandidates',id);if(!c)throw new Error('Unknown learning candidate');return c;}
  private bundle(hash:string):LearningBundle{const b=this.journal.get<LearningBundle>(this.context().run,'learningBundles',hash);if(!b)throw new Error('Unknown learning bundle');return b;}
  private catalog():ActivationCatalog{return this.journal.get<ActivationCatalog>(this.context().run,'activations','catalog')??{generation:0,activeHash:'baseline',verifiedHashes:['baseline'],quarantined:[],history:[],pinnedSessions:{}};}
  private saveCandidate(c:LearningCandidate,type:string){this.journal.append(this.context(),type,[{entity:'learningCandidates',id:c.id,value:{...c}}]);}
  private saveBundle(b:LearningBundle,type:string){this.journal.append(this.context(),type,[{entity:'learningBundles',id:b.hash,value:{...b}}]);}
  private saveCatalog(c:ActivationCatalog,type:string,id:string){this.journal.append({...this.context(),correlation:id},type,[{entity:'activations',id:'catalog',value:{...c}}]);}
}
