import { mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import Database from 'better-sqlite3';
import type { BlueprintDocument, BlueprintRevisionMetadata, WorkshopAssignment, WorkshopEvaluationReport, WorkshopScore } from '@autofactorio/contracts';
import { blueprintContentHash, exportBlueprint, normalizeBlueprint, sanitizedBundle } from './blueprint.js';
import { workshopRubricHash } from './scoring.js';

export interface LibraryAdmission {
  identity:Pick<BlueprintRevisionMetadata,'familyId'|'variantId'|'parentHash'|'label'>;
  document:BlueprintDocument;
  proof:{score:WorkshopScore;evaluation:WorkshopEvaluationReport;rubric:WorkshopAssignment['rubric'];rubricHash:string;profileId:string;gameFingerprint:string;outputPortId:string;exportValid:boolean;characterBuildEvidence:string[]|null;compatibilityEvidence:string[];distinctionEvidence:string[];admit:boolean};
  operationId:string;
}
export interface LibrarySearch { product?:string; profileId?:string; gameFingerprint?:string; machine?:string; status?:string; maxWidth?:number; maxHeight?:number; limit?:number; offset?:number }
export interface LibraryEntry extends BlueprintRevisionMetadata { directory:string }

const safe=(value:string,label:string)=>{if(!/^[\w.-]{1,160}$/.test(value))throw new Error(`Invalid ${label}`);return value;};
const atomicJson=(file:string,value:unknown)=>{const temporary=file+'.pending';writeFileSync(temporary,JSON.stringify(value,null,2),{flag:'wx'});renameSync(temporary,file);};
export class BlueprintLibrary {
  private readonly db:Database.Database;
  constructor(readonly root:string){mkdirSync(root,{recursive:true});this.db=new Database(path.join(root,'index.sqlite'));this.db.pragma('journal_mode = WAL');this.db.exec(`CREATE TABLE IF NOT EXISTS revisions(revision_hash TEXT PRIMARY KEY,family_id TEXT NOT NULL,variant_id TEXT NOT NULL,label TEXT NOT NULL,product TEXT NOT NULL,profile_id TEXT NOT NULL,game_fingerprint TEXT NOT NULL,statuses TEXT NOT NULL,width INTEGER NOT NULL,height INTEGER NOT NULL,machines TEXT NOT NULL,directory TEXT NOT NULL,operation_id TEXT NOT NULL UNIQUE);CREATE INDEX IF NOT EXISTS revisions_search ON revisions(product,profile_id,game_fingerprint);`);}
  private directory(metadata:Omit<BlueprintRevisionMetadata,'revisionHash'>,hash:string){return path.join(this.root,'components',safe(metadata.product.name,'product'),safe(metadata.familyId,'family'),safe(metadata.variantId,'variant'),'revisions',hash);}
  admit(input:LibraryAdmission):LibraryEntry{
    safe(input.operationId,'operation');const document=normalizeBlueprint(input.document);const revisionHash=blueprintContentHash(document),proof=input.proof;
    if(!proof.score.eligible||!proof.evaluation.valid||!proof.evaluation.passed||proof.score.candidate.artifactHash!==revisionHash||proof.evaluation.attemptId!==`${proof.score.candidate.sessionId}:${proof.score.candidate.iteration}`)throw new Error('Library admission requires one exact eligible evaluated artifact');
    if(proof.score.rubricVersion!==proof.rubric.version||proof.rubricHash!==workshopRubricHash(proof.rubric))throw new Error('Library admission rubric evidence mismatch');
    if(!proof.exportValid||!proof.compatibilityEvidence.length||!proof.admit||!proof.distinctionEvidence.length)throw new Error('Library admission validity or useful-distinction gate failed');
    const port=document.ports.find(value=>value.id===proof.outputPortId&&value.direction==='output'&&value.required);if(!port)throw new Error('Library admission output port mismatch');
    const xs=document.entities.map(value=>value.position.x),ys=document.entities.map(value=>value.position.y);const footprint={width:Math.max(...xs)-Math.min(...xs)+1,height:Math.max(...ys)-Math.min(...ys)+1};
    const statuses:BlueprintRevisionMetadata['statuses']=['export-valid','production-verified'];if(proof.characterBuildEvidence?.length)statuses.push('character-build-verified');
    const metadata:BlueprintRevisionMetadata={schema:1,...structuredClone(input.identity),revisionHash,product:structuredClone(port.product),profileId:safe(proof.profileId,'profile'),gameFingerprint:safe(proof.gameFingerprint,'game fingerprint'),statuses,footprint,machines:[...new Set(document.entities.map(value=>value.name))].sort(),rate:structuredClone(port.rate),provenance:[...new Set([proof.score.candidate.bundleHash,...proof.score.candidate.evidence])],evidence:[...new Set([...proof.evaluation.evidence,...Object.values(proof.score.dimensions).flatMap(value=>value.evidence),...proof.compatibilityEvidence,...proof.distinctionEvidence,...(proof.characterBuildEvidence??[])])]};const directory=this.directory(metadata,revisionHash);
    const existing=this.db.prepare('SELECT directory FROM revisions WHERE revision_hash=? OR operation_id=?').get(revisionHash,input.operationId) as {directory:string}|undefined;if(existing){const stored=JSON.parse(readFileSync(path.join(existing.directory,'metadata.json'),'utf8')) as BlueprintRevisionMetadata;if(stored.revisionHash!==revisionHash)throw new Error('Operation identity already admitted different revision');return{...stored,directory:existing.directory};}
    try{const stored=JSON.parse(readFileSync(path.join(directory,'metadata.json'),'utf8'))as BlueprintRevisionMetadata;if(stored.revisionHash!==revisionHash)throw new Error('Revision directory collision');this.db.prepare('INSERT OR IGNORE INTO revisions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(revisionHash,stored.familyId,stored.variantId,stored.label,stored.product.name,stored.profileId,stored.gameFingerprint,JSON.stringify(stored.statuses),stored.footprint.width,stored.footprint.height,JSON.stringify(stored.machines),directory,input.operationId);return{...stored,directory};}catch(error){if(!(error&&typeof error==='object'&&'code'in error&&error.code==='ENOENT'))throw error;}
    const temporary=directory+'.pending-'+input.operationId;mkdirSync(path.dirname(directory),{recursive:true});mkdirSync(temporary,{recursive:false});
    try{atomicJson(path.join(temporary,'blueprint.json'),document);writeFileSync(path.join(temporary,'blueprint.txt'),exportBlueprint(document),{flag:'wx'});atomicJson(path.join(temporary,'metadata.json'),metadata);atomicJson(path.join(temporary,'evidence.json'),input.proof);atomicJson(path.join(temporary,'portable.json'),sanitizedBundle(document,metadata));mkdirSync(path.dirname(directory),{recursive:true});renameSync(temporary,directory);
      const insert=this.db.transaction(()=>this.db.prepare('INSERT INTO revisions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(revisionHash,metadata.familyId,metadata.variantId,metadata.label,metadata.product.name,metadata.profileId,metadata.gameFingerprint,JSON.stringify(metadata.statuses),metadata.footprint.width,metadata.footprint.height,JSON.stringify(metadata.machines),directory,input.operationId));
      try{insert();}catch(error){const raced=this.db.prepare('SELECT directory FROM revisions WHERE revision_hash=? OR operation_id=?').get(revisionHash,input.operationId) as {directory:string}|undefined;if(!raced)throw error;if(raced.directory!==directory)rmSync(directory,{recursive:true,force:true});}
      return{...metadata,directory};
    }catch(error){rmSync(temporary,{recursive:true,force:true});throw error;}
  }
  search(query:LibrarySearch={}):LibraryEntry[]{
    const clauses:string[]=[],values:unknown[]=[];for(const[field,column]of [['product','product'],['profileId','profile_id'],['gameFingerprint','game_fingerprint']]as const)if(query[field]){clauses.push(`${column}=?`);values.push(query[field]);}if(query.maxWidth!==undefined){clauses.push('width<=?');values.push(query.maxWidth);}if(query.maxHeight!==undefined){clauses.push('height<=?');values.push(query.maxHeight);}if(query.machine){clauses.push('machines LIKE ?');values.push(`%"${query.machine}"%`);}if(query.status){clauses.push('statuses LIKE ?');values.push(`%"${query.status}"%`);}const limit=Math.min(100,Math.max(1,query.limit??25)),offset=Math.max(0,query.offset??0);
    const rows=this.db.prepare(`SELECT directory FROM revisions ${clauses.length?'WHERE '+clauses.join(' AND '):''} ORDER BY product,family_id,variant_id,revision_hash LIMIT ? OFFSET ?`).all(...values,limit,offset)as{directory:string}[];return rows.map(row=>({...JSON.parse(readFileSync(path.join(row.directory,'metadata.json'),'utf8')) as BlueprintRevisionMetadata,directory:row.directory}));
  }
  rename(revisionHash:string,label:string):void{safe(revisionHash,'revision');if(!label.trim()||label.length>200)throw new Error('Invalid label');const row=this.db.prepare('SELECT directory FROM revisions WHERE revision_hash=?').get(revisionHash)as{directory:string}|undefined;if(!row)throw new Error('Unknown revision');const metadata=JSON.parse(readFileSync(path.join(row.directory,'metadata.json'),'utf8'))as BlueprintRevisionMetadata;atomicJson(path.join(row.directory,'metadata.json.pending-update'),{...metadata,label});renameSync(path.join(row.directory,'metadata.json.pending-update'),path.join(row.directory,'metadata.json'));this.db.prepare('UPDATE revisions SET label=? WHERE revision_hash=?').run(label,revisionHash);}
  get(revisionHash:string):{entry:LibraryEntry;document:BlueprintDocument;blueprint:string;portable:unknown;evidence:LibraryAdmission['proof']}{safe(revisionHash,'revision');const row=this.db.prepare('SELECT directory FROM revisions WHERE revision_hash=?').get(revisionHash)as{directory:string}|undefined;if(!row)throw new Error('Unknown revision');return{entry:{...JSON.parse(readFileSync(path.join(row.directory,'metadata.json'),'utf8'))as BlueprintRevisionMetadata,directory:row.directory},document:JSON.parse(readFileSync(path.join(row.directory,'blueprint.json'),'utf8'))as BlueprintDocument,blueprint:readFileSync(path.join(row.directory,'blueprint.txt'),'utf8'),portable:JSON.parse(readFileSync(path.join(row.directory,'portable.json'),'utf8')),evidence:JSON.parse(readFileSync(path.join(row.directory,'evidence.json'),'utf8'))as LibraryAdmission['proof']};}
  async rebuild():Promise<number>{this.db.prepare('DELETE FROM revisions').run();const components=path.join(this.root,'components');let count=0;const walk=async(directory:string):Promise<void>=>{let entries;try{entries=await readdir(directory,{withFileTypes:true});}catch{return;}for(const entry of entries){const target=path.join(directory,entry.name);if(entry.isDirectory())await walk(target);else if(entry.name==='metadata.json'){const metadata=JSON.parse(await readFile(target,'utf8'))as BlueprintRevisionMetadata;const operationId=`rebuild-${metadata.revisionHash}`;this.db.prepare('INSERT OR IGNORE INTO revisions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(metadata.revisionHash,metadata.familyId,metadata.variantId,metadata.label,metadata.product.name,metadata.profileId,metadata.gameFingerprint,JSON.stringify(metadata.statuses),metadata.footprint.width,metadata.footprint.height,JSON.stringify(metadata.machines),directory,operationId);count++;}}};await walk(components);return count;}
  close():void{this.db.close();}
}
