import type { BlueprintDocument } from '@autofactorio/contracts';
import type { EventContext, Journal } from '../execution/durable.js';

export interface MaterializationPort { materialize(id:string,generation:number,operationId:string,document:BlueprintDocument):Promise<Record<string,unknown>>; inspect(id:string):Promise<Record<string,unknown>> }
export interface MaterializationOperation { id:string;workshop:string;generation:number;artifactHash:string;state:'pending'|'sending'|'unknown'|'completed'|'cancelled'|'failed';document:BlueprintDocument;receipt:Record<string,unknown>|null;reason:string|null }
export class DirectMaterializer {
  private busy=false;
  constructor(private journal:Journal,private context:()=>EventContext,private port:MaterializationPort){}
  private save(operation:MaterializationOperation,type:string){this.journal.append(this.context(),type,[{entity:'workshopOperations',id:operation.id,value:{...operation}}]);}
  intent(operation:Omit<MaterializationOperation,'state'|'receipt'|'reason'>){if(this.journal.get(this.context().run,'workshopOperations',operation.id))throw new Error('Materialization identity already exists');this.save({...structuredClone(operation),state:'pending',receipt:null,reason:null},'workshop/materialization-intent');}
  cancel(id:string){const operation=this.journal.get<MaterializationOperation>(this.context().run,'workshopOperations',id);if(!operation)throw new Error('Unknown materialization');if(operation.state!=='pending')throw new Error('Materialization already dispatched');this.save({...operation,state:'cancelled',reason:'cancelled_before_dispatch'},'workshop/materialization-cancelled');}
  async dispatch(id:string){if(this.busy)throw new Error('Materialization operation in progress');const operation=this.journal.get<MaterializationOperation>(this.context().run,'workshopOperations',id);if(!operation||operation.state!=='pending')throw new Error('Materialization is not pending');this.busy=true;this.save({...operation,state:'sending'},'workshop/materialization-sending');try{const receipt=await this.port.materialize(operation.workshop,operation.generation,operation.id,operation.document);const completed={...operation,state:'completed' as const,receipt,reason:null};this.save(completed,'workshop/materialization-completed');return completed;}catch(error){const unknown={...operation,state:'unknown' as const,reason:String(error),receipt:null};this.save(unknown,'workshop/materialization-unknown');throw error;}finally{this.busy=false;}}
  async reconcile(id:string){const operation=this.journal.get<MaterializationOperation>(this.context().run,'workshopOperations',id);if(!operation)throw new Error('Unknown materialization');if(operation.state!=='unknown'&&operation.state!=='sending')return operation;const state=await this.port.inspect(operation.workshop);const receipt=await this.port.materialize(operation.workshop,operation.generation,operation.id,operation.document);const entities=receipt.entities;if(!entities||typeof entities!=='object')throw new Error('Materialization reconciliation incomplete');const completed={...operation,state:'completed' as const,receipt:{...receipt,inspection:state},reason:null};this.save(completed,'workshop/materialization-reconciled');return completed;}
}
