import { appendFileSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { performance } from 'node:perf_hooks';
import { setTimeout as delay } from 'node:timers/promises';
import { combineEffectReceipts, effectReceipt, normalizeEffectReceipt, rationalFromDecimal, validateWorkshopAssignment } from '@autofactorio/contracts';
import type { Assignment, BlueprintDocument, EffectReceipt, LearningOutcome, ModelSelection, Receipt, WorkshopAssignment, WorkshopCandidateRef, WorkshopEvaluationReport, WorkshopScore } from '@autofactorio/contracts';
import { Budget } from '../../packages/codex/src/budget.js';
import { managedCatalog, profileOverrides } from '../../packages/codex/src/preflight.js';
import type { ManagedCatalog } from '../../packages/codex/src/preflight.js';
import { object } from '../../packages/codex/src/protocol.js';
import type { Activity, Sink } from '../../packages/codex/src/protocol.js';
import { Provider } from '../../packages/codex/src/provider.js';
import { AppServerRpc } from '../../packages/codex/src/rpc.js';
import { blueprintContentHash, billOfMaterials, normalizeBlueprint } from '../../packages/core/workshop/blueprint.js';
import { compileCharacterBlueprint, constructionBatches } from '../../packages/core/workshop/construction.js';
import { evaluateWorkshop } from '../../packages/core/workshop/evaluation.js';
import { HelperQuota, authorizeHelperPlan, invokeConfinedHelper } from '../../packages/core/workshop/helper-worker.js';
import type { LibraryAdmission } from '../../packages/core/workshop/library.js';
import type { WorkshopSessionState } from '../../packages/core/workshop/orchestrator.js';
import type { CapabilityProfile, InstalledRecipe } from '../../packages/core/workshop/profiles.js';
import { compareWorkshopScores, installedRoutes, scoreWorkshop, workshopRubricHash } from '../../packages/core/workshop/scoring.js';
import { emptyInferenceUsage, WorkshopInferenceAdmissions } from '../../packages/core/workshop/usage.js';
import type { DurableInferenceUsage, WorkshopInferenceAdmission, WorkshopInferenceUsage } from '../../packages/core/workshop/usage.js';
import { WorkshopEffectOutcomeError } from '../../packages/core/workshop/runtime.js';
import type { WorkshopRuntimeHost, WorkshopRuntimeServices } from '../../packages/core/workshop/runtime.js';
import { observeRequest } from '../../packages/factorio/src/client.js';
import type { GameClient } from '../../packages/factorio/src/client.js';
import type { Lifecycle } from '../../packages/factorio/src/lifecycle.js';
import type { CommandPort } from '../../packages/factorio/src/rcon.js';
import { WorkshopControl } from '../../packages/factorio/src/workshop.js';
import type { InstalledWorkshopProfile, WorkshopFixture } from '../../packages/factorio/src/workshop.js';
import { Gateway } from '../../packages/tools/src/gateway.js';
import type { Role } from '../../packages/tools/src/gateway.js';

type WorkshopRole=Extract<Role,`workshop-${string}`>;
interface ResolvedData { assignment:WorkshopAssignment; installed:InstalledWorkshopProfile; profile:CapabilityProfile; recipe:InstalledRecipe; sourceRevision:{hash:string;document:BlueprintDocument}|null }
interface BuiltData { id:string; generation:number; surface:string; characterEvidence:string[]|null }
interface InferenceResult { text:string; usage:WorkshopInferenceUsage }
export interface WorkshopActivity { id:string;sessionId:string;category:'preflight'|'provider'|'game';status:'started'|'completed'|'failed';at:string;iteration?:number|null;role?:WorkshopRole;detail?:string;usage?:WorkshopInferenceUsage }
type ActivitySink=(activity:WorkshopActivity)=>void;
export interface WorkshopInference {
  invoke(session:WorkshopSessionState,role:WorkshopRole,selection:ModelSelection,observation:unknown,prompt:string,instructions:string,admission:WorkshopInferenceAdmission):Promise<string|InferenceResult>;
  cancel?(sessionId:string):EffectReceipt|Promise<EffectReceipt>;
  close():Promise<void>;
}
export interface WorkshopGame {
  resolveProfile(profileId:string,product:string):Promise<InstalledWorkshopProfile>;
  preflight?(assignment:WorkshopAssignment):Promise<void>;
  build(session:WorkshopSessionState,document:BlueprintDocument,profile:CapabilityProfile):Promise<BuiltData>;
  measure(session:WorkshopSessionState,built:BuiltData):Promise<WorkshopEvaluationReport>;
  cancel?(sessionId:string):EffectReceipt|Promise<EffectReceipt>;
}
interface ActivatedLearningContext { bundleHash:string;lessons:string|null;helperPlan:unknown|null;evidence:string[] }

const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const contentDigest=(value:string)=>createHash('sha256').update(value).digest('hex');
const helperWorker=path.resolve('scripts/workshop-helper-worker.mjs');
const number=(value:{numerator:string;denominator:string})=>Number(value.numerator)/Number(value.denominator);
export function requireCompletedCharacterReceipt(receipt:Receipt):void{if(receipt.status!=='completed')throw new WorkshopEffectOutcomeError('failed',`Character workshop batch ${receipt.commandId} ${receipt.status}`);}
const jsonObject=(text:string):Record<string,unknown>=>{
  const fenced=/```(?:json)?\s*([\s\S]*?)```/i.exec(text)?.[1];
  for(const candidate of [fenced,text.slice(text.indexOf('{'),text.lastIndexOf('}')+1)])try{return object(JSON.parse(candidate??''));}catch{/* try the next representation */}
  throw new Error('Managed workshop role did not return one JSON object');
};
const productFromBrief=(brief:string):{product:string;rate:string}=>{
  const match=/(\d+(?:\.\d+)?)\s+([a-z][a-z0-9 -]*?)\s+per\s+minute/i.exec(brief);
  if(!match)throw new Error('Brief must name one supported product and a numeric per-minute target, for example "60 electronic circuits per minute"');
  const aliases:Record<string,string>={'electronic circuit':'electronic-circuit','electronic circuits':'electronic-circuit','iron gear':'iron-gear-wheel','iron gears':'iron-gear-wheel','iron gear wheel':'iron-gear-wheel','iron gear wheels':'iron-gear-wheel'};
  const label=match[2]!.trim().toLowerCase();return{product:aliases[label]??label.replace(/\s+/g,'-').replace(/s$/,''),rate:match[1]!};
};
const designerDocument=(value:Record<string,unknown>,assignment:WorkshopAssignment,resolved:ResolvedData):BlueprintDocument=>{
  const source=value.blueprint&&typeof value.blueprint==='object'?object(value.blueprint):value;if(!Array.isArray(source.entities)||!source.entities.length)throw new Error('Managed designer returned no blueprint entities');const known=new Set(resolved.profile.allowedEquipment);
  const entities=source.entities.map((raw,index)=>{const entity=object(raw),name=String(entity.name??'');if(!known.has(name))throw new Error(`Managed designer used profile-denied equipment: ${name}`);if(entity.recipe!==undefined&&entity.recipe!==resolved.recipe.id)throw new Error(`Managed designer used unavailable recipe: ${String(entity.recipe)}`);const number=Number(entity.entityNumber??entity.entity_number??index+1);return{id:String(entity.id??`entity-${number}`),entityNumber:number,name,position:entity.position as {x:number;y:number},direction:Number(entity.direction??0),quality:'normal' as const,...(typeof entity.recipe==='string'?{recipe:entity.recipe}:{}),...(entity.modules?{modules:entity.modules as Record<string,number>}:{}),...(Array.isArray(entity.filters)?{filters:entity.filters as {index:number;name:string;quality:'normal'}[]}:{}),...(entity.inventoryBar===undefined&&entity.bar===undefined?{}:{inventoryBar:Number(entity.inventoryBar??entity.bar)}),...(entity.settings?{settings:entity.settings as Record<string,string|number|boolean>}:{}),...(entity.undergroundType||entity.type==='input'||entity.type==='output'?{undergroundType:String(entity.undergroundType??entity.type)}:{})};}),ids=new Map(entities.map(entity=>[entity.entityNumber,entity.id])),wires=Array.isArray(source.wires)?source.wires.map(raw=>{if(!Array.isArray(raw))return raw as BlueprintDocument['wires'][number];if(raw.length!==4)throw new Error('Managed designer returned malformed native wire');const from=ids.get(Number(raw[0])),to=ids.get(Number(raw[2]));if(!from||!to)throw new Error('Managed designer wire references unknown entity');return{from:{entityId:from,connector:String(raw[1])},to:{entityId:to,connector:String(raw[3])},color:'copper' as const};}):[];
  const output=assignment.ports.find(port=>port.direction==='output'&&port.required)!;return normalizeBlueprint({schema:1,label:typeof source.label==='string'?source.label:'Managed workshop candidate',description:typeof source.description==='string'?source.description:'Managed designer candidate normalized by the trusted workshop adapter.',entities,wires,ports:assignment.ports,icons:Array.isArray(source.icons)?source.icons as BlueprintDocument['icons']:[{index:1,name:output.product.name}],tiles:Array.isArray(source.tiles)?source.tiles as BlueprintDocument['tiles']:[]});
};

/** Production workshop host. Provider and game adapters are explicit so the composition root can be acceptance-tested without synthetic dashboard behavior. */
export class LiveWorkshopHost implements WorkshopRuntimeHost {
  private services:WorkshopRuntimeServices|null=null;
  constructor(readonly directory:string,private inference:WorkshopInference,private game:WorkshopGame,private activity:ActivitySink=()=>{}){}
  bindServices(services:WorkshopRuntimeServices){this.services=services;}
  private sessionDirectory(id:string){return path.join(this.directory,'workshop-live',id);}
  private async persist(id:string,name:string,value:unknown){const directory=this.sessionDirectory(id);await mkdir(directory,{recursive:true});await writeFile(path.join(directory,name),JSON.stringify(value,null,2));}
  private async resolved(id:string):Promise<ResolvedData>{return JSON.parse(await readFile(path.join(this.sessionDirectory(id),'resolved.json'),'utf8')) as ResolvedData;}
  private async document(candidate:WorkshopCandidateRef):Promise<BlueprintDocument>{const value=JSON.parse(await readFile(path.join(this.sessionDirectory(candidate.sessionId),`${candidate.artifactHash}.json`),'utf8')) as BlueprintDocument;return normalizeBlueprint(value);}
  private async built(candidate:WorkshopCandidateRef):Promise<BuiltData>{return JSON.parse(await readFile(path.join(this.sessionDirectory(candidate.sessionId),`${candidate.artifactHash}.built.json`),'utf8')) as BuiltData;}
  private installed(installed:InstalledWorkshopProfile){const fingerprint=digest({gameVersion:installed.gameVersion,mods:installed.mods,profileId:installed.profileId,profileRevision:installed.profileRevision,surface:installed.surface,technologies:installed.technologies,allowedEquipment:installed.allowedEquipment,modules:installed.modules,beacons:installed.beacons,recipe:installed.recipe,machine:installed.machine}),profile:CapabilityProfile={schema:1,id:installed.profileId,revision:installed.profileRevision,fingerprint,source:'preset',technologies:[...installed.technologies],researchBonuses:{},recipes:[installed.recipe.id],allowedEquipment:[...new Set(installed.allowedEquipment)],locallyManufacturable:[],modules:[...installed.modules],beacons:[...installed.beacons],quality:'normal',surface:installed.surface},recipe:InstalledRecipe={id:installed.recipe.id,category:installed.recipe.category,enabled:true,ingredients:installed.recipe.ingredients,products:installed.recipe.products};return{fingerprint,profile,recipe};}
  private sourceRevision(assignment:WorkshopAssignment):ResolvedData['sourceRevision']{if(!assignment.improveRevision)return null;if(assignment.source.kind!=='revision'||assignment.source.id!==assignment.improveRevision)throw new Error('Improve source revision identity mismatch');const library=this.services?.library;if(!library)throw new Error('Trusted library unavailable for Improve');const prior=library.get(assignment.improveRevision);const output=assignment.ports.find(value=>value.direction==='output'&&value.required)!;if(prior.entry.revisionHash!==assignment.improveRevision||prior.entry.product.name!==output.product.name||prior.entry.profileId!==assignment.profileId||prior.entry.gameFingerprint!==assignment.gameFingerprint)throw new Error('Improve revision is missing or incompatible with the resolved assignment');return{hash:prior.entry.revisionHash,document:normalizeBlueprint(prior.document)};}
  async resolve(input:unknown):Promise<WorkshopAssignment>{
    return this.resolveAssignment(object(input));
  }
  async preflight(assignment:WorkshopAssignment):Promise<void>{const activityId=`${assignment.id}:preflight`;this.activity({id:activityId,sessionId:assignment.id,category:'preflight',status:'started',at:new Date().toISOString(),detail:'Checking game readiness'});try{await this.game.preflight?.(assignment);this.activity({id:activityId,sessionId:assignment.id,category:'preflight',status:'completed',at:new Date().toISOString(),detail:assignment.construction==='character'?'Visible builder connected':'Headless-compatible direct construction ready'});}catch(error){this.activity({id:activityId,sessionId:assignment.id,category:'preflight',status:'failed',at:new Date().toISOString(),detail:String(error)});throw error;}}
  private async resolveAssignment(raw:Record<string,unknown>):Promise<WorkshopAssignment>{
    if(Array.isArray(raw.ports)){const assignment=validateWorkshopAssignment(raw),output=assignment.ports.find(value=>value.direction==='output'&&value.required)!;const installed=await this.game.resolveProfile(assignment.profileId,output.product.name),facts=this.installed(installed);if(assignment.profileRevision!==installed.profileRevision||assignment.gameFingerprint!==facts.fingerprint)throw new Error('Resolved assignment no longer matches installed game data');const sourceRevision=this.sourceRevision(assignment);await this.persist(assignment.id,'resolved.json',{assignment,installed,profile:facts.profile,recipe:facts.recipe,sourceRevision} satisfies ResolvedData);return assignment;}
    const objective=String(raw.objective??''),target=productFromBrief(objective),installed=await this.game.resolveProfile(String(raw.profileId??''),target.product);
    const {fingerprint,profile,recipe}=this.installed(installed);
    const output=installed.recipe.products.find(value=>value.name===target.product);if(!output)throw new Error(`Installed recipe ${installed.recipe.id} does not produce ${target.product}`);
    const outputRate=rationalFromDecimal(target.rate,'minute'),craftRate=number(outputRate)/output.amount;
    const ports=[...installed.recipe.ingredients.map((ingredient,index)=>({id:`input-${ingredient.name}`,direction:'input' as const,product:{kind:ingredient.type,name:ingredient.name,quality:'normal' as const,surface:installed.surface,...(ingredient.temperature===undefined?{}:{temperature:ingredient.temperature})},position:{x:-12,y:index*4-4},facing:4,transport:ingredient.type==='fluid'?'pipe' as const:'belt' as const,...(ingredient.type==='item'?{lane:1 as const}:{}),rate:rationalFromDecimal(String(craftRate*ingredient.amount)),unit:'units-per-game-second' as const,required:true})),{id:`output-${target.product}`,direction:'output' as const,product:{kind:output.type,name:output.name,quality:'normal' as const,surface:installed.surface,...(output.temperature===undefined?{}:{temperature:output.temperature})},position:{x:12,y:0},facing:12,transport:output.type==='fluid'?'pipe' as const:'belt' as const,...(output.type==='item'?{lane:1 as const}:{}),rate:outputRate,unit:'units-per-game-second' as const,required:true}];
    const windowTicks=Number(raw.windowTicks),windows=Number(raw.windows);delete raw.windowTicks;delete raw.windows;
    const assignment=validateWorkshopAssignment({...raw,source:{...object(raw.source),numericTargetText:`${target.rate} per minute`},profileRevision:installed.profileRevision,gameFingerprint:fingerprint,footprint:{width:64,height:32,clearance:4,maxTiles:512*512},ports,throughput:[{portId:`output-${target.product}`,windowTicks,windows,quantum:{numerator:'1',denominator:'1'},productionError:{numerator:'0',denominator:'1'},deliveryError:{numerator:'0',denominator:'1'},maxStockDrawdown:{numerator:'2',denominator:'1'},maxResidual:{numerator:'1',denominator:'1'},interval:'(startTick,endTick]'}]});
    const sourceRevision=this.sourceRevision(assignment);await this.persist(assignment.id,'resolved.json',{assignment,installed,profile,recipe,sourceRevision} satisfies ResolvedData);return assignment;
  }
  private async usage(id:string):Promise<DurableInferenceUsage>{try{const state=JSON.parse(await readFile(path.join(this.sessionDirectory(id),'provider-budget.json'),'utf8'))as DurableInferenceUsage;for(const owner of ['workshop','learning'] as const)state[owner]={turns:state[owner]?.turns??0,tools:state[owner]?.tools??0,elapsedMs:state[owner]?.elapsedMs??0,tokens:state[owner]?.tokens??0,unknownTokens:state[owner]?.unknownTokens??false};state.invocations??={};return state;}catch(error){if(!(error&&typeof error==='object'&&'code'in error&&error.code==='ENOENT'))throw error;return emptyInferenceUsage();}}
  private async invoke(session:WorkshopSessionState,role:WorkshopRole,selection:ModelSelection,observation:unknown,prompt:string,instructions:string,owner:'workshop'|'learning',invocationId:string):Promise<string>{
    const state=await this.usage(session.id),admissions=new WorkshopInferenceAdmissions(session.id,session.assignment.budgets,state),prior=admissions.completed(invocationId);if(prior!==null)return prior;
    const admission=admissions.admit(owner,role,invocationId);await this.persist(session.id,'provider-budget.json',state);const started=performance.now();
    this.activity({id:invocationId,sessionId:session.id,category:'provider',status:'started',at:new Date().toISOString(),iteration:session.activeIteration,role,detail:`${selection.modelId}/${selection.reasoningEffort}`});
    try{const raw=await this.inference.invoke(session,role,selection,observation,prompt,instructions,admission),result:InferenceResult=typeof raw==='string'?{text:raw,usage:{turns:1,tools:1,elapsedMs:Math.max(0,Math.round(performance.now()-started)),tokens:null}}:raw;admissions.complete(admission,result.usage,result.text);await this.persist(session.id,'provider-budget.json',state);this.services?.usage.record({id:`${invocationId}:complete`,sessionId:session.id,invocationId,role,iteration:session.activeIteration,batchId:owner==='learning'?session.assignment.comparisonSeries:null,cumulativeTokens:result.usage.tokens,monetaryAmount:null,allowanceRemaining:null,owner,at:new Date().toISOString()});this.activity({id:invocationId,sessionId:session.id,category:'provider',status:'completed',at:new Date().toISOString(),iteration:session.activeIteration,role,detail:`${selection.modelId}/${selection.reasoningEffort}`,usage:result.usage});return result.text;}catch(error){admissions.unknown(admission,Math.round(performance.now()-started));await this.persist(session.id,'provider-budget.json',state);this.activity({id:invocationId,sessionId:session.id,category:'provider',status:'failed',at:new Date().toISOString(),iteration:session.activeIteration,role,detail:String(error)});throw new WorkshopEffectOutcomeError('unknown',error);}
  }
  private learningBundle(session:WorkshopSessionState){const pinned=this.services?.learning.pinnedBundle(session.id);if(!pinned)return null;if(pinned.hash!==session.pinnedBundleHash)throw new Error('Pinned learning bundle changed during workshop session');return pinned;}
  private async activatedLearning(session:WorkshopSessionState,resolved:ResolvedData):Promise<ActivatedLearningContext>{
    const pinned=this.learningBundle(session);if(!pinned||pinned.hash==='baseline')return{bundleHash:'baseline',lessons:null,helperPlan:null,evidence:[]};const receipt=path.join(this.sessionDirectory(session.id),'learning-consumption.json');try{return JSON.parse(await readFile(receipt,'utf8'))as ActivatedLearningContext;}catch(error){if(!(error&&typeof error==='object'&&'code'in error&&error.code==='ENOENT'))throw error;}
    const lessons=pinned.files['lessons.json']??null,evidence:string[]=[];if(lessons)evidence.push(`activated-lessons:${contentDigest(lessons)}`);let helperPlan:unknown|null=null;const helper=pinned.files['design-helper.mjs'];if(helper){const bundleRoot=path.join(this.sessionDirectory(session.id),'active-bundle'),scratch=path.join(this.sessionDirectory(session.id),'helper-scratch');await mkdir(bundleRoot,{recursive:true});await mkdir(scratch,{recursive:true});const helperFile=path.join(bundleRoot,'design-helper.mjs'),expectedHash=contentDigest(helper);await writeFile(helperFile,helper);const policy={wallMs:5000,inputBytes:128*1024,outputBytes:32*1024,scratchBytes:32*1024,invocations:1,policyHash:pinned.policyHash};try{const raw=await invokeConfinedHelper({worker:helperWorker,bundleRoot,helper:helperFile,expectedHash,scratch,value:{revision:session.assignment.revision,assignment:session.assignment,installed:resolved.installed,sourceRevision:resolved.sourceRevision},policy,quota:new HelperQuota(policy)});helperPlan=authorizeHelperPlan(raw,session.assignment.revision,['suggestion','constraint'],16);evidence.push(`activated-helper:${expectedHash}`);}catch(error){evidence.push(`activated-helper-rejected:${expectedHash}:${digest(String(error))}`);}}
    const result={bundleHash:pinned.hash,lessons,helperPlan,evidence};await this.persist(session.id,'learning-consumption.json',result);return result;
  }
  async design(session:WorkshopSessionState,iteration:number):Promise<WorkshopCandidateRef>{
    const resolved=await this.resolved(session.id),bundle=this.learningBundle(session),activatedLearning=await this.activatedLearning(session,resolved),files=bundle?.files??{},reply=await this.invoke(session,'workshop-designer',session.selections.designer,{assignment:session.assignment,installed:resolved.installed,sourceRevision:resolved.sourceRevision,priorIterations:session.iterations.map(value=>({number:value.number,feedback:value.feedback,valid:value.valid})),assistance:session.assistance,activatedLearning},`Design attempt ${iteration}. Return exactly one JSON object matching BlueprintDocument schema 1. Use only allowed equipment, the installed recipe and normal quality. Existing source/sink/power fixtures occupy the declared port positions, so place candidate entities adjacent and connect them. Keep every entity inside x=-10..10 and y=-12..12.${resolved.sourceRevision?' Improve the supplied exact source revision; preserve its identity only where measured evidence supports it.':''}`,`You are the library-independent AutoFactorio workshop designer. Produce a legal compact Factorio blueprint document from the supplied public assignment and installed-data facts. Do not use markdown outside the JSON object.${files['designer.instructions']?`\nActivated instructions:\n${files['designer.instructions']}`:''}`,'workshop',`${session.id}:${iteration}:designer`);
    const document=designerDocument(jsonObject(reply),session.assignment,resolved),artifactHash=blueprintContentHash(document);await this.persist(session.id,`${artifactHash}.json`,document);return{sessionId:session.id,iteration,artifactHash,assignmentRevision:session.assignment.revision,bundleHash:session.pinnedBundleHash,evidence:[`managed-designer:${session.selections.designer.modelId}:${session.selections.designer.reasoningEffort}`,`artifact:${artifactHash}`,...activatedLearning.evidence]};
  }
  async build(session:WorkshopSessionState,candidate:WorkshopCandidateRef):Promise<void>{const resolved=await this.resolved(session.id),document=await this.document(candidate);try{const built=await this.game.build(session,document,resolved.profile);await this.persist(session.id,`${candidate.artifactHash}.built.json`,built);}catch(error){if(error instanceof WorkshopEffectOutcomeError)throw error;throw new WorkshopEffectOutcomeError('unknown',error);}}
  async measure(session:WorkshopSessionState,candidate:WorkshopCandidateRef):Promise<WorkshopEvaluationReport>{const built=await this.built(candidate);try{return await this.game.measure(session,built);}catch(error){if(error instanceof WorkshopEffectOutcomeError)throw error;throw new WorkshopEffectOutcomeError('unknown',error);}}
  async score(session:WorkshopSessionState,candidate:WorkshopCandidateRef,evaluation:WorkshopEvaluationReport):Promise<{score:WorkshopScore;feedback:string}>{
    const resolved=await this.resolved(session.id),document=await this.document(candidate),score=scoreWorkshop({sessionId:session.id,iteration:candidate.iteration,assignmentRevision:session.assignment.revision,bundleHash:session.pinnedBundleHash,document,evaluation,rubricVersion:session.assignment.rubric.version,routes:installedRoutes([resolved.recipe]),rawResources:resolved.recipe.ingredients.map(value=>value.name),expansion:[],energy:null,inputs:null,outputs:null,interaction:{rejectedCalls:0,rebuilds:0,unknownOutcomes:0,toolCalls:0,reportedTokens:null,evidence:candidate.evidence}});
    const bundle=this.learningBundle(session),activatedLearning=await this.activatedLearning(session,resolved),files=bundle?.files??{},feedback=await this.invoke(session,'workshop-scorer',session.selections.scorer,{assignment:session.assignment,document,evaluation,score,activatedLearning:{bundleHash:activatedLearning.bundleHash,lessons:activatedLearning.lessons,evidence:activatedLearning.evidence}},'Critique this measured candidate. Return one JSON object with a concise string field named feedback. Do not revise measured values or claim access to other library designs.',`You are the library-blind AutoFactorio workshop scorer. Treat supplied game evidence and deterministic score fields as immutable.${files['scorer.instructions']?`\nActivated instructions:\n${files['scorer.instructions']}`:''}`,'workshop',`${session.id}:${candidate.iteration}:scorer`);return{score,feedback:String(jsonObject(feedback).feedback??score.feedback)};
  }
  async finalization(session:WorkshopSessionState):Promise<{admission:LibraryAdmission|null;learningRequired:boolean}>{
    const best=session.bestIteration===null?null:session.iterations[session.bestIteration-1]!,resolved=await this.resolved(session.id);let admission:LibraryAdmission|null=null;
    if(best?.artifact&&best.evaluation&&best.score?.eligible&&session.assignment.libraryAccess){const document=await this.document(best.artifact),built=await this.built(best.artifact),output=session.assignment.ports.find(value=>value.direction==='output'&&value.required)!,library=this.services?.library;if(!library)throw new Error('Trusted library unavailable for admission');const comparable=library.search({product:output.product.name,profileId:session.assignment.profileId,gameFingerprint:session.assignment.gameFingerprint,limit:100}),rubricHash=workshopRubricHash(session.assignment.rubric),exact=comparable.filter(value=>library.get(value.revisionHash).evidence.rubricHash===rubricHash),hash=blueprintContentHash(document);if(session.assignment.improveRevision){const parent=comparable.find(value=>value.revisionHash===session.assignment.improveRevision);if(!parent)throw new Error('Improve parent disappeared before finalization');if(library.get(parent.revisionHash).evidence.rubricHash!==rubricHash)throw new Error('Improve parent rubric definition mismatch');}let distinction:string[]=[];if(!comparable.length)distinction=['first-compatible-revision'];else if(!comparable.some(value=>value.revisionHash===hash)){const targets=session.assignment.improveRevision?exact.filter(value=>value.revisionHash===session.assignment.improveRevision):exact;const comparisons=targets.map(value=>({hash:value.revisionHash,result:compareWorkshopScores(best.score!,library.get(value.revisionHash).evidence.score,session.assignment.rubric)}));if(comparisons.length&&comparisons.every(value=>value.result>0))distinction=comparisons.map(value=>`materially-better-than:${value.hash}`);}if(distinction.length)admission={identity:{familyId:`product-${output.product.name}`,variantId:`${session.assignment.profileId}-${session.assignment.construction}`,parentHash:session.assignment.improveRevision,label:document.label},document,proof:{score:best.score,evaluation:best.evaluation,rubric:structuredClone(session.assignment.rubric),rubricHash,profileId:session.assignment.profileId,gameFingerprint:session.assignment.gameFingerprint,outputPortId:output.id,exportValid:true,characterBuildEvidence:built.characterEvidence,compatibilityEvidence:[`installed-profile:${resolved.profile.fingerprint}`,`rubric:${rubricHash}`],distinctionEvidence:distinction,admit:true},operationId:`${session.id}-admit-${best.artifact.artifactHash}`};}
    const completed=(this.services?.sessions().filter(value=>value.stage==='complete').length??0)+1,policy=session.assignment.learning,learningRequired=policy.cadence==='after-session'||policy.cadence==='batch'&&completed%policy.batchSessions===0;return{admission,learningRequired};
  }
  async prepareLearning(session:WorkshopSessionState):Promise<{activationRequired:boolean}>{
    const learning=this.services?.learning;if(!learning)throw new Error('Learning service unavailable');
    let raw:Record<string,unknown>;try{raw=jsonObject(await this.invoke(session,'workshop-learnings',session.selections.learnings,{assignment:session.assignment,iterations:session.iterations.map(value=>({number:value.number,valid:value.valid,feedback:value.feedback,score:value.score}))},'Decide whether repeated public evidence warrants a bounded reusable learning candidate. Return one JSON object with decision, scope, reason, evidence, and optional content. Use decision "no-change" unless a concrete repeated failure supports a change.','You are the scoped AutoFactorio learnings role. You cannot activate changes and must not use private library comparison content.','learning',`${session.id}:learnings`));}catch(error){const reason=String(error),pin=learning.pin(session.id),outcome:LearningOutcome={schema:1,id:`${session.id}-learning`,decision:'defer',scope:'lesson',evidence:[`maintenance-deferred:${digest(reason)}`],candidateHash:null,incumbentHash:pin.hash,expectedGeneration:pin.generation,bundleHash:null,activatedGeneration:null,reason:'Learning inference was admitted but did not produce one confirmed usable outcome; maintenance is deferred without changing the active bundle',revisitCondition:'learning-inference-confirmed'};learning.recordOutcome(outcome);await this.persist(session.id,'learning-plan.json',{outcome,activationHash:null});return{activationRequired:false};}
    const allowed=['accept','refine','merge','reject','defer','no-change'] as const,scopes=['designer-instructions','scorer-instructions','lesson','design-helper'] as const;
    let decision=allowed.includes(raw.decision as typeof allowed[number])?raw.decision as typeof allowed[number]:'no-change',reason=typeof raw.reason==='string'&&raw.reason.trim()?raw.reason:'No reusable change supported by the public session evidence';
    const scope=scopes.includes(raw.scope as typeof scopes[number])?raw.scope as typeof scopes[number]:'lesson',evidence=Array.isArray(raw.evidence)?raw.evidence.filter(value=>typeof value==='string'&&value.length) as string[]:[];if(!evidence.length)evidence.push(`workshop-session:${session.id}`);
    const pin=learning.pin(session.id),id=`${session.id}-learning`,content=typeof raw.content==='string'&&raw.content.trim()?raw.content:reason,duplicate=learning.duplicate(scope,content);let candidateHash:string|null=null,bundleHash:string|null=null;
    if(decision!=='no-change'&&duplicate){decision='no-change';reason=`Unchanged evidence matches existing candidate ${duplicate.id}; revisit condition not satisfied`;candidateHash=duplicate.contentHash;}
    if(decision!=='no-change'){const candidate=learning.candidate({id,batchId:session.assignment.comparisonSeries,scope,content,evidence,contextLineage:[`public-session:${session.id}`],libraryIndependent:true});candidateHash=candidate.contentHash;learning.attempt(id);learning.decide(id,decision,reason,null);if(decision==='accept'||decision==='merge'){const file=scope==='designer-instructions'?'designer.instructions':scope==='scorer-instructions'?'scorer.instructions':scope==='design-helper'?'design-helper.mjs':'lessons.json',fileContent=scope==='lesson'?JSON.stringify([{id,content,evidence}]):content,bundle=learning.assemble({incumbentHash:pin.hash,expectedGeneration:pin.generation,files:{[file]:fileContent},requiredControls:[`workshop:${session.assignment.comparisonSeries}`],policyHash:'workshop-learning-v1',retrievalHash:digest(evidence),catalogHash:digest(session.selections),candidates:[id]});bundleHash=bundle.hash;}}
    const activationHash=bundleHash&&session.assignment.learning.autoActivate&&learning.activationReady(bundleHash)?bundleHash:null,outcome:LearningOutcome={schema:1,id,decision,scope,evidence,candidateHash,incumbentHash:pin.hash,expectedGeneration:pin.generation,bundleHash,activatedGeneration:null,reason,revisitCondition:null};learning.recordOutcome(outcome);await this.persist(session.id,'learning-plan.json',{outcome,activationHash});return{activationRequired:activationHash!==null};
  }
  async activateLearning(session:WorkshopSessionState):Promise<void>{const learning=this.services?.learning;if(!learning)throw new Error('Learning service unavailable');const plan=JSON.parse(await readFile(path.join(this.sessionDirectory(session.id),'learning-plan.json'),'utf8'))as{outcome:LearningOutcome;activationHash:string|null};if(!plan.activationHash)throw new Error('No verified learning activation prepared');const catalog=learning.activate(plan.activationHash,`${session.id}:learning-activate`);learning.recordOutcome({...plan.outcome,activatedGeneration:catalog.generation});}
  async reconcile<T>(session:WorkshopSessionState,operationId:string):Promise<{resolved:true;value:T}|{resolved:false}>{if(operationId===`${session.id}:finalization`)return{resolved:true,value:await this.finalization(session) as T};if(operationId.endsWith(':build')){const artifact=session.activeIteration===null?null:session.iterations[session.activeIteration-1]?.artifact;if(artifact)try{await this.built(artifact);return{resolved:true,value:{completed:true} as T};}catch{/* no durable host receipt */}}if(operationId===`${session.id}:learning-prepare`)try{const plan=JSON.parse(await readFile(path.join(this.sessionDirectory(session.id),'learning-plan.json'),'utf8'))as{activationHash:string|null};return{resolved:true,value:{activationRequired:plan.activationHash!==null} as T};}catch{/* no durable plan */}if(operationId===`${session.id}:learning-activate`)try{await this.activateLearning(session);return{resolved:true,value:{completed:true} as T};}catch{/* activation cannot be safely inferred */}return{resolved:false};}
  async cancel(sessionId:string):Promise<EffectReceipt>{const adapters=[['inference',this.inference.cancel?.bind(this.inference)],['game',this.game.cancel?.bind(this.game)]] as const,results=await Promise.allSettled(adapters.map(([,cancel])=>Promise.resolve().then(()=>cancel?.(sessionId)))),receipts=results.map((value,index)=>{const source=`${adapters[index]![0]}_cancellation`,effectId=`${adapters[index]![0]}:${sessionId}`;return value.status==='rejected'?{schema:1 as const,effectId,outcome:'unknown' as const,failures:[`${source}:${String(value.reason)}`]}:normalizeEffectReceipt(value.value,effectId,source);});return combineEffectReceipts(`workshop:${sessionId}`,receipts);}
  async close(){await this.inference.close();}
}

export class LiveWorkshopGame implements WorkshopGame {
  private control:WorkshopControl;
  private cancelled=new Set<string>();
  private active=new Set<string>();
  constructor(port:CommandPort,private client:GameClient,private lifecycle:Lifecycle,private activity:ActivitySink=()=>{}){this.control=new WorkshopControl(port);}
  resolveProfile(profileId:string,product:string){return this.control.installedProfile(profileId,product);}
  async preflight(assignment:WorkshopAssignment):Promise<void>{
    if(assignment.construction!=='character')return;
    const world=await this.client.request({...observeRequest,surface:assignment.ports[0]?.product.surface??'nauvis'}),actors=object(world.actors??{}),actor=object(actors['builder-1']??{});
    if(actor.connected!==true)throw new Error('Legal character requires the visible Factorio client and connected builder-1. Restart with ordinary npm start (without --headless), wait for Factorio to connect, then launch again. No model inference was started.');
  }
  async build(session:WorkshopSessionState,document:BlueprintDocument,profile:CapabilityProfile):Promise<BuiltData>{
    const activityId=`${session.id}:${session.activeIteration}:game-build`;this.activity({id:activityId,sessionId:session.id,category:'game',status:'started',at:new Date().toISOString(),iteration:session.activeIteration,detail:session.assignment.construction});this.active.add(session.id);try{
    if(this.cancelled.has(session.id))throw new Error('Workshop game operation cancelled');
    const id=`${session.id}-${session.activeIteration}`,surface=`af-workshop-${digest(id).slice(0,16)}`,force=surface,fixtures:WorkshopFixture[]=[...session.assignment.ports.map(port=>({id:port.id,kind:port.direction==='output'||port.direction==='byproduct'?'sink' as const:'source' as const,position:port.position,product:{kind:port.product.kind,name:port.product.name,quality:'normal' as const},rate:number(port.rate)})),{id:'power',kind:'power',position:{x:0,y:14},product:{kind:'item',name:'electricity',quality:'normal'},rate:0}];
    let setup:Record<string,unknown>;try{setup=await this.control.setup({id,surface,force,profile,area:[{x:-256,y:-256},{x:256,y:256}],maxTiles:session.assignment.footprint.maxTiles,fixtures});}catch(error){if(!/workshop_exists/.test(String(error)))throw error;setup=await this.control.inspect(id);}
    const generation=Number(setup.generation);let characterEvidence:string[]|null=null;
    if(session.assignment.construction==='direct')await this.control.materialize(id,generation,`${id}-materialize`,document);else{
      const actor='builder-1';await this.control.enter(id,actor);const required=billOfMaterials(document),provision=await this.control.provision(id,actor,`${id}-provision`,Object.entries(required).map(([name,count])=>({name,quality:'normal' as const,count}))),inventory=Object.fromEntries((provision.after as {name:string;count:number}[]).map(value=>[value.name,value.count]));
      const plan=compileCharacterBlueprint(document,inventory,()=>true);let state=await this.lifecycle.inspect();if(state.armed||!state.paused||!state.neutral)state=await this.lifecycle.pause(state);const grantGeneration=state.generation+1,assignment:Assignment={id:`workshop-${digest(id).slice(0,12)}`,owner:'workshop-runtime',task:'workshop-build',revision:1,actor,resources:[{grant:{id:`area-${digest(id).slice(0,12)}`,generation:grantGeneration},resource:{kind:'area',surface,bounds:[{x:-256,y:-256},{x:256,y:256}]}},{grant:{id:`items-${digest(id).slice(0,12)}`,generation:grantGeneration},resource:{kind:'items',actor}},{grant:{id:`actor-${digest(id).slice(0,12)}`,generation:grantGeneration},resource:{kind:'actor',actor}}]};state=await this.lifecycle.reconcile(state,[assignment]);state=await this.lifecycle.arm(state);const batches=constructionBatches(plan,{commandPrefix:`workshop-${digest(id).slice(0,10)}`,epoch:state.epoch,session:state.session,task:assignment.task,revision:assignment.revision,actor,surface,grants:assignment.resources.map(value=>value.grant),deadline:state.tick+Math.max(36000,session.assignment.budgets.gameTicks)},100);characterEvidence=[];for(const batch of batches){if(this.cancelled.has(session.id))throw new Error('Workshop game operation cancelled');await this.client.request({op:'submit',batch});for(;;){if(this.cancelled.has(session.id))throw new Error('Workshop game operation cancelled');state=await this.lifecycle.heartbeat(state);const receipt=await this.client.receipt(batch.commandId);if(receipt&&!['accepted','running'].includes(receipt.status)){requireCompletedCharacterReceipt(receipt);characterEvidence.push(`game-receipt:${batch.commandId}:${receipt.endedTick}`);break;}await delay(25);}}state=await this.lifecycle.pause(state);
    }
    const result={id,generation,surface,characterEvidence};this.activity({id:activityId,sessionId:session.id,category:'game',status:'completed',at:new Date().toISOString(),iteration:session.activeIteration,detail:`${session.assignment.construction}:${characterEvidence?.length??0} receipts`});return result;}catch(error){this.activity({id:activityId,sessionId:session.id,category:'game',status:'failed',at:new Date().toISOString(),iteration:session.activeIteration,detail:String(error)});throw error;}finally{this.active.delete(session.id);}
  }
  async measure(session:WorkshopSessionState,built:BuiltData):Promise<WorkshopEvaluationReport>{const activityId=`${session.id}:${session.activeIteration}:game-measure`;this.activity({id:activityId,sessionId:session.id,category:'game',status:'started',at:new Date().toISOString(),iteration:session.activeIteration,detail:'Fixed-window measurement'});this.active.add(session.id);try{const rule=session.assignment.throughput[0]!,attemptId=`attempt-${digest(`${session.id}:${session.activeIteration}`).slice(0,20)}`,expectedAttemptId=`${session.id}:${session.activeIteration}`;await this.control.measureConfigure({id:built.id,generation:built.generation,attemptId,settlingTicks:session.assignment.settlingTicks,windowTicks:rule.windowTicks,windows:rule.windows,requestedSpeed:number(session.assignment.requestedSpeed),ports:session.assignment.ports.filter(value=>value.direction==='output'&&value.required).map(value=>({id:value.id,fixtureId:value.id,product:{kind:value.product.kind,name:value.product.name,quality:'normal'}}))});let after=-1;const samples=[];const deadline=Date.now()+session.assignment.budgets.wallMs;while(Date.now()<deadline){if(this.cancelled.has(session.id))throw new Error('Workshop game operation cancelled');const page=await this.control.measureRead(built.id,attemptId,after);for(const sample of page.samples){samples.push({...sample,attemptId:expectedAttemptId});after=Math.max(after,sample.index);}if(page.finished){const result=evaluateWorkshop(session.assignment,samples);this.activity({id:activityId,sessionId:session.id,category:'game',status:'completed',at:new Date().toISOString(),iteration:session.activeIteration,detail:`${samples.length} samples; ${result.valid?'valid':'invalid'}`});return result;}await delay(100);}throw new Error('Workshop measurement exceeded wall budget');}catch(error){this.activity({id:activityId,sessionId:session.id,category:'game',status:'failed',at:new Date().toISOString(),iteration:session.activeIteration,detail:String(error)});throw error;}finally{this.active.delete(session.id);}}
  cancel(sessionId:string):EffectReceipt{this.cancelled.add(sessionId);return this.active.has(sessionId)?{schema:1,effectId:`game:${sessionId}`,outcome:'unknown',failures:['game_cancellation:no_receipt_for_active_workshop_effect']}:effectReceipt(`game:${sessionId}`,'cancelled');}
}

export class ManagedWorkshopInference implements WorkshopInference {
  private active=new Map<string,{provider:Provider;gateway:Gateway;token:string}>();
  private cancelledSessions=new Set<string>();
  constructor(private executable:string,private directory:string,private mcpNames:string[],private sink:Sink,private listenGateway:(gateway:Gateway)=>ReturnType<Gateway['listen']>=gateway=>gateway.listen()){}
  async invoke(session:WorkshopSessionState,role:WorkshopRole,selection:ModelSelection,observation:unknown,prompt:string,instructions:string,admission:WorkshopInferenceAdmission):Promise<InferenceResult>{
    if(admission.schema!==1||admission.sessionId!==session.id||admission.role!==role||!admission.invocationId.startsWith(`${session.id}:`))throw new Error('Managed workshop inference requires an exact aggregate admission');const limits=admission.limits;if(this.cancelledSessions.has(session.id))throw new Error('Managed workshop invocation cancelled before setup');const caps={turns:limits.turns,concurrency:1,turnMs:Math.min(limits.wallMs,10*60_000),runMs:limits.wallMs,tools:limits.tools,tokens:limits.tokens},active:{provider?:Provider}={};const budget=new Budget(caps,()=>performance.now(),turn=>{gateway.revokeTurn(turn.id);void active.provider?.interruptStatus();});const gateway=new Gateway(budget,this.sink),server=await this.listenGateway(gateway);if(this.cancelledSessions.has(session.id)){await server.close();throw new Error('Managed workshop invocation cancelled during setup');}const token=gateway.issue(role);gateway.setObservation(role,observation);const turnDirectory=path.join(this.directory,'provider',session.id,admission.invocationId.replace(/[^\w.-]/g,'-'));await mkdir(turnDirectory,{recursive:true});if(this.cancelledSessions.has(session.id)){await server.close();throw new Error('Managed workshop invocation cancelled during setup');}const overrides=profileOverrides(this.mcpNames,path.join(turnDirectory,'logs'),selection);overrides['mcp_servers.autofactorio.url']=server.url;overrides['mcp_servers.autofactorio.http_headers.Authorization']=`Bearer ${token}`;overrides['mcp_servers.autofactorio.enabled']=true;overrides['mcp_servers.autofactorio.default_tools_approval_mode']='approve';const rpc=new AppServerRpc(this.executable,turnDirectory,overrides);let text='';const sink:Sink=event=>{this.sink(event);if(event.kind==='item/agentMessage/delta'&&typeof object(event.data).delta==='string')text+=String(object(event.data).delta);};const provider=active.provider=new Provider(role,rpc,budget,sink,()=>gateway.revoke(token),async()=>{gateway.revoke(token);return false;},selection);this.active.set(admission.invocationId,{provider,gateway,token});
    try{await provider.initialize();await provider.sessionStart(turnDirectory,undefined,instructions);await provider.catalog((role==='workshop-designer'?['observe','checkpoint']:['observe']).map(name=>`autofactorio:${name}`));await provider.start(`${prompt}\nCall observe once to obtain the immutable input.`,id=>gateway.bind(token,id));const deadline=Date.now()+caps.turnMs+30_000;while(provider.turn?.finished!==true){if(Date.now()>deadline)throw new Error(`${role} completion unconfirmed`);await delay(50);}const state=budget.snapshot();return{text,usage:{turns:state.spentTurns,tools:state.attempts,elapsedMs:Math.round(state.elapsedMs),tokens:state.reportedTokens||null}};}finally{this.active.delete(admission.invocationId);provider.close();await server.close();}
  }
  async cancel(sessionId:string):Promise<EffectReceipt>{this.cancelledSessions.add(sessionId);const values=[...this.active.entries()].filter(([id])=>id.startsWith(`${sessionId}:`));const results=await Promise.all(values.map(async([,value])=>{value.gateway.revoke(value.token);const effectId=`provider:${value.provider.session??value.provider.role}`;return normalizeEffectReceipt(await value.provider.interruptStatus(),effectId,'provider_cancellation');}));return combineEffectReceipts(`inference:${sessionId}`,results);}
  async close(){await Promise.allSettled([...this.active.values()].map(value=>{value.gateway.revoke(value.token);return value.provider.interruptStatus();}));}
}

export async function prepareLiveWorkshopHost(options:{directory:string;codexExecutable:string;port:CommandPort;game:GameClient;lifecycle:Lifecycle;events?:(event:Activity)=>void;activity?:ActivitySink}):Promise<{host:LiveWorkshopHost;catalog:ManagedCatalog}>{
  if(!path.isAbsolute(options.codexExecutable))throw new Error('Workshop Codex executable must be absolute');await mkdir(options.directory,{recursive:true});const bootstrap=new AppServerRpc(options.codexExecutable,options.directory,{forced_login_method:'chatgpt',model_provider:'openai','features.apps':false,'features.plugins':false});try{await bootstrap.call('initialize',{clientInfo:{name:'autofactorio_workshop',version:'0.1.0'},capabilities:{experimentalApi:true}});const catalog=await managedCatalog(bootstrap),config=object(object(await bootstrap.call('config/read',{cwd:options.directory})).config),mcpNames=Object.keys(object(config.mcp_servers??{})),sink:Sink=event=>{appendFileSync(path.join(options.directory,'workshop-provider-events.jsonl'),JSON.stringify(event)+'\n');options.events?.(event);};return{host:new LiveWorkshopHost(options.directory,new ManagedWorkshopInference(options.codexExecutable,options.directory,mcpNames,sink),new LiveWorkshopGame(options.port,options.game,options.lifecycle,options.activity),options.activity),catalog};}finally{bootstrap.close();}
}
